import assert from 'node:assert/strict';
import { resolveCampaignAddress } from './recipient-address.ts';
const input={profileEmail:' Profile@Example.com ',authEmail:'auth@example.com',authConfirmed:true,campaignKey:'activation',campaignStep:'activation_1',templateVersion:'v1',deliveries:[]};
const primary={id:'p1',email:'profile@example.com',campaign_key:'activation',campaign_step:'activation_1',template_version:'v1',metadata:{address_source:'profile'},bounced_at:'2026-09-02'};
assert.equal(resolveCampaignAddress(input).email,'profile@example.com');
assert.equal(resolveCampaignAddress({...input,authConfirmed:false}),null);
assert.equal(resolveCampaignAddress({...input,profileEmail:''}).email,'auth@example.com');
assert.equal(resolveCampaignAddress({...input,profileEmail:'bad address'}).email,'auth@example.com');
const fallback=resolveCampaignAddress({...input,deliveries:[primary]});
assert.equal(fallback.email,'auth@example.com');
assert.equal(fallback.fallbackFromDeliveryId,'p1');
assert.equal(fallback.templateVersion,'v1.auth-fallback');
assert.equal(resolveCampaignAddress({...input,authEmail:'PROFILE@example.com',deliveries:[primary]}),null);
assert.equal(resolveCampaignAddress({...input,deliveries:[{...primary,bounced_at:null,send_status:'sending'}]}).email,'profile@example.com','Timeouts do not authorize a fallback');
assert.equal(resolveCampaignAddress({...input,deliveries:[{...primary,delivered_at:'2026-09-02'}]}).email,'profile@example.com','Known delivery does not authorize a fallback');
assert.equal(resolveCampaignAddress({...input,deliveries:[primary,{...primary,id:'f1',email:'auth@example.com',template_version:'v1.auth-fallback',bounced_at:null,send_status:'sending'}]}),null,'An in-flight fallback cannot be repeated');
assert.equal(resolveCampaignAddress({...input,deliveries:[{...primary,metadata:{}}]}).email,'profile@example.com','Legacy auth-first bounces cannot be reclassified as failed profile sends');
assert.equal(resolveCampaignAddress({...input,deliveries:[{...primary,bounced_at:null,send_status:'delivery_failed'}]}).email,'auth@example.com');
console.log('Profile-first selection, confirmed-auth fallback, duplicate and ambiguous delivery tests passed.');
