import assert from 'node:assert/strict';
import { campaignIneligibilityReason, isEligibleForCampaign, profileCohort, type CampaignProfile } from './segments.ts';

const now = Date.now();
const base: CampaignProfile = { userId: 'u', email: 'u@example.com', confirmed: true, receiveEmails: true, marketingConsentAt: now - 86400000, accountCreatedAt: now - 2 * 86400000, firstName: null, profileComplete: false, currentlyEntitled: false, hasDeliverySuppression: false, firstUseAt: null, lastUseAt: null, priorSteps: new Set(), priorStepAt: new Map(), optedOutTopics: new Set() };
assert.equal(isEligibleForCampaign(base, 'activation_1', now), true);
assert.equal(isEligibleForCampaign({ ...base, receiveEmails: false }, 'activation_1', now), false);
assert.equal(campaignIneligibilityReason({ ...base, marketingConsentAt: null }, 'activation_1', now), 'explicit_consent_missing');
assert.equal(campaignIneligibilityReason({ ...base, accountCreatedAt: now - 31 * 86400000 }, 'activation_1', now), 'account_too_old');
assert.equal(campaignIneligibilityReason({ ...base, hasDeliverySuppression: true }, 'activation_1', now), 'delivery_suppressed');
assert.equal(isEligibleForCampaign({ ...base, optedOutTopics: new Set(['brobot_learning']) }, 'activation_1', now), false);
assert.equal(isEligibleForCampaign({ ...base, currentlyEntitled: true }, 'activation_1', now), false);
assert.equal(isEligibleForCampaign({ ...base, firstUseAt: now - 1000, lastUseAt: now - 1000 }, 'conversion_1', now), true);
assert.equal(isEligibleForCampaign({ ...base, priorSteps: new Set(['activation_1']), priorStepAt: new Map([['activation_1', now - 4 * 86400000]]) }, 'activation_2', now), true);
assert.equal(isEligibleForCampaign({ ...base, priorSteps: new Set(['activation_1']), priorStepAt: new Map([['activation_1', now - 86400000]]) }, 'activation_2', now), false);
assert.equal(profileCohort(null), 'empty');
assert.equal(profileCohort({ training_level: '', grad_year: null, full_name: 'Alex', email: 'a@example.com' }), 'empty');
assert.equal(profileCohort({ training_level: 'MD/DO Student', grad_year: null }), 'med_student_grad_year_only');
assert.equal(profileCohort({ training_level: 'MD/DO Student', grad_year: null }, 2027), 'other');
assert.equal(profileCohort({ training_level: 'MD/DO Resident', grad_year: null }), 'other');
assert.equal(profileCohort({ training_level: 'MD/DO Fellow', grad_year: null }), 'other');
assert.equal(profileCohort({ training_level: '', grad_year: null, institution: 'Hospital' }), 'other');
assert.equal(profileCohort({ training_level: '', grad_year: 2027 }), 'other');
assert.equal(isEligibleForCampaign({ ...base, profileCohort: 'empty' }, 'profile_completion_1', now), true);
assert.equal(isEligibleForCampaign({ ...base, profileCohort: 'med_student_grad_year_only' }, 'profile_completion_1', now), false);
assert.equal(isEligibleForCampaign({ ...base, profileCohort: 'med_student_grad_year_only' }, 'profile_grad_year_1', now), true);
assert.equal(isEligibleForCampaign({ ...base, profileCohort: 'empty' }, 'profile_grad_year_1', now), false);
assert.equal(isEligibleForCampaign({ ...base, profileCohort: 'empty', receiveEmails: false }, 'profile_completion_1', now), false);
assert.equal(isEligibleForCampaign({ ...base, profileCohort: 'med_student_grad_year_only', receiveEmails: false }, 'profile_grad_year_1', now), false);
assert.equal(isEligibleForCampaign({ ...base, profileCohort: 'empty', optedOutTopics: new Set(['product_updates']) }, 'profile_completion_1', now), false);
assert.equal(isEligibleForCampaign({ ...base, profileCohort: 'med_student_grad_year_only', priorSteps: new Set(['profile_completion_1']) }, 'profile_grad_year_1', now), false);
console.log('marketing segment tests passed');
