import { createApplicationCycleConfig } from "./application-cycle";

// Explicit public reads are required so Next.js can replace these values in client bundles.
export const pathToOrthoApplicationCycle = createApplicationCycleConfig({
  NEXT_PUBLIC_PATH_TO_ORTHO_ERAS_APPLICATION_OPEN_DATE:
    process.env.NEXT_PUBLIC_PATH_TO_ORTHO_ERAS_APPLICATION_OPEN_DATE,
  NEXT_PUBLIC_PATH_TO_ORTHO_ERAS_PROGRAM_REVIEW_DATE:
    process.env.NEXT_PUBLIC_PATH_TO_ORTHO_ERAS_PROGRAM_REVIEW_DATE,
  NEXT_PUBLIC_PATH_TO_ORTHO_NRMP_REGISTRATION_OPEN_DATE:
    process.env.NEXT_PUBLIC_PATH_TO_ORTHO_NRMP_REGISTRATION_OPEN_DATE,
  NEXT_PUBLIC_PATH_TO_ORTHO_NRMP_REGISTRATION_CLOSE_DATE:
    process.env.NEXT_PUBLIC_PATH_TO_ORTHO_NRMP_REGISTRATION_CLOSE_DATE,
  NEXT_PUBLIC_PATH_TO_ORTHO_NRMP_RANKING_OPEN_DATE:
    process.env.NEXT_PUBLIC_PATH_TO_ORTHO_NRMP_RANKING_OPEN_DATE,
  NEXT_PUBLIC_PATH_TO_ORTHO_NRMP_RANKING_CLOSE_DATE:
    process.env.NEXT_PUBLIC_PATH_TO_ORTHO_NRMP_RANKING_CLOSE_DATE,
  NEXT_PUBLIC_PATH_TO_ORTHO_YES_NO_DAY_DATE:
    process.env.NEXT_PUBLIC_PATH_TO_ORTHO_YES_NO_DAY_DATE,
  NEXT_PUBLIC_PATH_TO_ORTHO_MATCH_DAY_DATE:
    process.env.NEXT_PUBLIC_PATH_TO_ORTHO_MATCH_DAY_DATE,
});
