'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, BookOpenCheck, Check, ChevronRight, ClipboardCheck, Download, FilePlus2, Loader2, Search, ShieldCheck, Sparkles } from 'lucide-react';
import { EMPTY_REVIEW_QUESTION, PRISMA_ITEMS, WORKFLOW_STEPS, type Feasibility, type ReviewProject, type ReviewQuestion } from '@/lib/brobot/research/systematic-review';
import { SYSTEMATIC_REVIEW_LESSONS } from '@/lib/brobot/research/systematic-review-education';
import PrismaFlowGenerator from './prisma-flow-generator';

const STORAGE_KEY = 'snaportho:systematic-review:v2';
const card = 'rounded-2xl border border-slate-200 bg-white shadow-sm';
const input = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-600/10';
const emptyProject = (): ReviewProject => ({ question: EMPTY_REVIEW_QUESTION, feasibility: null, completedSteps: [], prismaItems: {}, updatedAt: new Date().toISOString() });
type View = 'feasibility' | 'roadmap' | 'prisma' | 'flow' | 'search' | 'extraction' | 'synthesis';

export default function SystematicReviewWorkspace() {
  const [project, setProject] = useState<ReviewProject>(emptyProject);
  const [view, setView] = useState<View>('flow');
  const [hydrated, setHydrated] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { try { const saved = localStorage.getItem(STORAGE_KEY); if (saved) setProject({ ...emptyProject(), ...JSON.parse(saved) }); } catch {} setHydrated(true); }, []);
  useEffect(() => { if (hydrated) localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...project, updatedAt: new Date().toISOString() })); }, [project, hydrated]);
  const progress = Math.round(project.completedSteps.length / WORKFLOW_STEPS.length * 100);
  const prismaProgress = Math.round(PRISMA_ITEMS.filter(([id]) => project.prismaItems[id]).length / PRISMA_ITEMS.length * 100);
  const nav: Array<[View,string,React.ReactNode]> = [['feasibility','Feasibility',<Sparkles key="a" className="h-4 w-4"/>],['roadmap','Roadmap',<ChevronRight key="b" className="h-4 w-4"/>],['prisma','PRISMA checklist',<ClipboardCheck key="c" className="h-4 w-4"/>],['flow','Flow diagram',<FilePlus2 key="d" className="h-4 w-4"/>],['search','Search strategy',<Search key="e" className="h-4 w-4"/>],['extraction','Extraction + bias',<ShieldCheck key="f" className="h-4 w-4"/>],['synthesis','Synthesis',<BookOpenCheck key="g" className="h-4 w-4"/>]];
  const updateQuestion = (key:keyof ReviewQuestion,value:string) => setProject(p=>({...p,question:{...p.question,[key]:value},feasibility:null}));
  const assess = async () => { setBusy(true); setError(''); try { const response=await fetch('/api/research/systematic-review/feasibility',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:project.question,papers:[]})}); const data=await response.json(); if(!response.ok)throw new Error(data.error); setProject(p=>({...p,feasibility:data,completedSteps:Array.from(new Set([...p.completedSteps,'question']))})); } catch(caught){setError(caught instanceof Error?caught.message:'Assessment failed.')} finally{setBusy(false)} };
  const exportProject = () => { const url=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'})); const a=document.createElement('a');a.href=url;a.download='systematic-review-plan.json';a.click();URL.revokeObjectURL(url); };
  return <main className="min-h-screen bg-[#f5f7f6] text-slate-900"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 px-4 py-3 backdrop-blur"><div className="mx-auto flex max-w-[1600px] items-center justify-between gap-3"><div className="flex items-center gap-3"><Link href="/research/playbook" aria-label="Back to playbook" className="rounded-lg p-2 hover:bg-slate-100"><ArrowLeft className="h-5 w-5"/></Link><div className="rounded-xl bg-teal-700 p-2 text-white"><BookOpenCheck className="h-5 w-5"/></div><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-teal-700">Research 101 · Playbook 03</p><h1 className="text-base font-semibold sm:text-lg">Systematic Review Playbook</h1></div></div><div className="flex items-center gap-2"><p className="hidden text-xs font-semibold sm:block">{progress}% project complete</p><button onClick={exportProject} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold"><Download className="h-4 w-4"/>Plan</button></div></div></header>
    <div className="mx-auto grid max-w-[1600px] gap-4 p-4 lg:grid-cols-[230px_minmax(0,1fr)_290px]"><aside className="space-y-4"><section className={`${card} p-2`}>{nav.map(([id,label,icon])=><button key={id} onClick={()=>setView(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold ${view===id?'bg-teal-700 text-white':'text-slate-600 hover:bg-slate-50'}`}>{icon}<span className="flex-1">{label}</span>{id==='prisma'&&<span className="text-[10px]">{prismaProgress}%</span>}</button>)}</section><section className={`${card} p-4`}><p className="text-xs font-bold uppercase tracking-wider text-teal-700">Core principle</p><p className="mt-2 text-sm font-semibold leading-6">Teach the systematic review process—not become another citation manager.</p></section></aside>
      <section className="min-w-0">{error&&<div role="alert" className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</div>}{view==='flow'&&<PrismaFlowGenerator/>}{view==='feasibility'&&<FeasibilityView project={project} update={updateQuestion} assess={assess} busy={busy}/>} {view==='roadmap'&&<Roadmap project={project} setProject={setProject}/>} {view==='prisma'&&<Prisma project={project} setProject={setProject}/>} {view==='search'&&<SearchBuilder/>}{view==='extraction'&&<Extraction/>}{view==='synthesis'&&<Synthesis/>}</section>
      <aside><Mentor view={view} project={project}/></aside>
    </div></main>;
}

function FeasibilityView({project,update,assess,busy}:{project:ReviewProject;update:(k:keyof ReviewQuestion,v:string)=>void;assess:()=>void;busy:boolean}) { const q=project.question; const fields:Array<[keyof ReviewQuestion,string]>=[['title','Working title'],['population','Population'],['intervention','Intervention / exposure'],['comparator','Comparator'],['outcome','Outcome'],['design','Eligible study designs'],['rationale','Why this review now?'],['knownReviews','Nearest existing reviews']]; return <div className="space-y-4"><section className={`${card} p-6`}><p className="text-xs font-bold uppercase tracking-wider text-teal-700">Gate 01</p><h2 className="mt-2 text-2xl font-semibold">Should you even do this review?</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{fields.map(([key,label])=><label key={key} className={`text-xs font-semibold text-slate-600 ${key==='rationale'||key==='knownReviews'?'md:col-span-2':''}`}>{label}<textarea rows={2} value={String(q[key])} onChange={e=>update(key,e.target.value)} className={`${input} mt-1 font-normal`}/></label>)}</div><button disabled={busy||(!q.title&&!q.population)} onClick={assess} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Sparkles className="h-4 w-4"/>}Challenge this topic</button></section>{project.feasibility&&<Scorecard data={project.feasibility}/>}</div> }
function Scorecard({data}:{data:Feasibility}) { return <section className={`${card} overflow-hidden`}><div className="bg-slate-900 p-6 text-white"><p className="text-xs font-bold uppercase tracking-wider text-teal-300">Recommendation</p><h3 className="mt-2 text-2xl font-semibold">{data.recommendation}</h3><p className="mt-2 text-sm text-slate-300">{data.summary}</p></div><div className="grid gap-3 p-6 sm:grid-cols-5">{Object.entries(data.scores).map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-3"><span className="text-[11px] capitalize text-slate-500">{label.replace(/([A-Z])/g,' $1')}</span><b className="mt-1 block text-xl">{value}</b></div>)}</div><ul className="space-y-2 px-6 pb-6 text-sm text-slate-600">{data.reasoning.map(x=><li key={x}>• {x}</li>)}</ul></section> }
function Roadmap({project,setProject}:{project:ReviewProject;setProject:React.Dispatch<React.SetStateAction<ReviewProject>>}) { return <section className={`${card} p-6`}><h2 className="text-2xl font-semibold">From question to submission</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{WORKFLOW_STEPS.map(([id,label],i)=>{const done=project.completedSteps.includes(id);return <button key={id} onClick={()=>setProject(p=>({...p,completedSteps:done?p.completedSteps.filter(x=>x!==id):[...p.completedSteps,id]}))} className={`flex items-center gap-3 rounded-xl border p-3 text-left ${done?'border-teal-200 bg-teal-50':'border-slate-200'}`}><span className={`flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold ${done?'bg-teal-700 text-white':'bg-slate-100'}`}>{done?<Check className="h-4 w-4"/>:i+1}</span><b className="text-sm">{label}</b></button>})}</div></section> }
function Prisma({project,setProject}:{project:ReviewProject;setProject:React.Dispatch<React.SetStateAction<ReviewProject>>}) { return <section className={`${card} p-6`}><h2 className="text-2xl font-semibold">PRISMA is not optional.</h2><p className="mt-2 text-sm text-slate-600">Track compliance while decisions are made—not at manuscript submission.</p><div className="mt-5 space-y-2">{PRISMA_ITEMS.map(([id,label])=><label key={id} className="flex gap-3 rounded-xl border p-3"><input type="checkbox" checked={Boolean(project.prismaItems[id])} onChange={()=>setProject(p=>({...p,prismaItems:{...p.prismaItems,[id]:!p.prismaItems[id]}}))} className="accent-teal-700"/><b className="text-sm">{label}</b></label>)}</div></section> }
function SearchBuilder(){const [concepts,setConcepts]=useState({population:'',intervention:'',outcome:''});const query=Object.values(concepts).filter(Boolean).map(x=>`(${x.split(',').map(y=>`\"${y.trim()}\"`).join(' OR ')})`).join(' AND ');return <section className={`${card} p-6`}><h2 className="text-2xl font-semibold">Build concepts, not one long guess</h2><div className="mt-5 grid gap-3 md:grid-cols-3">{Object.keys(concepts).map(k=><label key={k} className="text-xs font-semibold capitalize">{k}<textarea rows={4} value={concepts[k as keyof typeof concepts]} onChange={e=>setConcepts({...concepts,[k]:e.target.value})} className={`${input} mt-1`}/></label>)}</div><div className="mt-5 rounded-xl bg-slate-900 p-4 font-mono text-xs text-slate-200">{query||'Boolean preview'}</div></section>}
function Extraction(){return <section className={`${card} p-6`}><h2 className="text-2xl font-semibold">Structured extraction and risk of bias</h2><p className="mt-3 text-sm leading-6 text-slate-600">Use your chosen review platform or reference manager to manage studies. Prespecify and pilot fields for design, population, sample size, interventions, outcomes, time points, funding, conflicts, limitations, and findings.</p><div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><b>Risk of bias is not a generic score.</b> Choose the tool by study design and support each domain judgment with evidence.</div></section>}
function Synthesis(){return <section className={`${card} p-6`}><h2 className="text-2xl font-semibold">What does the entire body of evidence tell us?</h2><p className="mt-3 text-sm leading-6 text-slate-600">Map consensus, conflicts, clinical and methodological heterogeneity, certainty, gaps, and clinical implications. A narrative synthesis can be the rigorous choice when pooling would mislead.</p></section>}
function Mentor({view,project}:{view:View;project:ReviewProject}){if(view==='flow')return <section className={`${card} sticky top-24 p-5`}><p className="text-xs font-bold uppercase tracking-wider text-teal-700">BroBot mentor</p><h3 className="mt-4 font-semibold">Why reviewers care</h3><p className="mt-2 text-sm leading-6 text-slate-600">The PRISMA diagram demonstrates transparency and lets readers understand how your evidence base was assembled.</p><h3 className="mt-5 text-sm font-semibold">Common mistake</h3><p className="mt-1 text-xs leading-5 text-slate-500">Numbers that do not reconcile between screening stages.</p><div className="mt-5 rounded-xl bg-teal-50 p-3 text-xs leading-5 text-teal-900"><b>BroBot tip:</b> Always save search results before deduplication so you can reproduce your counts later.</div><div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-700"><b>Journal tip:</b> Many journals expect the PRISMA 2020 flow diagram format.</div></section>;const key=view==='feasibility'?'question':view==='roadmap'||view==='prisma'?'protocol':view==='search'?'strategy':view==='extraction'?'extraction':'synthesis';const lesson=SYSTEMATIC_REVIEW_LESSONS[key];return <section className={`${card} sticky top-24 p-5`}><p className="text-xs font-bold uppercase tracking-wider text-teal-700">BroBot mentor</p><h3 className="mt-3 font-semibold">Why this matters</h3><p className="mt-2 text-sm leading-6 text-slate-600">{lesson.why}</p><h3 className="mt-4 text-sm font-semibold">Common mistake</h3><p className="mt-1 text-xs leading-5 text-slate-500">{lesson.mistake}</p><div className="mt-4 rounded-xl bg-teal-50 p-3 text-xs leading-5 text-teal-900"><b>Tip:</b> {lesson.improve}</div>{!project.feasibility&&<p className="mt-4 text-xs text-amber-700">Feasibility has not been challenged yet.</p>}</section>}
