/**
 * Prepare topic content slices for registered KG topics.
 * Mirrors static Prepare curriculum fields — internal draft source only.
 */

import { loadAdultReconstructionPrepareSlice } from "./adult-reconstruction-prepare-slices.ts";

export type PrepareTopicSlice = {
  topicId: string;
  title: string;
  trackId: string;
  subspecialty: string;
  tags: string[];
  learningObjectives: string[];
  fast: {
    mustKnow: string[];
    anatomyFocus: string[];
    oneLiner: string;
    pimpQuestions: string[];
    orSurvivalTips: string[];
    caseSteps: string[];
  };
  deep: {
    anatomy: string[];
    classification: string[];
    imaging: string[];
    decisionMaking: string[];
    treatmentOptions: string[];
    boardPearls: string[];
    complications: string[];
  };
  sourcePath: string;
};

/** Registered topic slices — extend when new topics register in topic-registry. */
const PREPARE_SLICES: Record<string, PrepareTopicSlice> = {
  "ankle-fracture": {
    topicId: "ankle-fracture",
    title: "Ankle Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["ankle", "mortise", "syndesmosis", "trauma"],
    learningObjectives: [
      "Use exam and radiographs to identify stable versus unstable ankle fractures.",
      "Explain the importance of the mortise and syndesmotic injury.",
      "Outline ED immobilization and operative indications.",
    ],
    fast: {
      mustKnow: ["Mortise congruity, skin status, NV exam, syndesmosis language"],
      anatomyFocus: ["Malleoli", "Deltoid ligament", "Syndesmosis"],
      oneLiner:
        "Ankle fracture management hinges on whether the mortise is stable and whether soft tissues are safe.",
      pimpQuestions: ["What makes the fracture unstable?", "How do stress views help?"],
      orSurvivalTips: [
        "Say whether this is isolated fibula or bimalleolar equivalent",
        "Mention posterior malleolus if present",
      ],
      caseSteps: [
        "Inspect skin",
        "Describe fracture pattern",
        "Comment on mortise",
        "State splint and weight-bearing plan",
      ],
    },
    deep: {
      anatomy: ["Ankle ring concept", "Syndesmotic stabilizers", "Posterior malleolus role"],
      classification: ["Weber", "Supination-external rotation patterns"],
      imaging: ["AP/lateral/mortise views", "Stress views", "CT for posterior malleolus planning"],
      decisionMaking: ["Stable isolated fractures versus unstable patterns requiring fixation"],
      treatmentOptions: [
        "Boot/cast",
        "Reduction and splint",
        "ORIF with syndesmotic fixation when indicated",
      ],
      boardPearls: ["A deltoid injury can make an isolated fibula fracture unstable"],
      complications: ["Wound issues", "Malreduction of syndesmosis", "Post-traumatic arthritis"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts",
  },
  "compartment-syndrome": {
    topicId: "compartment-syndrome",
    title: "Compartment Syndrome",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["emergency", "fasciotomy", "ischemia", "pain out of proportion"],
    learningObjectives: [
      "Recognize the clinical diagnosis of compartment syndrome.",
      "Explain why delayed treatment leads to irreversible damage.",
      "Describe emergent management including fasciotomy principles.",
    ],
    fast: {
      mustKnow: ["Pain out of proportion, pain with passive stretch, serial exam urgency"],
      anatomyFocus: ["Leg compartments", "Forearm compartments", "Muscle and nerve ischemia timeline"],
      oneLiner:
        "Compartment syndrome is a clinical emergency where worsening pain and tense compartments trump waiting for tests.",
      pimpQuestions: ["Why are pulses unreliable?", "When do pressure measurements help?"],
      orSurvivalTips: [
        "Never reassure solely from present pulses",
        "Use time-sensitive limb emergency language",
      ],
      caseSteps: [
        "State concern immediately",
        "Repeat focused exam",
        "Loosen dressings",
        "Escalate for fasciotomy",
      ],
    },
    deep: {
      anatomy: ["Compartments at risk", "Perfusion pressure concept", "Nerves commonly affected"],
      classification: ["Acute traumatic versus exertional"],
      imaging: ["No imaging should delay treatment", "Pressure checks as adjuncts only"],
      decisionMaking: ["High suspicion and evolving exam findings favor fasciotomy"],
      treatmentOptions: ["Emergent fasciotomy", "Return trips for debridement and closure"],
      boardPearls: ["Pulselessness is late; pain with passive stretch is earlier and more useful"],
      complications: ["Muscle necrosis", "Contracture", "Rhabdomyolysis", "Amputation"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts",
  },
  "distal-radius-fracture": {
    topicId: "distal-radius-fracture",
    title: "Distal Radius Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["fracture", "wrist", "reduction", "casting"],
    learningObjectives: [
      "Recognize common distal radius fracture patterns and mechanism.",
      "Describe initial reduction, splinting, and neurovascular checks.",
      "Identify red flags that push management toward fixation.",
    ],
    fast: {
      mustKnow: ["Mechanism, alignment, median nerve exam, immobilization choice"],
      anatomyFocus: ["Distal radius articular surface", "DRUJ relationship", "Median nerve in carpal tunnel"],
      oneLiner:
        "A distal radius fracture is a high-frequency trauma problem where alignment and median nerve status drive urgency.",
      pimpQuestions: ["What radiographic parameters matter?", "When is dorsal comminution important?"],
      orSurvivalTips: [
        "Know acceptable radial height/inclination language",
        "Mention finger ROM after splinting",
      ],
      caseSteps: [
        "Describe mechanism",
        "Check NV exam",
        "Review AP/lateral films",
        "State splint and follow-up plan",
      ],
    },
    deep: {
      anatomy: ["Distal radius columns", "Volar cortex as reduction reference", "DRUJ stabilizers"],
      classification: ["Extra-articular vs intra-articular", "Dorsally displaced vs volarly displaced"],
      imaging: ["Standard wrist radiographs", "CT for complex articular injury"],
      decisionMaking: ["Assess displacement, instability, articular step-off, patient demand"],
      treatmentOptions: ["Splint/cast", "Closed reduction", "Percutaneous fixation", "Volar plating"],
      boardPearls: ["Malalignment tolerance is lower in active patients and articular injuries"],
      complications: ["Loss of reduction", "Median neuropathy", "CRPS", "Tendon irritation"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts",
  },
  "tibial-shaft-fracture": {
    topicId: "tibial-shaft-fracture",
    title: "Tibial Shaft Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["leg fracture", "intramedullary nail", "compartment syndrome"],
    learningObjectives: [
      "Describe initial stabilization and soft-tissue priorities in tibial shaft fractures.",
      "Recognize the association with compartment syndrome.",
      "Compare nonoperative treatment with IM nailing indications.",
    ],
    fast: {
      mustKnow: ["Soft tissue exam, compartments, alignment, weight-bearing plan"],
      anatomyFocus: ["Tibial shaft blood supply", "Anterior compartment", "Proximal entry point landmarks"],
      oneLiner: "Tibial shaft fractures are soft-tissue injuries first and bony injuries second.",
      pimpQuestions: ["What are compartment syndrome warning signs?", "Why do open tibias need urgency?"],
      orSurvivalTips: [
        "Always mention soft tissues and compartment checks",
        "Know common IM nail starting point language",
      ],
      caseSteps: [
        "Describe wound status",
        "Check compartments",
        "Review alignment",
        "State immobilization and operative plan",
      ],
    },
    deep: {
      anatomy: ["Subcutaneous tibial crest", "Compartment layout", "Proximal/distal metaphyseal challenges"],
      classification: ["Open versus closed", "Simple versus segmental/comminuted"],
      imaging: ["Full-length tibia/fibula radiographs", "Adjacent joint views"],
      decisionMaking: ["Closed stable injuries versus deformity/open/high-energy patterns"],
      treatmentOptions: [
        "Cast or brace in select cases",
        "External fixation bridge",
        "IM nail",
        "Plate fixation in selected patterns",
      ],
      boardPearls: ["Serial exams matter because compartment syndrome is a clinical diagnosis"],
      complications: ["Compartment syndrome", "Malunion", "Infection", "Nonunion"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts",
  },
  "femoral-neck-fracture": {
    topicId: "femoral-neck-fracture",
    title: "Femoral Neck Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["hip", "femoral neck", "intracapsular", "AVN", "arthroplasty"],
    learningObjectives: [
      "Explain intracapsular anatomy and blood supply risk after femoral neck fracture.",
      "Differentiate fixation versus arthroplasty pathways by age, displacement, and function.",
      "Communicate AVN and nonunion risks with appropriate urgency.",
    ],
    fast: {
      mustKnow: ["Intracapsular location", "Displacement", "Head viability language", "Medical optimization"],
      anatomyFocus: ["Femoral neck", "Femoral head blood supply", "MFCA / retinacular vessels", "Calcar"],
      oneLiner: "Femoral neck fracture is an intracapsular injury where displacement and blood supply determine fixation versus arthroplasty.",
      pimpQuestions: ["Why are displaced femoral neck fractures different?", "What changes management in younger patients?"],
      orSurvivalTips: ["Use intracapsular language", "Mention DVT prophylaxis and AVN surveillance when relevant"],
      caseSteps: ["Confirm intracapsular location", "State displacement", "Describe optimization need", "Outline fixation vs arthroplasty pathway"],
    },
    deep: {
      anatomy: ["Retinacular blood supply", "MFCA vulnerability", "Calcar buttress"],
      classification: ["Garden displacement concepts"],
      imaging: ["Pelvis and hip radiographs", "MRI for occult fracture"],
      decisionMaking: ["Age, baseline function, displacement, head viability, medical risk"],
      treatmentOptions: ["Cannulated screws", "Femoral neck ORIF", "Hemiarthroplasty", "Total hip arthroplasty"],
      boardPearls: ["Displaced femoral neck fractures in older adults are often arthroplasty problems"],
      complications: ["Avascular necrosis", "Nonunion", "Delirium"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts#hip-fracture-neck-split",
  },
  "intertrochanteric-fracture": {
    topicId: "intertrochanteric-fracture",
    title: "Intertrochanteric Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["hip", "intertrochanteric", "extracapsular", "cephalomedullary nail", "DHS"],
    learningObjectives: [
      "Recognize stable versus unstable intertrochanteric fracture patterns.",
      "Select sliding hip screw versus cephalomedullary nail fixation concepts.",
      "Identify implant failure and varus collapse risks.",
    ],
    fast: {
      mustKnow: ["Extracapsular location", "Fracture line orientation", "Medial comminution", "Implant category"],
      anatomyFocus: ["Intertrochanteric region", "Greater trochanter", "Calcar / medial buttress"],
      oneLiner: "Intertrochanteric fractures are extracapsular injuries where stability pattern drives implant selection.",
      pimpQuestions: ["What makes an intertrochanteric fracture unstable?", "When is a cephalomedullary nail preferred?"],
      orSurvivalTips: ["Comment on reverse obliquity", "Use tip-apex distance language when discussing lag screw"],
      caseSteps: ["Describe fracture line", "Assess medial buttress", "State implant plan", "Outline mobilization pathway"],
    },
    deep: {
      anatomy: ["Intertrochanteric bone quality", "Abductor insertion on greater trochanter"],
      classification: ["Stable versus unstable patterns", "Reverse obliquity"],
      imaging: ["AP and lateral hip radiographs"],
      decisionMaking: ["Pattern stability, bone quality, patient mobility goals"],
      treatmentOptions: ["Sliding hip screw", "Cephalomedullary nail"],
      boardPearls: ["Reverse obliquity patterns are unstable and often need intramedullary fixation"],
      complications: ["Implant cutout", "Varus collapse", "Nonunion"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts#hip-fracture-it-split",
  },
  "subtrochanteric-fracture": {
    topicId: "subtrochanteric-fracture",
    title: "Subtrochanteric Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["hip", "subtrochanteric", "proximal femur", "cephalomedullary nail"],
    learningObjectives: [
      "Localize subtrochanteric fractures relative to the lesser trochanter.",
      "Explain high mechanical demands and varus shortening forces.",
      "Recognize atypical fracture morphology and sciatic nerve safety in fixation.",
    ],
    fast: {
      mustKnow: ["Fracture level", "Comminution", "Mechanical demands", "Implant plan"],
      anatomyFocus: ["Lesser trochanter landmark", "Proximal femoral diaphysis", "Sciatic nerve proximity"],
      oneLiner: "Subtrochanteric fractures are high-stress proximal femoral shaft injuries where reduction and implant choice determine alignment survival.",
      pimpQuestions: ["Why is varus a major concern?", "When is an atypical pattern suspected?"],
      orSurvivalTips: ["Describe reduction tools and nail starting point language", "Mention sciatic nerve protection with posterior exposure"],
      caseSteps: ["Localize fracture relative to lesser trochanter", "Assess comminution", "State fixation plan", "Outline weight-bearing restrictions"],
    },
    deep: {
      anatomy: ["Lesser trochanter", "Posterior proximal femur", "Abductor lever arm"],
      classification: ["Seinsheimer concepts"],
      imaging: ["Full femur views when needed", "Assess for atypical morphology"],
      decisionMaking: ["Pattern stability, bone quality, metabolic bone disease concern"],
      treatmentOptions: ["Cephalomedullary nail", "Plate osteosynthesis in selected patterns"],
      boardPearls: ["Cephalomedullary nailing is the common operative answer for most subtrochanteric fractures"],
      complications: ["Varus malunion", "Nonunion", "Implant failure"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts#hip-fracture-st-split",
  },
  "clavicle-fracture": {
    topicId: "clavicle-fracture",
    title: "Clavicle Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["clavicle", "shoulder girdle", "midshaft fracture"],
    learningObjectives: [
      "Recognize common midshaft clavicle fracture patterns.",
      "Identify medial clavicle and sternoclavicular red flags.",
      "Compare nonoperative sling versus operative fixation indications.",
    ],
    fast: {
      mustKnow: ["Fracture location, shortening, skin tenting, neurovascular exam"],
      anatomyFocus: ["Clavicle", "AC joint", "Sternoclavicular joint"],
      oneLiner: "Midshaft clavicle fractures are common shoulder girdle injuries where displacement and patient goals drive operative versus sling treatment.",
      pimpQuestions: ["When is operative fixation considered?", "What makes medial clavicle injuries dangerous?"],
      orSurvivalTips: ["Comment on shortening and comminution", "Screen for SC joint posterior displacement language"],
      caseSteps: ["Describe fracture site", "Check skin and NV exam", "State sling versus ORIF plan", "Set follow-up expectations"],
    },
    deep: {
      anatomy: ["Clavicular blood supply", "SC joint stability", "AC joint relationship"],
      classification: ["Midshaft versus lateral versus medial patterns"],
      imaging: ["AP clavicle radiographs", "Serendipity view for medial injuries when needed"],
      decisionMaking: ["Displacement, shortening, comminution, activity demands"],
      treatmentOptions: ["Sling immobilization", "Open reduction internal fixation"],
      boardPearls: ["Posterior sternoclavicular displacement is not a benign clavicle injury"],
      complications: ["Malunion", "Nonunion", "Neurovascular compromise with medial injuries"],
    },
    sourcePath: "trauma-clavicle-fractures-midshaft curriculum bridge",
  },
  "proximal-humerus-fracture": {
    topicId: "proximal-humerus-fracture",
    title: "Proximal Humerus Fracture",
    trackId: "shoulder-elbow",
    subspecialty: "Shoulder & Elbow",
    tags: ["shoulder fracture", "elderly fracture", "axillary nerve"],
    learningObjectives: [
      "Recognize common proximal humerus fracture patterns and demographic.",
      "Understand why many are treated nonoperatively.",
      "Describe complications and rehab priorities.",
    ],
    fast: {
      mustKnow: ["Often low-energy elderly injury, many nonoperative, check axillary nerve"],
      anatomyFocus: ["Tuberosities", "Humeral head blood supply", "Axillary nerve"],
      oneLiner: "Most proximal humerus fractures are elderly fragility injuries where acceptable alignment often beats risky surgery.",
      pimpQuestions: ["Why are many treated without surgery?", "What nerve do you check?"],
      orSurvivalTips: ["Mention tuberosity displacement and head split if present", "Do not forget elbow motion during rehab"],
      caseSteps: ["Describe fracture parts conceptually", "Check neurovascular status", "State sling and rehab plan"],
    },
    deep: {
      anatomy: ["Tuberosity function and cuff attachments", "Humeral head perfusion"],
      classification: ["Displacement-based part concept at a high level"],
      imaging: ["AP, scapular Y, axillary views if tolerated"],
      decisionMaking: ["Displacement, tuberosity involvement, age, bone quality, function"],
      treatmentOptions: ["Sling and early rehab", "ORIF", "Arthroplasty in select complex patterns"],
      boardPearls: ["Axillary nerve exam should be part of every shoulder trauma presentation"],
      complications: ["Stiffness", "Avascular necrosis", "Malunion", "Tuberosity failure"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts",
  },
  "humeral-shaft-fracture": {
    topicId: "humeral-shaft-fracture",
    title: "Humeral Shaft Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["humerus", "radial nerve", "IM nail"],
    learningObjectives: [
      "Document radial nerve function before and after reduction.",
      "Recognize Holstein-Lewis fracture association.",
      "Compare nonoperative versus operative stabilization pathways.",
    ],
    fast: {
      mustKnow: ["Alignment, radial nerve exam, brachial pulse, splint plan"],
      anatomyFocus: ["Spiral groove radial nerve", "Humeral diaphysis", "Brachial artery"],
      oneLiner: "Humeral shaft fractures require serial radial nerve exams and clear alignment goals.",
      pimpQuestions: ["What fracture pattern risks radial nerve injury?", "When is IM nailing preferred?"],
      orSurvivalTips: ["Repeat wrist extension after reduction", "Know Holstein-Lewis association"],
      caseSteps: ["Describe deformity", "Document radial nerve baseline", "State splint and operative plan"],
    },
    deep: {
      anatomy: ["Radial nerve in spiral groove", "Brachial artery course"],
      classification: ["Open versus closed", "Spiral distal-third patterns"],
      imaging: ["AP and lateral humerus radiographs"],
      decisionMaking: ["Alignment, nerve status, open injury, patient factors"],
      treatmentOptions: ["Functional bracing", "IM nail", "Plate osteosynthesis"],
      boardPearls: ["Holstein-Lewis fractures are classic radial nerve board associations"],
      complications: ["Radial nerve palsy", "Nonunion", "Malunion"],
    },
    sourcePath: "trauma-humeral-shaft-fractures curriculum bridge",
  },
  "distal-humerus-fracture": {
    topicId: "distal-humerus-fracture",
    title: "Distal Humerus Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["elbow", "intra-articular", "column fixation"],
    learningObjectives: [
      "Use column and articular concepts for distal humerus fractures.",
      "Identify ulnar and median nerve risks during fixation.",
      "Discuss ORIF versus arthroplasty in elderly patients.",
    ],
    fast: {
      mustKnow: ["Articular involvement, column comminution, nerve exam, splint position"],
      anatomyFocus: ["Medial and lateral columns", "Capitellum and trochlea", "Ulnar nerve"],
      oneLiner: "Distal humerus fractures are elbow injuries where articular restoration and nerve protection drive operative planning.",
      pimpQuestions: ["Why do columns matter?", "When is total elbow arthroplasty considered?"],
      orSurvivalTips: ["Use dual-column fixation language", "Mention ulnar nerve transposition/protection"],
      caseSteps: ["Describe articular step-off", "Check ulnar nerve", "State ORIF versus arthroplasty pathway"],
    },
    deep: {
      anatomy: ["Medial and lateral columns", "Olecranon fossa", "Trochlea and capitellum"],
      classification: ["Extra-articular versus intra-articular patterns"],
      imaging: ["AP and lateral elbow radiographs", "CT for complex articular planning"],
      decisionMaking: ["Articular involvement, bone quality, patient demand"],
      treatmentOptions: ["ORIF", "Total elbow arthroplasty in selected elderly patients"],
      boardPearls: ["Ulnar nerve protection is essential in posterior exposure"],
      complications: ["Elbow stiffness", "Nonunion", "Ulnar neuropathy"],
    },
    sourcePath: "trauma-distal-humerus-fractures curriculum bridge",
  },
  "supracondylar-humerus-fracture": {
    topicId: "supracondylar-humerus-fracture",
    title: "Supracondylar Humerus Fracture",
    trackId: "pediatrics",
    subspecialty: "Pediatrics",
    tags: ["peds trauma", "elbow", "vascular exam", "pins"],
    learningObjectives: [
      "Recognize the classic pediatric elbow injury pattern and its urgency.",
      "Perform and present a focused neurovascular exam.",
      "Explain why many displaced fractures need urgent pinning.",
    ],
    fast: {
      mustKnow: ["Child elbow injury, posterior fat pad/anterior humeral line, vascular exam"],
      anatomyFocus: ["Brachial artery", "Median/AIN and radial nerve", "Distal humerus alignment"],
      oneLiner: "Supracondylar humerus fractures are pediatric elbow injuries where alignment and neurovascular status determine urgency.",
      pimpQuestions: ["What nerve is most commonly injured?", "Why is the vascular exam so important?"],
      orSurvivalTips: ["Always mention AIN exam", "Do not forget compartment syndrome risk after reduction"],
      caseSteps: ["Describe swelling", "Document pulse and nerve exam", "Interpret lateral x-ray alignment", "State immobilization/OR urgency"],
    },
    deep: {
      anatomy: ["Distal humerus anatomy in children", "Cubital fossa neurovascular structures"],
      classification: ["Displacement-based supracondylar pattern framework"],
      imaging: ["Anterior humeral line", "Baumann angle at a concept level"],
      decisionMaking: ["Nondisplaced casting versus urgent pinning for displaced injuries"],
      treatmentOptions: ["Long-arm cast", "Closed reduction and percutaneous pinning"],
      boardPearls: ["A pulseless, poorly perfused hand after this injury is an emergency"],
      complications: ["Nerve palsy", "Vascular compromise", "Cubitus varus", "Compartment syndrome"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts",
  },
  "pelvic-ring-injury": {
    topicId: "pelvic-ring-injury",
    title: "Pelvic Ring Injury",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["pelvis", "pelvic ring", "hemorrhage", "binder", "resuscitation"],
    learningObjectives: [
      "Recognize unstable pelvic ring patterns and hemorrhage risk.",
      "Apply Young-Burgess mechanism language to injury severity.",
      "Prioritize binder, resuscitation, and stabilization before definitive fixation.",
    ],
    fast: {
      mustKnow: ["Mechanism, ring stability, binder, hemorrhage language, resuscitation priority"],
      anatomyFocus: ["Pelvis", "Sacroiliac joint", "Pubic symphysis", "Sacrum"],
      oneLiner: "Pelvic ring injury is a resuscitation problem first — instability and hemorrhage drive urgency before definitive fixation.",
      pimpQuestions: ["What makes a pelvic ring unstable?", "When is a pelvic binder indicated?"],
      orSurvivalTips: ["Use Young-Burgess APC/LC/VS language", "Mention binder and ex-fix as temporizing tools"],
      caseSteps: ["State mechanism", "Assess ring stability", "Apply binder if indicated", "Escalate hemorrhage control"],
    },
    deep: {
      anatomy: ["Anterior and posterior ring", "Venous plexus", "Sacroiliac stability"],
      classification: ["Young-Burgess APC, LC, VS patterns"],
      imaging: ["AP pelvis", "Inlet/outlet views", "CT for posterior ring detail"],
      decisionMaking: ["Hemodynamic status, ring instability, associated injuries"],
      treatmentOptions: ["Pelvic binder", "Pelvic external fixation", "Definitive ORIF when stable"],
      boardPearls: ["Unstable pelvic ring with hypotension is a hemorrhage emergency"],
      complications: ["Pelvic hemorrhage", "Retroperitoneal bleeding", "Late instability"],
    },
    sourcePath: "trauma-pelvic-ring-fractures curriculum bridge",
  },
  "acetabular-fracture": {
    topicId: "acetabular-fracture",
    title: "Acetabular Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["acetabulum", "hip", "column fracture", "judet-letournel"],
    learningObjectives: [
      "Localize acetabular fracture columns and articular involvement.",
      "Explain hip stability and congruity goals after injury.",
      "Outline operative indications and post-traumatic arthritis risk.",
    ],
    fast: {
      mustKnow: ["Column involvement, hip stability, articular step-off, operative candidacy"],
      anatomyFocus: ["Acetabulum", "Anterior column", "Posterior column", "Femoral head"],
      oneLiner: "Acetabular fractures are articular hip injuries where column pattern and congruity determine operative planning.",
      pimpQuestions: ["What columns are involved?", "When is operative fixation indicated?"],
      orSurvivalTips: ["Use column and wall language", "Mention CT for articular planning"],
      caseSteps: ["Describe fracture pattern", "Assess hip stability", "Review CT articular detail", "State ORIF pathway"],
    },
    deep: {
      anatomy: ["Anterior and posterior columns", "Acetabular walls", "Quadrilateral plate"],
      classification: ["Judet-Letournel column/wall patterns"],
      imaging: ["Judet views", "CT with articular mapping"],
      decisionMaking: ["Displacement, instability, articular involvement, patient factors"],
      treatmentOptions: ["Nonoperative in select patterns", "Acetabular ORIF"],
      boardPearls: ["Articular incongruity predicts post-traumatic arthritis"],
      complications: ["Post-traumatic arthritis", "Sciatic nerve injury", "Heterotopic ossification"],
    },
    sourcePath: "trauma-acetabular-fractures curriculum bridge",
  },
  "femoral-shaft-fracture": {
    topicId: "femoral-shaft-fracture",
    title: "Femoral Shaft Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["femur", "intramedullary nail", "polytrauma", "fat embolism"],
    learningObjectives: [
      "Stabilize femoral shaft fractures in polytrauma patients.",
      "Compare IM nailing with bridge external fixation concepts.",
      "Recognize fat embolism and compartment syndrome associations.",
    ],
    fast: {
      mustKnow: ["Alignment, soft tissues, polytrauma context, IM nail as default operative answer"],
      anatomyFocus: ["Femoral diaphysis", "Piriformis/trochanteric entry landmarks", "Distal locking"],
      oneLiner: "Femoral shaft fracture management balances early stabilization with resuscitation and soft-tissue safety.",
      pimpQuestions: ["When is early IM nailing preferred?", "What are bridge fixation indications?"],
      orSurvivalTips: ["Mention antegrade nail language", "Address polytrauma timing"],
      caseSteps: ["Describe fracture pattern", "Assess soft tissues", "State splint versus nail plan", "Set weight-bearing restrictions"],
    },
    deep: {
      anatomy: ["Femoral shaft blood supply", "Entry site options", "Distal femur transition zone"],
      classification: ["Open versus closed", "Winquist-Hansen comminution concepts"],
      imaging: ["AP/lateral femur", "Hip and knee joint views"],
      decisionMaking: ["Polytrauma status, open injury, alignment, patient physiology"],
      treatmentOptions: ["Skeletal traction", "External fixation bridge", "Antegrade/retrograde IM nail"],
      boardPearls: ["Early femoral stabilization can help polytrauma resuscitation"],
      complications: ["Fat embolism", "Malunion", "Nonunion", "Compartment syndrome"],
    },
    sourcePath: "trauma-femoral-shaft-fractures curriculum bridge",
  },
  "distal-femur-fracture": {
    topicId: "distal-femur-fracture",
    title: "Distal Femur Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["distal femur", "supracondylar femur", "articular", "ORIF"],
    learningObjectives: [
      "Differentiate extra-articular from intra-articular distal femur patterns.",
      "Explain fixation options for comminuted metaphyseal fractures.",
      "Identify malunion and stiffness risks after fixation.",
    ],
    fast: {
      mustKnow: ["Articular involvement, comminution, alignment, implant category"],
      anatomyFocus: ["Distal femur", "Lateral condyle", "Medial condyle", "Patellofemoral groove"],
      oneLiner: "Distal femur fractures combine metaphyseal comminution with articular restoration demands.",
      pimpQuestions: ["When is a locking plate preferred?", "What makes the fracture intra-articular?"],
      orSurvivalTips: ["Comment on articular step-off", "Mention lateral plating language"],
      caseSteps: ["Describe condylar involvement", "Assess alignment", "State ORIF plan", "Outline rehab restrictions"],
    },
    deep: {
      anatomy: ["Distal femoral metaphysis", "Condylar columns", "Patellar articulation"],
      classification: ["Extra-articular versus intra-articular", "AO distal femur patterns"],
      imaging: ["AP/lateral knee radiographs", "CT for articular planning"],
      decisionMaking: ["Articular displacement, bone quality, patient demand"],
      treatmentOptions: ["Locked plating", "Retrograde nail in selected patterns"],
      boardPearls: ["Articular step-off in distal femur fractures often needs operative reduction"],
      complications: ["Malunion", "Knee stiffness", "Hardware irritation"],
    },
    sourcePath: "trauma-distal-femur-fractures curriculum bridge",
  },
  "patella-fracture": {
    topicId: "patella-fracture",
    title: "Patella Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["patella", "extensor mechanism", "knee", "ORIF"],
    learningObjectives: [
      "Assess extensor mechanism integrity after patella fracture.",
      "Differentiate nondisplaced from operative fracture patterns.",
      "Recognize patella baja and hardware complications.",
    ],
    fast: {
      mustKnow: ["Extensor mechanism exam, fracture displacement, articular step-off"],
      anatomyFocus: ["Patella", "Quadriceps tendon", "Patellar tendon", "Extensor mechanism"],
      oneLiner: "Patella fracture management centers on whether the extensor mechanism remains functional.",
      pimpQuestions: ["How do you test extensor mechanism?", "When is ORIF indicated?"],
      orSurvivalTips: ["Perform active extension check", "Mention tension band fixation language"],
      caseSteps: ["Test extension", "Describe fracture pattern", "State splint versus ORIF", "Plan early motion"],
    },
    deep: {
      anatomy: ["Patellar articular surface", "Quadriceps-patellar tendon linkage"],
      classification: ["Transverse, comminuted, sleeve patterns"],
      imaging: ["Merchant/sunrise views when needed", "Lateral for displacement"],
      decisionMaking: ["Extensor lag, displacement, articular involvement"],
      treatmentOptions: ["Cylinder cast", "Patella ORIF with tension band"],
      boardPearls: ["Loss of active extension is an operative indication"],
      complications: ["Patella baja", "Hardware prominence", "Stiffness"],
    },
    sourcePath: "trauma-patella-fracture curriculum bridge",
  },
  "tibial-plateau-fracture": {
    topicId: "tibial-plateau-fracture",
    title: "Tibial Plateau Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["knee", "tibial plateau", "Schatzker", "ligament injury"],
    learningObjectives: [
      "Classify tibial plateau fractures by condylar involvement and depression.",
      "Screen for ligament and neurovascular injury around the knee.",
      "Compare nonoperative treatment with plateau ORIF indications.",
    ],
    fast: {
      mustKnow: ["Condylar involvement, depression, knee stability, NV exam"],
      anatomyFocus: ["Tibial plateau", "Lateral condyle", "Medial condyle", "Popliteal artery", "Common peroneal nerve"],
      oneLiner: "Tibial plateau fractures are knee injuries where articular depression and ligament status drive operative planning.",
      pimpQuestions: ["What Schatzker pattern is this?", "When is dual-buttress fixation needed?"],
      orSurvivalTips: ["Document knee stability and NV exam", "Use plateau depression language"],
      caseSteps: ["Describe condylar split/depression", "Check NV status", "State splint versus ORIF", "Plan protected weight bearing"],
    },
    deep: {
      anatomy: ["Lateral and medial plateau", "ACL/PCL relationship", "Posterolateral corner proximity"],
      classification: ["Schatzker I–VI patterns"],
      imaging: ["AP/lateral knee", "CT for depression and split detail"],
      decisionMaking: ["Displacement, instability, associated ligament injury, soft tissues"],
      treatmentOptions: ["Nonoperative in stable patterns", "Tibial plateau ORIF"],
      boardPearls: ["High-energy medial plateau fractures can threaten the popliteal artery"],
      complications: ["Knee stiffness", "Post-traumatic arthritis", "Compartment syndrome"],
    },
    sourcePath: "trauma-tibial-plateau-fractures curriculum bridge",
  },
  "pilon-fracture": {
    topicId: "pilon-fracture",
    title: "Pilon Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["pilon", "tibial plafond", "ankle", "soft tissue"],
    learningObjectives: [
      "Recognize high-energy tibial plafond fractures with soft-tissue risk.",
      "Explain staged management with external fixation bridging.",
      "Identify wound complications and articular restoration priorities.",
    ],
    fast: {
      mustKnow: ["Soft tissue status, articular comminution, staged fixation, fibula role"],
      anatomyFocus: ["Tibial plafond", "Distal tibia articular surface", "Ankle mortise", "Plantar soft tissues"],
      oneLiner: "Pilon fractures are ankle-spanning injuries where soft tissues often dictate staged operative timing.",
      pimpQuestions: ["Why stage pilon fixation?", "When is fibula fixation part of the plan?"],
      orSurvivalTips: ["Lead with soft-tissue envelope language", "Mention spanning ex-fix bridge"],
      caseSteps: ["Assess soft tissues", "Describe articular injury", "Apply splint/ex-fix bridge", "Plan delayed ORIF"],
    },
    deep: {
      anatomy: ["Tibial plafond", "Ankle joint surface", "Distal fibula relationship"],
      classification: ["Ruedi-Allgower concepts", "AO pilon patterns"],
      imaging: ["AP/lateral ankle", "CT for articular mapping"],
      decisionMaking: ["Soft-tissue swelling, open injury, articular displacement"],
      treatmentOptions: ["Spanning external fixation", "Definitive pilon ORIF", "Ankle fusion in salvage"],
      boardPearls: ["Definitive fixation through compromised soft tissues increases wound failure risk"],
      complications: ["Wound breakdown", "Infection", "Post-traumatic arthritis"],
    },
    sourcePath: "trauma-tibial-plafond-fractures curriculum bridge",
  },
  "calcaneus-fracture": {
    topicId: "calcaneus-fracture",
    title: "Calcaneus Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["calcaneus", "hindfoot", "Böhler angle", "subtalar joint"],
    learningObjectives: [
      "Interpret Böhler angle and hindfoot alignment after calcaneus fracture.",
      "Explain Sanders articular classification relevance.",
      "Compare nonoperative care with calcaneus ORIF in appropriate patients.",
    ],
    fast: {
      mustKnow: ["Mechanism, Böhler angle, heel alignment, soft tissue swelling"],
      anatomyFocus: ["Calcaneus", "Subtalar joint", "Posterior facet", "Plantar soft tissues"],
      oneLiner: "Calcaneus fractures are hindfoot injuries where articular depression and soft-tissue swelling shape treatment.",
      pimpQuestions: ["What does a decreased Böhler angle suggest?", "When is operative fixation reasonable?"],
      orSurvivalTips: ["Measure Böhler angle on lateral", "Mention lateral extensile wound risk"],
      caseSteps: ["Describe heel deformity", "Review lateral radiograph", "Assess soft tissues", "State nonoperative versus ORIF"],
    },
    deep: {
      anatomy: ["Posterior facet", "Sustentaculum tali", "Subtalar articulation"],
      classification: ["Sanders articular patterns", "Essex-Lopresti tongue/depression"],
      imaging: ["Lateral and axial heel views", "CT for articular planning"],
      decisionMaking: ["Articular displacement, alignment, soft tissues, patient function"],
      treatmentOptions: ["Protected weight bearing", "Calcaneus ORIF", "Primary subtalar fusion in select cases"],
      boardPearls: ["Severe soft-tissue swelling can delay operative calcaneus fixation"],
      complications: ["Wound complications", "Subtalar arthritis", "Heel widening"],
    },
    sourcePath: "trauma-calcaneus-fractures curriculum bridge",
  },
  "talus-fracture": {
    topicId: "talus-fracture",
    title: "Talus Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["talus", "talar neck", "AVN", "hindfoot"],
    learningObjectives: [
      "Recognize talar neck fracture blood supply risk.",
      "Explain Hawkins classification and AVN surveillance.",
      "Outline fixation and nonoperative pathways by displacement.",
    ],
    fast: {
      mustKnow: ["Talar neck location, displacement, AVN risk, hindfoot alignment"],
      anatomyFocus: ["Talus", "Talar neck", "Talar body blood supply", "Subtalar and ankle joints"],
      oneLiner: "Talar neck fractures are hindfoot injuries where displacement predicts avascular necrosis risk.",
      pimpQuestions: ["Why is the talus vulnerable to AVN?", "What changes management with displacement?"],
      orSurvivalTips: ["Use Hawkins language", "Mention urgent reduction/fixation for displaced neck fractures"],
      caseSteps: ["Describe neck fracture displacement", "Assess hindfoot alignment", "State reduction urgency", "Plan AVN surveillance"],
    },
    deep: {
      anatomy: ["Talar neck vascular watershed", "Body and head perfusion"],
      classification: ["Hawkins I–IV patterns"],
      imaging: ["Canale view concept", "CT for displacement detail"],
      decisionMaking: ["Displacement, open injury, associated subtalar/ankle involvement"],
      treatmentOptions: ["Cast immobilization in select patterns", "Talus ORIF"],
      boardPearls: ["Displaced talar neck fractures carry high AVN risk"],
      complications: ["Avascular necrosis", "Subtalar arthritis", "Malunion"],
    },
    sourcePath: "trauma-talar-neck-fractures curriculum bridge",
  },
  "lisfranc-injury": {
    topicId: "lisfranc-injury",
    title: "Lisfranc Injury",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["lisfranc", "midfoot", "instability", "ORIF"],
    learningObjectives: [
      "Identify Lisfranc ligament disruption and midfoot instability.",
      "Interpret weight-bearing radiographs when available.",
      "Differentiate nonoperative immobilization from operative stabilization.",
    ],
    fast: {
      mustKnow: ["Midfoot pain, instability, diastasis language, weight-bearing films"],
      anatomyFocus: ["Lisfranc joint", "Medial cuneiform-second metatarsal", "Midfoot arch"],
      oneLiner: "Lisfranc injury is a midfoot stability problem where subtle diastasis can become chronic disability.",
      pimpQuestions: ["What radiographic finding suggests instability?", "When is ORIF indicated?"],
      orSurvivalTips: ["Ask for weight-bearing views", "Mention dorsal disruption and instability"],
      caseSteps: ["Localize midfoot tenderness", "Review alignment views", "Assess instability", "State immobilization versus ORIF"],
    },
    deep: {
      anatomy: ["Lisfranc ligament", "Tarsometatarsal articulations", "Plantar ligamentous support"],
      classification: ["Pure ligamentous versus fracture-dislocation patterns"],
      imaging: ["AP/oblique/weight-bearing foot radiographs", "CT for occult injuries"],
      decisionMaking: ["Displacement, instability, athletic demand, timing of diagnosis"],
      treatmentOptions: ["Nonoperative immobilization", "Lisfranc ORIF"],
      boardPearls: ["Missed Lisfranc instability leads to chronic midfoot collapse"],
      complications: ["Chronic instability", "Post-traumatic arthritis", "Planovalgus deformity"],
    },
    sourcePath: "foot-ankle-lisfranc-injury curriculum bridge",
  },
  "acl-tear": {
    topicId: "acl-tear",
    title: "ACL Tear",
    trackId: "sports",
    subspecialty: "Sports",
    tags: ["knee", "ligament", "pivot shift", "sports injury"],
    learningObjectives: [
      "Recognize the classic history and exam findings of ACL injury.",
      "Describe associated injuries and the role of MRI.",
      "Outline nonoperative versus reconstruction pathways at a student level.",
    ],
    fast: {
      mustKnow: ["Pop, effusion, Lachman, pivoting instability, rehab importance"],
      anatomyFocus: ["ACL bundles", "Secondary stabilizers", "Meniscus relationship"],
      oneLiner: "ACL tears are instability injuries diagnosed by history and exam, with reconstruction decisions shaped by goals and associated pathology.",
      pimpQuestions: ["Why is Lachman better than anterior drawer?", "What associated injuries matter?"],
      orSurvivalTips: ["Mention bone bruise pattern on MRI", "Do not ignore meniscus injury"],
      caseSteps: ["Summarize mechanism", "State key exam tests", "Mention MRI and prehab"],
    },
    deep: {
      anatomy: ["ACL footprint", "Rotational stabilizers", "Anterolateral structures"],
      classification: ["Complete versus partial tear", "Acute versus chronic instability"],
      imaging: ["MRI patterns", "Associated bone bruise and meniscus findings"],
      decisionMaking: ["Instability symptoms, sport demands, age, concomitant injuries"],
      treatmentOptions: ["Rehab-only pathway", "ACL reconstruction with graft selection concepts"],
      boardPearls: ["A good Lachman with hemarthrosis after a pivot injury is highly suggestive"],
      complications: ["Stiffness", "Graft failure", "Cyclops lesion", "Persistent instability"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts",
  },
  "meniscus-tear": {
    topicId: "meniscus-tear",
    title: "Meniscus Tear",
    trackId: "sports",
    subspecialty: "Sports",
    tags: ["knee", "locking", "joint line tenderness", "sports"],
    learningObjectives: [
      "Differentiate traumatic from degenerative meniscus tears.",
      "Use exam and MRI thoughtfully when symptoms suggest meniscal pathology.",
      "Explain repair versus meniscectomy considerations.",
    ],
    fast: {
      mustKnow: ["Joint line tenderness, mechanical symptoms, tear location matters"],
      anatomyFocus: ["Medial vs lateral meniscus", "Red-red and white-white zones"],
      oneLiner: "Meniscus tears range from rehab problems to repairable mechanical lesions depending on pattern and symptoms.",
      pimpQuestions: ["Why do some tears get repaired?", "What symptoms favor surgery?"],
      orSurvivalTips: ["Use peripheral vascularity language", "Mention locked knee urgency"],
      caseSteps: ["Describe symptoms", "State exam maneuvers", "Mention when MRI helps", "Outline basic treatment categories"],
    },
    deep: {
      anatomy: ["Meniscal roots and horn attachments", "Hoop stress function"],
      classification: ["Radial, vertical, horizontal, root, bucket-handle tears"],
      imaging: ["MRI tear patterns and extrusion"],
      decisionMaking: ["Age, symptoms, tear pattern, ACL status, repairability"],
      treatmentOptions: ["PT and activity modification", "Repair", "Partial meniscectomy", "Root repair concepts"],
      boardPearls: ["Peripheral longitudinal tears in young knees are the classic repairable lesion"],
      complications: ["Persistent pain", "Re-tear", "Accelerated arthritis after meniscectomy"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts",
  },
  "rotator-cuff-tear": {
    topicId: "rotator-cuff-tear",
    title: "Rotator Cuff Tear",
    trackId: "sports",
    subspecialty: "Sports",
    tags: ["shoulder", "impingement", "abduction weakness"],
    learningObjectives: [
      "Recognize common cuff tear presentations and key exam findings.",
      "Explain the role of x-rays and MRI in workup.",
      "Outline initial conservative care and when surgery becomes more urgent.",
    ],
    fast: {
      mustKnow: ["Night pain, weakness, active versus passive ROM, traumatic acute tears"],
      anatomyFocus: ["Supraspinatus", "Infraspinatus", "Subscapularis", "Biceps"],
      oneLiner: "Rotator cuff tears are shoulder dysfunction problems where age, acuity, and functional loss shape urgency.",
      pimpQuestions: ["Why are acute traumatic tears different?", "What x-ray findings suggest chronic cuff disease?"],
      orSurvivalTips: ["Mention pseudoparalysis when severe", "Know cuff muscle actions"],
      caseSteps: ["Describe active ROM", "Localize weakness", "Mention x-rays before MRI", "State PT versus surgery framework"],
    },
    deep: {
      anatomy: ["Force couples of the shoulder", "Cuff insertion footprints"],
      classification: ["Partial versus full-thickness", "Acute versus chronic", "Massive tears"],
      imaging: ["X-ray findings", "MRI for tendon quality, retraction, and atrophy"],
      decisionMaking: ["Symptoms, function, tear size, chronicity, patient goals"],
      treatmentOptions: ["PT", "Injections in selected settings", "Arthroscopic repair", "Reverse arthroplasty for irreparable patterns"],
      boardPearls: ["Passive ROM preserved with weak active elevation suggests cuff pathology rather than adhesive capsulitis"],
      complications: ["Stiffness", "Re-tear", "Persistent weakness"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts",
  },
  "shoulder-instability": {
    topicId: "shoulder-instability",
    title: "Shoulder Instability",
    trackId: "sports",
    subspecialty: "Sports",
    tags: ["shoulder", "labrum", "dislocation", "bankart"],
    learningObjectives: [
      "Recognize anterior instability presentation and reduction priorities.",
      "Explain recurrence risk in young athletes.",
      "Describe key associated lesions such as Bankart and Hill-Sachs injuries.",
    ],
    fast: {
      mustKnow: ["Check axillary nerve, confirm reduction, discuss recurrence risk"],
      anatomyFocus: ["Glenoid labrum", "Capsulolabral complex", "Hill-Sachs lesion"],
      oneLiner: "Shoulder instability is usually a labral/capsular injury pattern whose recurrence risk is highest in young active patients.",
      pimpQuestions: ["Why do young athletes recur?", "What is a Bankart lesion?"],
      orSurvivalTips: ["Always mention axillary nerve sensation", "Use instability episode language"],
      caseSteps: ["Assess neurovascular status", "Obtain pre/post-reduction films", "State sling and follow-up plan"],
    },
    deep: {
      anatomy: ["Static and dynamic stabilizers", "Glenoid track concept at a high level"],
      classification: ["Anterior versus posterior versus multidirectional instability"],
      imaging: ["Radiographs for reduction and bony injury", "MRI for labral pathology", "CT for bone loss"],
      decisionMaking: ["Age, sport, recurrence, bone loss, associated lesions"],
      treatmentOptions: ["Rehab", "Arthroscopic stabilization", "Bone block procedures in bone loss"],
      boardPearls: ["First-time anterior dislocation in a young athlete carries a high recurrence risk"],
      complications: ["Recurrent instability", "Stiffness", "Nerve injury"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts",
  },
  "achilles-tendon-rupture": {
    topicId: "achilles-tendon-rupture",
    title: "Achilles Tendon Rupture",
    trackId: "sports",
    subspecialty: "Sports",
    tags: ["ankle", "tendon", "thompson test", "push-off weakness"],
    learningObjectives: [
      "Identify classic Achilles rupture history and exam.",
      "Explain the Thompson test and resting tension findings.",
      "Compare operative and nonoperative treatment at a high level.",
    ],
    fast: {
      mustKnow: ["Sudden pop, Thompson test, plantarflexion weakness, early immobilization in equinus"],
      anatomyFocus: ["Achilles watershed zone", "Gastrocnemius-soleus complex"],
      oneLiner: "Achilles rupture is usually a clinical diagnosis where early recognition preserves treatment options.",
      pimpQuestions: ["Who can be treated nonoperatively?", "Why does delay matter?"],
      orSurvivalTips: ["Do not forget comparison to the opposite side", "Mention resting tendon tension"],
      caseSteps: ["State mechanism", "Describe Thompson test", "Mention splinting in plantarflexion", "Outline referral urgency"],
    },
    deep: {
      anatomy: ["Tendon blood supply and rupture zone", "Gastroc-soleus biomechanics"],
      classification: ["Acute versus chronic rupture", "Insertional versus midsubstance"],
      imaging: ["Ultrasound or MRI only when exam is equivocal"],
      decisionMaking: ["Gap, patient activity level, treatment compliance, chronicity"],
      treatmentOptions: ["Functional nonoperative rehab", "Open or percutaneous repair"],
      boardPearls: ["A positive Thompson test in the right story is often enough to act"],
      complications: ["Re-rupture", "Wound issues", "Tendon elongation"],
    },
    sourcePath: "src/lib/student-curriculum/curriculum-data.ts",
  },
};

export function loadPrepareTopicSlice(topicId: string): PrepareTopicSlice | undefined {
  return PREPARE_SLICES[topicId] ?? loadAdultReconstructionPrepareSlice(topicId);
}