import type { DifficultyLevel, StudentLevel } from "@/lib/student-curriculum/curriculum-types";

type CompactTopicSeed = {
  id: string;
  title: string;
  aliases?: string[];
  trackId: string;
  subspecialty: string;
  studentLevel?: StudentLevel;
  difficulty?: DifficultyLevel;
  tags: string[];
  commonCases: Array<{ name: string; scenario: string }>;
  learningObjectives: string[];
  prerequisites?: string[];
  relatedTopicIds: string[];
  mustKnow: string[];
  anatomyFocus: string[];
  caseSteps: string[];
  pimpQuestions: string[];
  orSurvivalTips: string[];
  oneLiner: string;
  anatomy: string[];
  classification: string[];
  imaging: string[];
  decisionMaking: string[];
  treatmentOptions: string[];
  surgicalApproach: string[];
  complications: string[];
  boardPearls: string[];
  selfCheckQuestions: string[];
};

function compactTopic(seed: CompactTopicSeed) {
  return {
    id: seed.id,
    title: seed.title,
    aliases: seed.aliases ?? [],
    trackId: seed.trackId,
    subspecialty: seed.subspecialty,
    studentLevel: seed.studentLevel ?? "clerkship",
    difficulty: seed.difficulty ?? "core",
    tags: seed.tags,
    commonCases: seed.commonCases,
    learningObjectives: seed.learningObjectives,
    prerequisites: seed.prerequisites ?? [],
    relatedTopicIds: seed.relatedTopicIds,
    fast: {
      mustKnow: seed.mustKnow,
      anatomyFocus: seed.anatomyFocus,
      caseSteps: seed.caseSteps,
      pimpQuestions: seed.pimpQuestions,
      orSurvivalTips: seed.orSurvivalTips,
      oneLiner: seed.oneLiner,
    },
    deep: {
      anatomy: seed.anatomy,
      classification: seed.classification,
      imaging: seed.imaging,
      decisionMaking: seed.decisionMaking,
      treatmentOptions: seed.treatmentOptions,
      surgicalApproach: seed.surgicalApproach,
      complications: seed.complications,
      boardPearls: seed.boardPearls,
      selfCheckQuestions: seed.selfCheckQuestions,
    },
  };
}

export const CURRICULUM_EXPANSION_SEEDS = [
  compactTopic({
    id: "tibial-plateau-fracture",
    title: "Tibial Plateau Fracture",
    aliases: ["schatzker fracture", "lateral plateau fracture"],
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["knee", "fracture", "plateau", "schatzker"],
    commonCases: [
      { name: "Valgus knee injury", scenario: "Older adult after low-energy fall with knee swelling and pain." },
      { name: "High-energy plateau fracture", scenario: "Younger patient after MVC with compartment concern." },
    ],
    learningObjectives: [
      "Classify tibial plateau fractures using Schatzker patterns.",
      "Explain when nonoperative management is reasonable.",
      "Identify soft-tissue and compartment concerns.",
    ],
    relatedTopicIds: ["tibial-shaft-fracture", "knee-osteoarthritis", "compartment-syndrome"],
    mustKnow: ["Mechanism, Schatzker pattern language, NV exam, compartment watch"],
    anatomyFocus: ["Lateral plateau", "Medial plateau", "Meniscus and ligament injury"],
    caseSteps: ["Assess swelling and compartments", "Describe fracture split/depression", "State stability plan", "Discuss OR timing"],
    pimpQuestions: ["What makes a plateau fracture unstable?", "When do you worry about compartment syndrome?"],
    orSurvivalTips: ["Mention split versus depression", "Soft tissues often drive operative timing"],
    oneLiner: "Tibial plateau fractures combine articular injury, instability, and soft-tissue risk.",
    anatomy: ["Medial and lateral plateau columns", "Meniscal and ligamentous injury patterns"],
    classification: ["Schatzker I-VI", "Split versus depression patterns"],
    imaging: ["AP/lateral/oblique knee films", "CT for operative planning"],
    decisionMaking: ["Nonoperative for stable low-energy patterns versus ORIF for instability/articular step-off"],
    treatmentOptions: ["Hinged knee brace", "ORIF with rafting/buttress plating", "External fixation in swollen knee"],
    surgicalApproach: ["Anterolateral and posteromedial approaches basics"],
    complications: ["Stiffness", "Malunion", "Compartment syndrome", "Post-traumatic arthritis"],
    boardPearls: ["Soft-tissue condition often dictates timing more than the fracture line alone"],
    selfCheckQuestions: ["How does Schatzker guide treatment?", "What exam finding raises compartment concern?"],
  }),
  compactTopic({
    id: "pilon-fracture",
    title: "Pilon Fracture",
    aliases: ["tibial plafond fracture", "distal tibia intra-articular fracture"],
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["ankle", "pilon", "intra-articular", "trauma"],
    commonCases: [
      { name: "High-energy ankle injury", scenario: "Axial loading injury with severe swelling and articular comminution." },
    ],
    learningObjectives: [
      "Explain why pilon fractures are high-energy intra-articular injuries.",
      "Describe staged management when soft tissues are compromised.",
      "Identify articular restoration priorities.",
    ],
    relatedTopicIds: ["ankle-fracture", "external-fixation", "compartment-syndrome"],
    mustKnow: ["High-energy mechanism, soft-tissue status, articular step-off, staged fixation concept"],
    anatomyFocus: ["Distal tibial articular surface", "Fibula length", "Ankle mortise"],
    caseSteps: ["Assess soft tissues", "Describe articular injury", "State staging plan", "Mention fibula role"],
    pimpQuestions: ["Why is timing different from a simple ankle fracture?", "What is the role of external fixation?"],
    orSurvivalTips: ["Say whether this is a staged case", "Mention fibular fixation for length"],
    oneLiner: "Pilon fractures are intra-articular distal tibial injuries where soft tissues often dictate staged reconstruction.",
    anatomy: ["Plafond articular surface", "Fibula as lateral column", "Ankle joint congruity"],
    classification: ["Ruedi-Allgower concepts", "High-energy intra-articular patterns"],
    imaging: ["Radiographs", "CT for articular mapping"],
    decisionMaking: ["Staged protocol when swelling is severe", "Definitive fixation when soft tissues allow"],
    treatmentOptions: ["Spanning external fixator", "Definitive ORIF", "Ankle-spanning temporization"],
    surgicalApproach: ["Anteromedial and anterolateral exposure concepts"],
    complications: ["Wound breakdown", "Infection", "Post-traumatic arthritis", "Malunion"],
    boardPearls: ["Do not rush definitive fixation through compromised skin"],
    selfCheckQuestions: ["What is the first priority in a swollen pilon?", "Why is CT essential?"],
  }),
  compactTopic({
    id: "pelvic-fracture",
    title: "Pelvic Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["pelvis", "polytrauma", "hemorrhage", "stability"],
    commonCases: [
      { name: "High-energy pelvic injury", scenario: "Trauma bay patient with pelvic pain and hemodynamic concern." },
    ],
    learningObjectives: [
      "Differentiate stable versus unstable pelvic ring injuries.",
      "Explain initial resuscitation priorities.",
      "Recognize when angiography or binder use matters.",
    ],
    relatedTopicIds: ["acetabulum-fracture", "polytrauma", "external-fixation"],
    mustKnow: ["Mechanism, hemodynamic status, pelvic binder, unstable pattern language"],
    anatomyFocus: ["Anterior ring", "Posterior ring", "Sacroiliac complex"],
    caseSteps: ["Assess stability and bleeding risk", "Describe ring injury pattern", "State resuscitation priorities", "Mention fixation timing"],
    pimpQuestions: ["What makes a pelvic fracture unstable?", "When is binder use appropriate?"],
    orSurvivalTips: ["Lead with stability and resuscitation before fracture classification details"],
    oneLiner: "Pelvic fractures are evaluated first through stability, bleeding risk, and associated injury burden.",
    anatomy: ["Anterior pelvic ring", "Posterior pelvic ring", "Sacral anatomy"],
    classification: ["Young-Burgess", "Tile stability concepts"],
    imaging: ["AP pelvis", "Inlet/outlet views", "CT for operative planning"],
    decisionMaking: ["Resuscitation and hemorrhage control before definitive fixation"],
    treatmentOptions: ["Pelvic binder", "Angioembolization", "External fixation", "Definitive ORIF"],
    surgicalApproach: ["Symphyseal and iliosacral fixation concepts"],
    complications: ["Hemorrhage", "Infection", "Neurologic injury", "Chronic instability"],
    boardPearls: ["Unstable pelvic ring injuries can be lethal before they are operative problems"],
    selfCheckQuestions: ["What exam suggests posterior instability?", "What is the first priority in the trauma bay?"],
  }),
  compactTopic({
    id: "acetabulum-fracture",
    title: "Acetabulum Fracture",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["acetabulum", "pelvis", "intra-articular", "trauma"],
    commonCases: [
      { name: "Fall from height", scenario: "Patient with hip pain after axial load injury and incongruent joint concern." },
    ],
    learningObjectives: [
      "Use elementary acetabular fracture pattern language.",
      "Explain why joint congruity drives treatment.",
      "Recognize associated hip instability patterns.",
    ],
    relatedTopicIds: ["pelvic-fracture", "hip-fracture", "external-fixation"],
    mustKnow: ["Mechanism, column/wall language basics, joint congruity, hip stability"],
    anatomyFocus: ["Anterior column", "Posterior column", "Roof weight-bearing zone"],
    caseSteps: ["Describe fracture orientation", "Comment on joint congruity", "Assess hip stability", "State operative versus nonoperative plan"],
    pimpQuestions: ["What part of the acetabulum is most important for load bearing?", "When is operative fixation indicated?"],
    orSurvivalTips: ["Use Letournel language only as precisely as you can"],
    oneLiner: "Acetabulum fractures are judged by joint congruity, stability, and the weight-bearing roof.",
    anatomy: ["Anterior and posterior columns", "Acetabular roof", "Quadrilateral surface"],
    classification: ["Elementary and associated fracture patterns"],
    imaging: ["Judet views", "CT with 3D reconstructions"],
    decisionMaking: ["Nonoperative for congruent stable patterns versus ORIF for displacement/instability"],
    treatmentOptions: ["Protected weight-bearing", "ORIF", "Total hip arthroplasty in select cases"],
    surgicalApproach: ["Kocher-Langenbeck and ilioinguinal concepts"],
    complications: ["Sciatic nerve injury", "Post-traumatic arthritis", "HO"],
    boardPearls: ["Roof involvement changes everything"],
    selfCheckQuestions: ["What imaging set defines operative planning?", "What nerve is at risk posteriorly?"],
  }),
  compactTopic({
    id: "external-fixation",
    title: "External Fixation",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["external fixation", "damage control", "trauma", "stabilization"],
    commonCases: [
      { name: "Damage control orthopaedics", scenario: "Unstable patient with long bone or pelvic injury needing temporization." },
    ],
    learningObjectives: [
      "Explain when external fixation is used as temporizing stabilization.",
      "Describe pin site and construct basics.",
      "Recognize common indications in trauma.",
    ],
    relatedTopicIds: ["pilon-fracture", "pelvic-fracture", "open-fractures"],
    mustKnow: ["Damage control concept", "Safe pin placement principles", "When temporization beats definitive fixation"],
    anatomyFocus: ["Safe corridors", "Joint-spanning versus non-spanning constructs"],
    caseSteps: ["State why temporization is needed", "Describe construct goal", "Mention pin site care", "Plan for later definitive fixation"],
    pimpQuestions: ["When do you span the ankle or knee?", "What makes a construct stable enough?"],
    orSurvivalTips: ["Say whether the frame is damage control or definitive"],
    oneLiner: "External fixation is often a bridge to safer definitive fixation when physiology or soft tissues are not ready.",
    anatomy: ["Pin insertion corridors", "Joint mechanics affected by spanning"],
    classification: ["Damage control versus definitive use"],
    imaging: ["Plain films for alignment", "CT when planning conversion to ORIF"],
    decisionMaking: ["Physiology, soft tissue, and definitive plan timing"],
    treatmentOptions: ["Femoral/tibial spanning frames", "Pelvic C-clamp or anterior frame", "Conversion to ORIF"],
    surgicalApproach: ["Pin placement and bar application basics"],
    complications: ["Pin tract infection", "Malalignment", "Joint stiffness after spanning"],
    boardPearls: ["External fixation is a plan, not a failure"],
    selfCheckQuestions: ["What are indications for spanning the knee?", "What is the goal in damage control orthopaedics?"],
  }),
  compactTopic({
    id: "polytrauma",
    title: "Polytrauma",
    trackId: "trauma",
    subspecialty: "Trauma",
    tags: ["polytrauma", "damage control", "resuscitation", "prioritization"],
    commonCases: [
      { name: "Multiply injured trauma patient", scenario: "Team must prioritize life-threatening injuries and orthopaedic stabilization." },
    ],
    learningObjectives: [
      "Prioritize resuscitation and orthopaedic stabilization in polytrauma.",
      "Explain damage control orthopaedics.",
      "Coordinate timing of orthopaedic interventions.",
    ],
    relatedTopicIds: ["pelvic-fracture", "open-fractures", "compartment-syndrome"],
    mustKnow: ["ABCs first", "Damage control concept", "Life limb over long bone definitive fixation"],
    anatomyFocus: ["Injury burden triage", "Compartment and vascular threats"],
    caseSteps: ["Summarize injury burden", "State immediate threats", "Prioritize orthopaedic timing", "Communicate plan to team"],
    pimpQuestions: ["What orthopaedic problems cannot wait?", "When is damage control appropriate?"],
    orSurvivalTips: ["Speak in priorities, not every fracture at once"],
    oneLiner: "Polytrauma care is about sequencing life-saving and limb-saving priorities before elegant fracture fixation.",
    anatomy: ["Whole-patient physiology", "Compartment and vascular anatomy at risk"],
    classification: ["Immediate versus delayed orthopaedic intervention"],
    imaging: ["Targeted imaging after stabilization"],
    decisionMaking: ["Resuscitation and hemorrhage control before definitive orthopaedic plans"],
    treatmentOptions: ["Damage control external fixation", "Urgent fasciotomy", "Delayed definitive fixation"],
    surgicalApproach: ["Team communication and staged plans"],
    complications: ["Missed compartment syndrome", "ARDS from poorly timed long cases", "Infection in open injuries"],
    boardPearls: ["The orthopaedic plan must fit the patient physiology"],
    selfCheckQuestions: ["What injuries are temporized first?", "What changes your operative timing?"],
  }),
  compactTopic({
    id: "acdf",
    title: "ACDF",
    aliases: ["anterior cervical discectomy and fusion"],
    trackId: "spine",
    subspecialty: "Spine",
    tags: ["cervical", "fusion", "acdf", "spine surgery"],
    commonCases: [
      { name: "Cervical radiculopathy", scenario: "Patient with arm pain and focal disc pathology amenable to anterior surgery." },
    ],
    learningObjectives: [
      "Explain indications for anterior cervical surgery.",
      "Describe key anatomic structures at risk.",
      "Recognize common postoperative concerns.",
    ],
    relatedTopicIds: ["cervical-myelopathy", "lumbar-disc-herniation"],
    mustKnow: ["Radiculopathy versus myelopathy distinction", "Anterior approach structures at risk", "Dysphagia and airway watch"],
    anatomyFocus: ["Esophagus", "Trachea", "Recurrent laryngeal nerve", "Vertebral artery"],
    caseSteps: ["Confirm symptomatic level", "State anterior approach rationale", "Mention graft/plate basics", "Postop airway/dysphagia watch"],
    pimpQuestions: ["What structures are at risk anteriorly?", "When is ACDF preferred over posterior surgery?"],
    orSurvivalTips: ["Know the symptomatic level and what nerve root should improve"],
    oneLiner: "ACDF is an anterior decompression and fusion option for focal cervical radiculopathy and select myelopathy patterns.",
    anatomy: ["Anterior cervical soft tissue corridor", "Nerve root and cord relationship"],
    classification: ["Radiculopathy versus myelopathy indications"],
    imaging: ["MRI for nerve root/cord compression", "Radiographs for alignment"],
    decisionMaking: ["Focal anterior pathology amenable to decompression and fusion"],
    treatmentOptions: ["Anterior discectomy", "Graft and plate fixation", "Alternative posterior options"],
    surgicalApproach: ["Anterior cervical approach basics"],
    complications: ["Dysphagia", "Hoarseness", "Adjacent segment disease", "Nonunion"],
    boardPearls: ["Anterior surgery is about precise level identification and safe corridor development"],
    selfCheckQuestions: ["What complication should you monitor immediately postop?", "What imaging confirms the level?"],
  }),
  compactTopic({
    id: "lumbar-decompression",
    title: "Lumbar Decompression",
    trackId: "spine",
    subspecialty: "Spine",
    tags: ["lumbar", "decompression", "stenosis", "discectomy"],
    commonCases: [
      { name: "Lumbar stenosis", scenario: "Older adult with neurogenic claudication needing posterior decompression." },
    ],
    learningObjectives: [
      "Differentiate decompression goals for stenosis versus disc herniation.",
      "Explain basic posterior lumbar exposure concepts.",
      "Recognize postoperative activity expectations.",
    ],
    relatedTopicIds: ["lumbar-spinal-stenosis", "lumbar-disc-herniation", "tlif"],
    mustKnow: ["Stenosis versus radiculopathy target", "Lamina and ligamentum flavum language", "Neural element decompression goal"],
    anatomyFocus: ["Lamina", "Ligamentum flavum", "Thecal sac and nerve roots"],
    caseSteps: ["State symptomatic level", "Describe compression source", "Explain decompression goal", "Mention stability concerns"],
    pimpQuestions: ["What symptom pattern suggests stenosis?", "When is fusion added?"],
    orSurvivalTips: ["Say what is being decompressed and why symptoms should improve"],
    oneLiner: "Lumbar decompression removes the compressive tissue causing radiculopathy or neurogenic claudication.",
    anatomy: ["Posterior lumbar elements", "Foraminal anatomy"],
    classification: ["Stenosis versus herniated disc targets"],
    imaging: ["MRI showing central or foraminal compression"],
    decisionMaking: ["Decompression alone versus decompression with fusion"],
    treatmentOptions: ["Laminectomy", "Laminotomy/foraminotomy", "Fusion when instability exists"],
    surgicalApproach: ["Posterior midline exposure basics"],
    complications: ["Dural tear", "Instability after aggressive decompression", "Recurrent stenosis"],
    boardPearls: ["The symptom pattern should match the decompression plan"],
    selfCheckQuestions: ["What is neurogenic claudication?", "When do you add fusion?"],
  }),
  compactTopic({
    id: "tlif",
    title: "TLIF",
    aliases: ["transforaminal lumbar interbody fusion"],
    trackId: "spine",
    subspecialty: "Spine",
    tags: ["lumbar", "fusion", "tlif", "interbody"],
    commonCases: [
      { name: "Lumbar instability with stenosis", scenario: "Patient needs decompression plus interbody fusion for instability." },
    ],
    learningObjectives: [
      "Explain the goal of interbody fusion in lumbar disease.",
      "Describe TLIF as a unilateral interbody approach.",
      "Recognize instrumentation basics.",
    ],
    relatedTopicIds: ["lumbar-decompression", "lumbar-spinal-stenosis"],
    mustKnow: ["Why interbody support is used", "Unilateral transforaminal corridor", "Pedicle screw instrumentation basics"],
    anatomyFocus: ["Pedicles", "Intervertebral disc space", "Nerve root in foramen"],
    caseSteps: ["State instability/deformity rationale", "Describe interbody goal", "Mention posterior instrumentation", "Postop fusion expectations"],
    pimpQuestions: ["Why add an interbody cage?", "What does TLIF stand for?"],
    orSurvivalTips: ["Know the level and whether the case is decompression plus fusion"],
    oneLiner: "TLIF combines posterior decompression with interbody fusion through a transforaminal corridor.",
    anatomy: ["Transforaminal corridor", "Pedicle screw trajectory basics"],
    classification: ["Instability and deformity indications"],
    imaging: ["MRI and standing films for instability"],
    decisionMaking: ["When deformity or instability requires fusion support"],
    treatmentOptions: ["TLIF", "PLIF alternatives", "Decompression alone if stable"],
    surgicalApproach: ["Posterior instrumentation and interbody placement"],
    complications: ["Nerve root irritation", "Pseudarthrosis", "Cage subsidence"],
    boardPearls: ["Fusion is for instability, deformity, or need for durable indirect decompression"],
    selfCheckQuestions: ["What problem does the cage solve?", "When is fusion unnecessary?"],
  }),
  compactTopic({
    id: "cervical-trauma",
    title: "Cervical Trauma",
    trackId: "spine",
    subspecialty: "Spine",
    tags: ["cervical", "trauma", "fracture", "instability"],
    commonCases: [
      { name: "Cervical fracture-dislocation", scenario: "Trauma patient with neck pain and neurologic concern." },
    ],
    learningObjectives: [
      "Identify unstable cervical injury patterns.",
      "Explain initial immobilization and imaging priorities.",
      "Recognize neurologic emergency language.",
    ],
    relatedTopicIds: ["cervical-myelopathy", "acdf", "cauda-equina-syndrome"],
    mustKnow: ["Mechanism, neurologic exam, immobilization, unstable pattern language"],
    anatomyFocus: ["Cervical stability columns", "Cord at risk", "Facet injury patterns"],
    caseSteps: ["Assess neurologic status", "Describe injury pattern", "State stability", "Mention operative versus nonoperative plan"],
    pimpQuestions: ["What makes a cervical injury unstable?", "When is MRI urgent?"],
    orSurvivalTips: ["Lead with neurologic status and stability"],
    oneLiner: "Cervical trauma management starts with neurologic status, stability, and safe immobilization.",
    anatomy: ["Anterior and posterior stability columns", "Facet joints"],
    classification: ["Subaxial injury classification concepts", "Occiput to C2 injury patterns"],
    imaging: ["CT for fracture detail", "MRI for cord and soft tissue injury"],
    decisionMaking: ["Nonoperative immobilization versus operative stabilization"],
    treatmentOptions: ["Collar immobilization", "Halo", "Posterior or anterior fixation"],
    surgicalApproach: ["Stabilization strategy by injury level"],
    complications: ["Cord injury", "Nonunion", "Loss of reduction"],
    boardPearls: ["A normal neurologic exam can still coexist with unstable injury"],
    selfCheckQuestions: ["What imaging is first-line in awake trauma patients?", "What changes management urgently?"],
  }),
  compactTopic({
    id: "revision-arthroplasty",
    title: "Revision Arthroplasty",
    trackId: "adult-reconstruction",
    subspecialty: "Adult Reconstruction",
    tags: ["revision", "arthroplasty", "implant", "failure"],
    commonCases: [
      { name: "Painful total joint replacement", scenario: "Patient with painful THA/TKA and concern for loosening or instability." },
    ],
    learningObjectives: [
      "Outline a workup framework for painful arthroplasty.",
      "Explain common failure modes.",
      "Recognize why revision is more complex than primary arthroplasty.",
    ],
    relatedTopicIds: ["periprosthetic-joint-infection", "total-hip-arthroplasty", "total-knee-arthroplasty"],
    mustKnow: ["Painful joint replacement differential", "Loosening, instability, infection language", "Revision complexity"],
    anatomyFocus: ["Prior surgical planes", "Bone loss concerns", "Implant interface"],
    caseSteps: ["Define pain pattern", "Review labs and imaging", "State leading failure mode", "Mention revision complexity"],
    pimpQuestions: ["How do you rule out infection?", "What are common failure modes?"],
    orSurvivalTips: ["Never assume pain is loosening without a workup framework"],
    oneLiner: "Revision arthroplasty starts with a disciplined differential for pain, instability, loosening, and infection.",
    anatomy: ["Prior implant interfaces", "Bone stock and soft tissue quality"],
    classification: ["Aseptic loosening versus instability versus infection"],
    imaging: ["Radiographs", "CT for bone loss", "Labs and aspiration when infection suspected"],
    decisionMaking: ["Workup before revision plan"],
    treatmentOptions: ["Component exchange", "Staged revision for infection", "Constraint upgrades"],
    surgicalApproach: ["Explant and reconstruction planning"],
    complications: ["Infection recurrence", "Instability", "Periprosthetic fracture"],
    boardPearls: ["Infection must be ruled out before attributing pain to loosening"],
    selfCheckQuestions: ["What labs and studies matter most?", "Why is revision harder than primary?"],
  }),
  compactTopic({
    id: "periprosthetic-fracture",
    title: "Periprosthetic Fracture",
    trackId: "adult-reconstruction",
    subspecialty: "Adult Reconstruction",
    tags: ["periprosthetic fracture", "arthroplasty", "trauma", "revision"],
    commonCases: [
      { name: "Fall after arthroplasty", scenario: "Patient with painful hip or knee after low-energy fall near prosthesis." },
    ],
    learningObjectives: [
      "Use periprosthetic fracture classification language.",
      "Explain how implant stability changes treatment.",
      "Recognize when revision is required.",
    ],
    relatedTopicIds: ["revision-arthroplasty", "hip-fracture", "total-hip-arthroplasty"],
    mustKnow: ["Implant stability", "Vancouver/Periprosthetic classification basics", "ORIF versus revision decision"],
    anatomyFocus: ["Bone around implant", "Stem fixation", "Fracture location relative to prosthesis"],
    caseSteps: ["Assess implant stability", "Describe fracture location", "State fixation plan", "Mention postop protection"],
    pimpQuestions: ["What changes management most in periprosthetic fractures?", "When is component revision needed?"],
    orSurvivalTips: ["Always mention whether the implant is stable"],
    oneLiner: "Periprosthetic fracture treatment depends on implant stability, fracture location, and bone quality.",
    anatomy: ["Cortical bone around implant", "Stress risers at implant tip"],
    classification: ["Vancouver classification for hip", "Fracture location relative to prosthesis"],
    imaging: ["Radiographs", "CT for planning"],
    decisionMaking: ["Stable implant ORIF versus unstable implant revision"],
    treatmentOptions: ["Plate fixation", "Cable and graft augmentation", "Revision components"],
    surgicalApproach: ["Preserve implant when stable and possible"],
    complications: ["Nonunion", "Implant loosening", "Recurrent fracture"],
    boardPearls: ["Stability is the key fork in the road"],
    selfCheckQuestions: ["What is the first question to answer?", "When do you revise instead of fix?"],
  }),
  compactTopic({
    id: "cartilage-restoration",
    title: "Cartilage Restoration",
    trackId: "sports",
    subspecialty: "Sports",
    tags: ["cartilage", "meniscus", "knee", "sports"],
    commonCases: [
      { name: "Focal cartilage defect", scenario: "Young active patient with focal knee pain and cartilage injury on MRI." },
    ],
    learningObjectives: [
      "Explain indications for cartilage restoration procedures.",
      "Differentiate focal defects from advanced arthritis.",
      "Recognize common restoration options.",
    ],
    relatedTopicIds: ["meniscus-tear", "knee-osteoarthritis", "acl-tear"],
    mustKnow: ["Focal defect versus arthritis", "Patient age and activity goals", "Common restoration options"],
    anatomyFocus: ["Articular cartilage zones", "Meniscus relationship", "Alignment considerations"],
    caseSteps: ["Define defect size and location", "Assess alignment and meniscus status", "State restoration option", "Discuss rehab expectations"],
    pimpQuestions: ["When is marrow stimulation enough?", "What patient factors matter most?"],
    orSurvivalTips: ["Say whether this is focal cartilage disease versus global arthritis"],
    oneLiner: "Cartilage restoration is for focal articular defects in appropriately selected active patients.",
    anatomy: ["Articular cartilage", "Subchondral bone", "Meniscus and alignment"],
    classification: ["Defect size and location", "Outerbridge-style damage language"],
    imaging: ["MRI cartilage mapping", "Alignment films"],
    decisionMaking: ["Focal defect in active patient versus arthroplasty pathway"],
    treatmentOptions: ["Marrow stimulation", "OATS/mosaicplasty", "MACI and related options"],
    surgicalApproach: ["Defect preparation and graft placement basics"],
    complications: ["Incomplete fill", "Delamination", "Progression to arthritis"],
    boardPearls: ["Alignment and meniscus status can make or break cartilage surgery"],
    selfCheckQuestions: ["Who is a good candidate?", "What imaging defines the defect?"],
  }),
];