import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const root=new URL("../../../",import.meta.url);
const read=(path:string)=>readFileSync(new URL(path,root),"utf8");
const workspace=read("src/components/mycases/MyCasesWorkspace.tsx");
const student=read("src/app/student-workspace/mycases/page.tsx");
const resident=read("src/app/work/mycases/page.tsx");
const notes=read("src/app/student-workspace/notes/page.tsx");
const overview=read("src/components/mycases/overview/MyCasesOverview.tsx");
const cases=read("src/components/mycases/cases/CasesLibrary.tsx");
const detail=read("src/components/mycases/cases/CaseDetail.tsx");
const media=read("src/components/mycases/media/SecureMediaGallery.tsx");
const thumbnail=read("src/components/mycases/media/SecureThumbnail.tsx");
const knowledge=read("src/components/mycases/knowledge/KnowledgeLibrary.tsx");
const collections=read("src/components/mycases/collections/CollectionsView.tsx");
const search=read("src/components/mycases/search/SearchView.tsx");
const fixtures=read("src/lib/mycases/fixtures.ts");

assert(student.includes("<MyCasesWorkspace")); assert(resident.includes("<MyCasesWorkspace"));
assert(student.includes('audience="student"')); assert(resident.includes('audience="resident"'));
assert(student.includes("MYCASES_MEDIA_FIXTURES")); assert(resident.includes("MYCASES_MEDIA_FIXTURES"));
assert(notes.includes('redirect("/student-workspace/mycases?view=notes")'));
for(const section of ["overview","cases","knowledge","collections","search"])assert(workspace.includes(`section===\"${section}\"`));
assert(overview.includes("Featured case")); assert(overview.includes("Recent cases")); assert(overview.includes("Learning highlights"));
assert(overview.includes("SecureThumbnail")); assert(overview.includes("Build the visual memory")||media.includes("Build the visual memory"));
assert(cases.includes('useState<CasesViewMode>("grid")')); assert(cases.includes("List view"));
for(const filter of ["Status","Rotation","Attending context","Tag","Include archived"])assert(cases.includes(filter));
assert(cases.includes("Recently updated")); assert(cases.includes("Recently created"));
assert(thumbnail.includes("ProcedurePlaceholder")); assert(thumbnail.includes("onError={onRetry}"));
assert(detail.indexOf("SecureMediaGallery")<detail.indexOf("Case summary"));
assert(detail.includes("Knowledge from this case")); assert(detail.includes("onAddKnowledge"));
assert(media.includes("thumbnailOnly=true")); assert(media.includes("ensureFullView"));
assert(media.indexOf("ensureFullView")<media.indexOf("viewer.imageUrl"));
for(const key of ['event.key==="Escape"','event.key==="ArrowLeft"','event.key==="ArrowRight"'])assert(media.includes(key));
assert(media.includes("Previous image")); assert(media.includes("Next image"));
assert(media.includes("!attested||progress!==null")); assert(media.includes('form.set("attestation","true")'));
assert(media.includes("Educational media added to the gallery")); assert(media.includes("Upload failed"));
assert(media.includes("window.prompt")); assert(media.includes("window.confirm"));
assert(media.includes("sanitized image and thumbnail will be removed immediately"));
assert(media.includes("URL.revokeObjectURL")); assert.equal(media.includes(".storage"),false);
assert(knowledge.includes("Source case")); assert(knowledge.includes("General knowledge"));
assert(collections.includes("Tags gather related cases")); assert(search.includes("Cases")); assert(search.includes("Knowledge"));
assert(fixtures.includes("several")||fixtures.match(/fixtureAsset\(1,/g)?.length===3);
assert(fixtures.includes("portrait-planning.svg")); assert(fixtures.includes("failedThumbnail:true")); assert(fixtures.includes("is_archived:true"));
for(const responsive of ["sm:","lg:","xl:"])assert(workspace.includes(responsive)||overview.includes(responsive)||cases.includes(responsive));
console.log("MyCases image-first UI contract tests passed");
