"use client";
import { ArrowRight, BookOpen, Camera, Plus, Sparkles } from "lucide-react";
import type { MyCasesCase, MyCasesLearningItem } from "@/lib/mycases/types";
import type { CaseMediaSummaryMap, MyCasesSection } from "../ui-types";
import { LEARNING_LABELS, relativeDate, statusLabel } from "../format";
import { SecureThumbnail } from "../media/SecureThumbnail";

type Props={cases:MyCasesCase[];items:MyCasesLearningItem[];media:CaseMediaSummaryMap;audience:"student"|"resident";onCase:(item:MyCasesCase)=>void;onSection:(section:MyCasesSection)=>void;onAddItem:(caseId?:string)=>void;onAddCase:()=>void;onRetryMedia:(caseId:string)=>void};
export function MyCasesOverview({cases,items,media,audience,onCase,onSection,onAddItem,onAddCase,onRetryMedia}:Props){
  const active=[...cases].filter(item=>!item.is_archived).sort((a,b)=>b.updated_at.localeCompare(a.updated_at));
  const featured=active[0]; const recent=active.slice(0,6); const highlights=[...items].filter(item=>!item.is_archived&&(item.is_pinned||item.kind==="reflection")).sort((a,b)=>Number(b.is_pinned)-Number(a.is_pinned)||b.updated_at.localeCompare(a.updated_at)).slice(0,4);
  if(!featured)return <section className="relative overflow-hidden border border-slate-200 bg-white px-6 py-14 text-center shadow-sm sm:px-10"><div className="absolute inset-x-0 top-0 h-1 bg-blue-600"/><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-slate-950 text-white"><Sparkles className="h-6 w-6"/></div><p className="mt-5 text-xs font-bold uppercase tracking-[.2em] text-blue-700">Private visual case library</p><h2 className="mx-auto mt-3 max-w-xl text-3xl font-black tracking-tight">Turn each case into durable, reusable learning.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-600">Start with a de-identified educational case. Add secure images, preparation, pearls, reflections, and the questions you want to revisit.</p><button onClick={onAddCase} className="mt-7 inline-flex min-h-11 items-center gap-2 rounded-lg bg-slate-950 px-5 py-3 text-sm font-bold text-white focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2"><Plus className="h-4 w-4"/>Add your first case</button></section>;
  return <div className="space-y-10">
    <section className="grid overflow-hidden border border-slate-200 bg-white shadow-sm lg:grid-cols-[1.25fr_.75fr]">
      <button onClick={()=>onCase(featured)} className="relative min-h-[300px] text-left outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-blue-500 lg:min-h-[420px]" aria-label={`Open featured case: ${featured.title}`}><SecureThumbnail media={media[featured.id]} procedure={featured.procedure_name} alt={`Educational thumbnail for ${featured.procedure_name}`} className="absolute inset-0" onRetry={()=>onRetryMedia(featured.id)}/><div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/25 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 text-white sm:p-8"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-blue-200"><span>Featured case</span>{media[featured.id]?.count?<span>• {media[featured.id].count} images</span>:null}</div><h2 className="mt-3 max-w-2xl text-3xl font-black tracking-tight sm:text-4xl">{featured.procedure_name}</h2><p className="mt-2 text-sm text-slate-200">{featured.diagnosis||featured.title}</p></div></button>
      <div className="flex flex-col justify-between p-6 sm:p-8"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">{audience==="student"?"Recent clinical learning":"Recent operative learning"}</p><h3 className="mt-3 text-2xl font-black tracking-tight">{featured.title}</h3><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-600"><span>{statusLabel(featured.status)}</span><span>{featured.rotation_context||"Rotation not recorded"}</span><span>{relativeDate(featured.updated_at)}</span></div>{featured.tags?.length?<div className="mt-5 flex flex-wrap gap-2">{featured.tags.map(tag=><span key={tag.id} className="border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-semibold text-slate-600">#{tag.name}</span>)}</div>:null}</div><div className="mt-8 grid gap-2"><button onClick={()=>onCase(featured)} className="flex min-h-11 items-center justify-between rounded-lg bg-slate-950 px-4 py-3 text-sm font-bold text-white focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2">Open case <ArrowRight className="h-4 w-4"/></button><button onClick={()=>onAddItem(featured.id)} className="flex min-h-11 items-center gap-2 rounded-lg border border-slate-300 px-4 py-3 text-sm font-bold text-slate-800"><BookOpen className="h-4 w-4"/>Add linked learning</button><button onClick={()=>onCase(featured)} className="flex min-h-11 items-center gap-2 px-4 py-2 text-sm font-bold text-blue-700"><Camera className="h-4 w-4"/>Add educational media</button></div></div>
    </section>
    <section><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-500">Visual library</p><h2 className="mt-1 text-2xl font-black tracking-tight">Recent cases</h2></div><button onClick={()=>onSection("cases")} className="text-sm font-bold text-blue-700">View library</button></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{recent.map(item=><button key={item.id} onClick={()=>onCase(item)} className="group overflow-hidden border border-slate-200 bg-white text-left shadow-sm outline-none transition hover:-translate-y-0.5 hover:shadow-md focus-visible:ring-2 focus-visible:ring-blue-500 motion-reduce:transform-none"><SecureThumbnail media={media[item.id]} procedure={item.procedure_name} alt={`Educational thumbnail for ${item.procedure_name}`} className="aspect-[16/9]" onRetry={()=>onRetryMedia(item.id)}/><div className="p-4"><div className="flex items-center justify-between gap-3"><span className="text-xs font-bold uppercase tracking-wide text-blue-700">{item.rotation_context||statusLabel(item.status)}</span><span className="text-xs text-slate-500">{media[item.id]?.count??0} media</span></div><h3 className="mt-2 line-clamp-2 font-bold leading-5">{item.procedure_name}</h3><p className="mt-1 truncate text-sm text-slate-500">{item.diagnosis||item.title}</p></div></button>)}</div></section>
    <section className="grid gap-8 border-t border-slate-200 pt-8 lg:grid-cols-[1fr_280px]"><div><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-500">From experience to knowledge</p><h2 className="mt-1 text-2xl font-black tracking-tight">Learning highlights</h2></div><button onClick={()=>onSection("knowledge")} className="text-sm font-bold text-blue-700">View knowledge</button></div><div className="mt-4 divide-y divide-slate-200 border-y border-slate-200">{highlights.map(item=>{const source=cases.find(c=>c.id===item.case_id);return <article key={item.id} className="grid gap-3 py-5 sm:grid-cols-[92px_1fr_auto] sm:items-center">{source?<SecureThumbnail media={media[source.id]} procedure={source.procedure_name} alt="Source case educational thumbnail" className="aspect-[4/3]" onRetry={()=>onRetryMedia(source.id)}/>:<div className="flex aspect-[4/3] items-center justify-center bg-slate-100 text-xs font-bold text-slate-400">GENERAL</div>}<div><p className="text-xs font-bold uppercase tracking-wide text-blue-700">{LEARNING_LABELS[item.kind]}</p><h3 className="mt-1 font-bold">{item.title||item.content}</h3><p className="mt-1 line-clamp-2 text-sm text-slate-600">{item.content}</p><p className="mt-2 text-xs text-slate-400">{source?source.title:"General knowledge · not case-linked"}</p></div>{item.is_pinned&&<span className="text-xs font-bold text-slate-500">Pinned</span>}</article>})}{!highlights.length&&<p className="py-10 text-sm text-slate-500">Pin a pearl or add a reflection to create your learning highlights.</p>}</div></div><aside className="border-l-0 border-slate-200 lg:border-l lg:pl-8"><p className="text-4xl font-black">{cases.length}</p><p className="text-sm text-slate-500">cases in your library</p><div className="mt-6 space-y-4 border-t border-slate-200 pt-5 text-sm"><p><strong className="block text-xl text-slate-950">{new Set(cases.map(item=>item.procedure_name)).size}</strong><span className="text-slate-500">procedures represented</span></p><p><strong className="block text-xl text-slate-950">{items.filter(item=>!item.is_archived).length}</strong><span className="text-slate-500">active learning items</span></p><p><strong className="block text-xl text-slate-950">{items.filter(item=>item.is_pinned).length}</strong><span className="text-slate-500">pinned for review</span></p></div></aside></section>
  </div>;
}
