import { createHash } from "node:crypto";import { z } from "zod";
export const REVIEWER_CONTRACT_VERSION="snaportho-anki-reviewer.v1" as const;
export const REVIEWER_ROLES=["mapping_reviewer","clinical_editor","deck_editor","release_manager","administrator"] as const;
export const ASSIGNMENT_STATUSES=["draft","assigned","in_progress","submitted","completed","cancelled","superseded"] as const;
export const ITEM_STATUSES=["pending","in_review","decision_saved","change_proposed","submitted","conflict","skipped","superseded"] as const;
export const CONFLICT_TYPES=["server_version_changed","local_content_changed","assignment_superseded","proposal_superseded","card_inactive","entity_inactive","identity_mismatch","duplicate_submission","permission_changed"] as const;
export const NO_MAPPING=["correctly_unmapped","missing_alias","missing_canonical_entity","extraction_failure","threshold_too_conservative","nonclinical_or_low_value","multiconcept_or_ambiguous","deck_improvement_required"] as const;
export const mappingReviewSchema=z.object({contractVersion:z.literal(REVIEWER_CONTRACT_VERSION),canonicalCardId:z.string().uuid(),canonicalCardVersionId:z.string().uuid(),baseContentHash:z.string().regex(/^[a-f0-9]{64}$/),canonicalEntityId:z.string().uuid().nullable(),mappingRole:z.enum(["teaches","tests","explains","demonstrates","context_only","broadly_related"]).nullable(),decision:z.enum(["approved","rejected","needs_changes","defer"]),confidence:z.number().min(0).max(1),noMappingClassification:z.enum(NO_MAPPING).nullable(),ambiguityResolution:z.string().min(1).max(500),reasonCodes:z.array(z.string().regex(/^[a-z0-9_:-]+$/)).max(20),notes:z.string().max(1000),evidenceHashes:z.array(z.string().regex(/^[a-f0-9]{64}$/)).max(50),idempotencyKey:z.string().uuid(),clientVersion:z.string().min(1).max(64),localIdentity:z.object({noteGuid:z.string().min(1).max(64),cardOrdinal:z.number().int().min(0),contentHash:z.string().regex(/^[a-f0-9]{64}$/)})}).strict().superRefine((v,c)=>{if(v.canonicalEntityId===null&&!v.noMappingClassification)c.addIssue({code:"custom",message:"no-mapping classification required"});if(v.canonicalEntityId!==null&&!v.mappingRole)c.addIssue({code:"custom",message:"mapping role required"});});
const fieldSchema=z.object({name:z.string().min(1).max(100),value:z.string().max(50_000)}).strict();
export const changeProposalSchema=z.object({contractVersion:z.literal(REVIEWER_CONTRACT_VERSION),canonicalCardId:z.string().uuid(),canonicalCardVersionId:z.string().uuid(),baseContentHash:z.string().regex(/^[a-f0-9]{64}$/),changeType:z.enum(["content_edit","tag_edit","deck_path_proposal","split_card_proposal","merge_card_proposal","retire_card_proposal","duplicate_report","clinical_correction","formatting_correction"]),status:z.enum(["draft","submitted"]),editedFields:z.array(fieldSchema).max(50),tags:z.array(z.string().max(200)).max(200),proposedDeckPath:z.string().max(1000).nullable(),reasonCodes:z.array(z.string().regex(/^[a-z0-9_:-]+$/)).max(20),notes:z.string().max(1000),newContentHash:z.string().regex(/^[a-f0-9]{64}$/),idempotencyKey:z.string().uuid(),clientVersion:z.string().min(1).max(64),localIdentity:z.object({noteGuid:z.string().min(1).max(64),cardOrdinal:z.number().int().min(0),contentHash:z.string().regex(/^[a-f0-9]{64}$/)})}).strict();
export const workspaceLocalIdentitySchema=z.object({noteGuid:z.string().min(1).max(200),cardOrdinal:z.number().int().min(0),contentHash:z.string().regex(/^[a-f0-9]{64}$/)}).strict();
const mappingChangeSchema=z.object({action:z.enum(["add","remove","change_role"]),canonicalEntityId:z.string().uuid().nullable(),mappingRole:z.enum(["teaches","tests","explains","demonstrates","context_only","broadly_related"]).nullable(),useExpansionSuggestion:z.boolean(),rationale:z.string().min(1).max(1000),confidence:z.number().min(0).max(1)}).strict().superRefine((v,c)=>{if((v.canonicalEntityId===null)===(!v.useExpansionSuggestion))c.addIssue({code:"custom",message:"choose exactly one existing entity or expansion suggestion"});if(v.action!=="remove"&&!v.mappingRole)c.addIssue({code:"custom",message:"mapping role required"});});
const kgExpansionSchema=z.object({suggestionType:z.enum(["new_entity","new_alias"]),preferredLabel:z.string().min(2).max(300),entityType:z.string().regex(/^[a-z][a-z0-9_]{1,63}$/),description:z.string().min(1).max(2000),existingEntityId:z.string().uuid().nullable(),rationale:z.string().min(1).max(1000)}).strict().superRefine((v,c)=>{if(v.suggestionType==="new_alias"&&!v.existingEntityId)c.addIssue({code:"custom",message:"alias suggestion requires an existing entity"});if(v.suggestionType==="new_entity"&&v.existingEntityId)c.addIssue({code:"custom",message:"new entity suggestion cannot target an existing entity"});});
export const workspaceProposalSchema=z.object({contractVersion:z.literal(REVIEWER_CONTRACT_VERSION),proposalKind:z.enum(["edit_existing_card","create_missing_card"]),sourceSurface:z.enum(["browser","reviewer","dashboard"]),baseCard:z.object({canonicalCardId:z.string().uuid(),canonicalCardVersionId:z.string().uuid(),contentHash:z.string().regex(/^[a-f0-9]{64}$/)}).strict().nullable(),localIdentity:workspaceLocalIdentitySchema,editedFields:z.array(fieldSchema).min(1).max(50),centralTagChanges:z.object({add:z.array(z.string().min(1).max(200)).max(100),remove:z.array(z.string().min(1).max(200)).max(100)}).strict(),proposedDeckPath:z.string().min(1).max(1000).nullable(),mappingChanges:z.array(mappingChangeSchema).max(25),kgExpansionSuggestion:kgExpansionSchema.nullable(),notes:z.string().max(2000),idempotencyKey:z.string().uuid(),clientVersion:z.string().min(1).max(64)}).strict().superRefine((v,c)=>{if(v.proposalKind==="edit_existing_card"&&!v.baseCard)c.addIssue({code:"custom",message:"existing card proposal requires a pinned base"});if(v.proposalKind==="create_missing_card"&&v.baseCard)c.addIssue({code:"custom",message:"missing card proposal cannot claim a canonical base"});if(v.mappingChanges.some(m=>m.useExpansionSuggestion)&&!v.kgExpansionSuggestion)c.addIssue({code:"custom",message:"mapping references a missing expansion suggestion"});});
export type WorkspaceProposal=z.infer<typeof workspaceProposalSchema>;
export const workspaceReviewSchema=z.object({contractVersion:z.literal(REVIEWER_CONTRACT_VERSION),decision:z.enum(["approve_for_incorporation","request_changes","reject","defer"]),proposalEvidenceHash:z.string().regex(/^[a-f0-9]{64}$/),reasonCodes:z.array(z.string().regex(/^[a-z0-9_:-]+$/)).max(20),notes:z.string().max(2000),idempotencyKey:z.string().uuid(),clientVersion:z.string().min(1).max(64)}).strict();
export function workspaceProposalEvidenceHash(value:WorkspaceProposal):string{return sha(JSON.stringify(value));}
export type ConflictType=typeof CONFLICT_TYPES[number];
export type ReviewerContext={userId:string;deviceLinkId:string;deviceTokenId:string;roles:string[];active:boolean;reviewerStatus:string;qualificationSnapshot:Record<string,unknown>};
export type PinnedItem={assignmentReviewerId:string;assignmentStatus:string;itemStatus:string;canonicalCardId:string;canonicalCardVersionId:string;baseContentHash:string;noteGuid:string;cardOrdinal:number;cardActive:boolean;currentVersionId:string;entityActive:boolean|null;evidenceHashes:string[];acceptedProposalExists:boolean};
export function validateSubmissionContext(ctx:ReviewerContext,item:PinnedItem,input:z.infer<typeof mappingReviewSchema>|z.infer<typeof changeProposalSchema>,requiredRole:"mapping_reviewer"|"clinical_editor"):ConflictType|null{const hasRole=ctx.roles.includes(requiredRole)||(requiredRole==="mapping_reviewer"&&ctx.roles.includes("clinical_editor"));if(!ctx.active||ctx.reviewerStatus!=="active"||!hasRole)return"permission_changed";if(item.assignmentReviewerId!==ctx.userId)return"permission_changed";if(item.assignmentStatus==="superseded")return"assignment_superseded";if(item.currentVersionId!==item.canonicalCardVersionId)return"server_version_changed";if(!item.cardActive)return"card_inactive";if(input.canonicalCardId!==item.canonicalCardId||input.canonicalCardVersionId!==item.canonicalCardVersionId||input.localIdentity.noteGuid!==item.noteGuid||input.localIdentity.cardOrdinal!==item.cardOrdinal)return"identity_mismatch";if(input.baseContentHash!==item.baseContentHash||input.localIdentity.contentHash!==item.baseContentHash)return"local_content_changed";if(item.acceptedProposalExists)return"proposal_superseded";if("canonicalEntityId" in input&&input.canonicalEntityId&&item.entityActive===false)return"entity_inactive";return null;}
export function assignmentComplete(statuses:string[]):boolean{return statuses.length>0&&statuses.every(s=>["decision_saved","change_proposed","submitted","skipped"].includes(s));}
export function sha(value:string):string{return createHash("sha256").update(value).digest("hex");}
export function safeReviewerMetadata(value:unknown):boolean{if(!value||typeof value!=="object")return true;if(Array.isArray(value))return value.every(safeReviewerMetadata);return Object.entries(value as Record<string,unknown>).every(([k,v])=>!/front|back|field|html|css|media|token|credential|secret|content|payload/i.test(k)&&safeReviewerMetadata(v));}
