import { createHash } from "node:crypto";
// @ts-expect-error Direct Node tooling imports TypeScript source files.
import { deterministicUuid } from "./deck-foundation.ts";

export const SEMANTIC_CONTRACT_VERSION="snaportho-anki-kg-semantic.v1" as const;
export const SEMANTIC_SCHEMA_VERSION="snaportho-anki-kg-semantic-schema.v1" as const;
export const SEMANTIC_IMPLEMENTATION_VERSION="2026-07-20.1" as const;
export const SEMANTIC_PROMPT_VERSION="none-local-lexical" as const;
export type ContentProcessingMode="local_only"|"approved_external_model"|"fixture"|"replay";
export type EphemeralField={name:string;rawValue:string;plainText?:string};
export type EphemeralCard={canonicalCardId:string;canonicalCardVersionId:string;contentHash:string;cardOrdinal:number;tags:string[];fields:EphemeralField[]};
export type EntityIndexRow={id:string;preferredLabel:string;normalizedLabel:string;entityType:string;aliases:string[];sourceAliases:string[];active:boolean;lifecycleStatus:string};
export type ExtractedConcept={contractVersion:typeof SEMANTIC_CONTRACT_VERSION;canonicalCardId:string;canonicalCardVersionId:string;conceptId:string;normalizedConceptLabel:string;clinicalCategory:string;conceptRole:"central_teaching"|"supporting_context"|"comparison"|"differential"|"prerequisite"|"incidental_mention"|"distractor"|"negated";confidence:number;sourceField:string;evidenceHash:string;negated:boolean;distractor:boolean;incidentalMention:boolean;central:boolean;extractionVersion:string};
export type SemanticResolution={resolutionId:string;canonicalCardId:string;canonicalCardVersionId:string;conceptId:string;normalizedConceptLabel:string;canonicalEntityId:string|null;entityType:string|null;proposedMappingRole:"teaches"|"tests"|"explains"|"demonstrates"|"context_only"|"broadly_related"|null;resolutionConfidence:number;evidenceType:string|null;competingCandidates:Array<{id:string;entityType:string;preferredLabel:string}>;specificityComparison:string;lifecycleValid:boolean;evidenceHashes:string[];reasonCodes:string[];resolverVersion:string;disposition:"selected"|"rejected"|"deferred"|"missing_alias"|"missing_entity"|"correctly_unmapped"};
export type SemanticCritic={reviewerType:"clinical_critic"|"specificity_critic"|"negation_distractor_critic"|"coverage_critic"|"card_quality_critic";reviewerVersion:string;canonicalCardId:string;canonicalCardVersionId:string;canonicalEntityId:string|null;decision:"support"|"oppose"|"uncertain";confidence:number;reasonCodes:string[];evidenceHashes:string[]};
export type SemanticCardResult={concepts:ExtractedConcept[];resolutions:SemanticResolution[];critics:SemanticCritic[];qualityFindings:string[]};

function stable(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(",")}}`;}
export function hash(value:unknown):string{return createHash("sha256").update(typeof value==="string"?value:stable(value)).digest("hex");}
export function canonicalContentHash(card:Pick<EphemeralCard,"fields"|"tags"|"cardOrdinal">):string{return hash({noteFields:card.fields.map(f=>({name:f.name,rawValue:f.rawValue})),tags:card.tags,cardOrd:card.cardOrdinal});}
export function stripNonClinicalMarkup(value:string):string{return value.replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/\[sound:[^\]]+\]/gi," ").replace(/<img\b[^>]*>/gi," ").replace(/\{\{[^}]+\}\}/g," ").replace(/\$\$?[\s\S]*?\$\$?/g," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&#39;/gi,"'").replace(/&quot;/gi,'"').replace(/\s+/g," ").trim();}
export function normalizeClinicalText(value:string):string{return stripNonClinicalMarkup(value).toLowerCase().replace(/[^a-z0-9+\-/ ]+/g," ").replace(/\s+/g," ").trim();}
export function validateEphemeralCard(card:EphemeralCard,expected:{cardId:string;versionId:string;contentHash:string}):void{if(card.canonicalCardId!==expected.cardId)throw new Error("card_ownership_mismatch");if(card.canonicalCardVersionId!==expected.versionId)throw new Error("card_version_mismatch");if(card.contentHash!==expected.contentHash||canonicalContentHash(card)!==expected.contentHash)throw new Error("card_content_hash_mismatch");}

const FORBIDDEN_KEYS=/(front|back|raw.?html|css|field.?snapshot|field.?values|apkg|latex|secret|credential|api.?key|password|normalized.?body|card.?body)/i;
const HTML=/<\/?[a-z][^>]*>/i, CSS=/\{\s*[a-z-]+\s*:/i, MEDIA=/(data:image|\[sound:|<img\b)/i;
export function durableSemanticSafetyErrors(value:unknown,path="$"):string[]{const errors:string[]=[];if(typeof value==="string"){if(HTML.test(value))errors.push(`${path}:raw_html`);if(CSS.test(value))errors.push(`${path}:css`);if(MEDIA.test(value))errors.push(`${path}:media`);if(value.length>500)errors.push(`${path}:unbounded_text`);return errors;}if(Array.isArray(value))return value.flatMap((v,i)=>durableSemanticSafetyErrors(v,`${path}[${i}]`));if(value&&typeof value==="object")for(const [k,v] of Object.entries(value as Record<string,unknown>)){if(FORBIDDEN_KEYS.test(k))errors.push(`${path}.${k}:forbidden_key`);errors.push(...durableSemanticSafetyErrors(v,`${path}.${k}`));}return errors;}
export function assertDurableSemanticSafe(value:unknown):void{const errors=durableSemanticSafetyErrors(value);if(errors.length)throw new Error(`unsafe_durable_semantic_artifact:${errors.join(",")}`);}

function phrasePresent(text:string,phrase:string):boolean{return phrase.length>=4&&` ${text} `.includes(` ${phrase} `);}
function detectFlags(text:string,label:string){const at=text.indexOf(label),prefix=at>=0?text.slice(Math.max(0,at-45),at):"";const negated=/\b(no|not|without|except|never|contraindicated)\b/.test(prefix);const distractor=/\b(incorrect|wrong|false|distractor)\b/.test(prefix);const incidental=/\b(history of|associated with|may include)\b/.test(prefix);return{negated,distractor,incidental};}
export function extractConcepts(card:EphemeralCard,entities:EntityIndexRow[]):ExtractedConcept[]{const out:ExtractedConcept[]=[];for(const field of card.fields){const text=normalizeClinicalText(field.plainText??field.rawValue);for(const e of entities.filter(x=>x.active&&!['deprecated','replaced','merged','split'].includes(x.lifecycleStatus))){const labels=[e.normalizedLabel,...e.aliases,...e.sourceAliases].map(normalizeClinicalText).filter(x=>x.split(" ").length>1||x.length>=5);const matched=[...new Set(labels)].filter(l=>phrasePresent(text,l)).sort((a,b)=>b.length-a.length)[0];if(!matched)continue;const flags=detectFlags(text,matched),role=flags.negated?"negated":flags.distractor?"distractor":flags.incidental?"incidental_mention":out.some(x=>x.sourceField===field.name)?"supporting_context":"central_teaching";out.push({contractVersion:SEMANTIC_CONTRACT_VERSION,canonicalCardId:card.canonicalCardId,canonicalCardVersionId:card.canonicalCardVersionId,conceptId:deterministicUuid(`${card.canonicalCardVersionId}|${field.name}|${matched}|${role}`),normalizedConceptLabel:matched,clinicalCategory:e.entityType,conceptRole:role,confidence:role==="central_teaching"?.94:.75,sourceField:field.name,evidenceHash:hash(`${field.name}|${matched}|${role}|${card.contentHash}`),negated:flags.negated,distractor:flags.distractor,incidentalMention:flags.incidental,central:role==="central_teaching",extractionVersion:SEMANTIC_IMPLEMENTATION_VERSION});}}
  return [...new Map(out.sort((a,b)=>a.conceptId.localeCompare(b.conceptId)).map(x=>[x.conceptId,x])).values()];}
export function retrieveEntityCandidates(concept:ExtractedConcept,entities:EntityIndexRow[]):EntityIndexRow[]{const n=normalizeClinicalText(concept.normalizedConceptLabel);return entities.filter(e=>[e.normalizedLabel,...e.aliases,...e.sourceAliases].map(normalizeClinicalText).includes(n)).sort((a,b)=>Number(b.active)-Number(a.active)||a.id.localeCompare(b.id));}
export function resolveConcept(concept:ExtractedConcept,entities:EntityIndexRow[]):SemanticResolution{const all=retrieveEntityCandidates(concept,entities),active=all.filter(e=>e.active&&!['deprecated','replaced','merged','split'].includes(e.lifecycleStatus));const blocked=concept.negated||concept.distractor||concept.incidentalMention;const chosen=active.length===1&&!blocked?active[0]:null;const disposition:SemanticResolution["disposition"]=blocked?"rejected":active.length===1?"selected":active.length>1?"deferred":all.length?"deferred":"missing_entity";return{resolutionId:deterministicUuid(`${concept.conceptId}|${chosen?.id??disposition}`),canonicalCardId:concept.canonicalCardId,canonicalCardVersionId:concept.canonicalCardVersionId,conceptId:concept.conceptId,normalizedConceptLabel:concept.normalizedConceptLabel,canonicalEntityId:chosen?.id??null,entityType:chosen?.entityType??null,proposedMappingRole:chosen?(concept.central?"teaches":"context_only"):null,resolutionConfidence:chosen?.normalizedLabel===concept.normalizedConceptLabel?.97:chosen?.id?.length?.93:0,evidenceType:chosen?(chosen.normalizedLabel===concept.normalizedConceptLabel?"preferred_label":"governed_or_source_alias"):null,competingCandidates:active.map(e=>({id:e.id,entityType:e.entityType,preferredLabel:e.preferredLabel})),specificityComparison:active.length===1?"single_exact_lexical_candidate":active.length>1?"multiple_equal_candidates":"no_candidate",lifecycleValid:Boolean(chosen),evidenceHashes:[concept.evidenceHash],reasonCodes:blocked?[concept.negated?"negated_concept":concept.distractor?"distractor_concept":"incidental_mention"]:active.length===1?["exact_existing_entity"]:active.length>1?["alias_ambiguity"]:["no_existing_entity_candidate"],resolverVersion:SEMANTIC_IMPLEMENTATION_VERSION,disposition};}
export function runSemanticCard(card:EphemeralCard,entities:EntityIndexRow[]):SemanticCardResult{const concepts=extractConcepts(card,entities),resolutions=concepts.map(c=>resolveConcept(c,entities));const quality:string[]=[];if(concepts.filter(c=>c.central).length>2)quality.push("potential_multiconcept_overload");if(card.fields.every(f=>normalizeClinicalText(f.plainText??f.rawValue).length<8))quality.push("insufficient_clinical_content");const critics:SemanticCritic[]=[];for(const r of resolutions){const c=concepts.find(x=>x.conceptId===r.conceptId)!;const base={reviewerVersion:SEMANTIC_IMPLEMENTATION_VERSION,canonicalCardId:r.canonicalCardId,canonicalCardVersionId:r.canonicalCardVersionId,canonicalEntityId:r.canonicalEntityId,evidenceHashes:r.evidenceHashes};critics.push({...base,reviewerType:"clinical_critic",decision:r.disposition==="selected"?"support":"uncertain",confidence:r.resolutionConfidence,reasonCodes:r.reasonCodes},{...base,reviewerType:"specificity_critic",decision:r.competingCandidates.length>1?"oppose":"support",confidence:.9,reasonCodes:r.competingCandidates.length>1?["unresolved_specificity"]:["specificity_supported"]},{...base,reviewerType:"negation_distractor_critic",decision:c.negated||c.distractor||c.incidentalMention?"oppose":"support",confidence:.95,reasonCodes:c.negated?["negated"]:c.distractor?["distractor"]:c.incidentalMention?["incidental"]:["asserted_concept"]});}critics.push({reviewerType:"coverage_critic",reviewerVersion:SEMANTIC_IMPLEMENTATION_VERSION,canonicalCardId:card.canonicalCardId,canonicalCardVersionId:card.canonicalCardVersionId,canonicalEntityId:null,decision:concepts.length?"support":"uncertain",confidence:concepts.length?.8:.4,reasonCodes:concepts.length?["lexical_concepts_extracted"]:["no_concept_extracted"],evidenceHashes:concepts.map(c=>c.evidenceHash)},{reviewerType:"card_quality_critic",reviewerVersion:SEMANTIC_IMPLEMENTATION_VERSION,canonicalCardId:card.canonicalCardId,canonicalCardVersionId:card.canonicalCardVersionId,canonicalEntityId:null,decision:quality.length?"oppose":"support",confidence:.8,reasonCodes:quality.length?quality:["no_deterministic_quality_blocker"],evidenceHashes:[]});return{concepts,resolutions,critics,qualityFindings:quality};}

export function crossCardFindings(results:SemanticCardResult[]):Array<Record<string,unknown>>{const findings:Array<Record<string,unknown>>=[];const byConcept=new Map<string,SemanticResolution[]>();for(const r of results.flatMap(x=>x.resolutions)){const rows=byConcept.get(r.normalizedConceptLabel)??[];rows.push(r);byConcept.set(r.normalizedConceptLabel,rows);}for(const [label,rows] of byConcept){const entities=new Set(rows.map(r=>r.canonicalEntityId).filter(Boolean));const roles=new Set(rows.map(r=>r.proposedMappingRole).filter(Boolean));if(entities.size>1||roles.size>1)findings.push({findingId:deterministicUuid(`cross|${label}`),normalizedConceptLabel:label,cardVersionIds:[...new Set(rows.map(r=>r.canonicalCardVersionId))].sort(),reasonCodes:[entities.size>1?"inconsistent_entity":"inconsistent_role"]});}return findings.sort((a,b)=>String(a.findingId).localeCompare(String(b.findingId)));}
export function authorizeModel(mode:ContentProcessingMode,externalAuthorized:boolean):void{if(mode==="approved_external_model"&&!externalAuthorized)throw new Error("external_model_processing_not_authorized");}
export function validateModelSemanticResult(value:unknown):void{if(!value||typeof value!=="object")throw new Error("invalid_model_output");const r=value as Record<string,unknown>;if(r.contractVersion!==SEMANTIC_CONTRACT_VERSION||!Array.isArray(r.concepts)||!Array.isArray(r.resolutions))throw new Error("invalid_model_output");assertDurableSemanticSafe(value);}
export function calibrationSample<T extends {queue:string;riskTier:string;canonicalCardId:string;priorityScore:number;reasonCodes:string[]}>(rows:T[],limitA=5,limitB=8,limitNoMapping=8):T[]{const mandatory=rows.filter(r=>["clinical_exception","missing_entity","missing_alias","cross_card_conflict","card_improvement","duplicate_card","stale_version"].includes(r.queue)||r.reasonCodes.some(x=>/ambigu|critic/.test(x)));const take=(predicate:(r:T)=>boolean,n:number)=>rows.filter(predicate).sort((a,b)=>b.priorityScore-a.priorityScore||a.canonicalCardId.localeCompare(b.canonicalCardId)).slice(0,n);return [...new Map([...mandatory,...take(r=>r.riskTier==="A",limitA),...take(r=>r.riskTier==="B"&&r.queue!=="no_mapping_confirm",limitB),...take(r=>r.queue==="no_mapping_confirm",limitNoMapping)].map(r=>[r.canonicalCardId,r])).values()].sort((a,b)=>b.priorityScore-a.priorityScore||a.canonicalCardId.localeCompare(b.canonicalCardId));}

export class FixtureContentLoader{private readonly cards:EphemeralCard[];constructor(cards:EphemeralCard[]){this.cards=cards;}async load(expected:{cardId:string;versionId:string;contentHash:string}):Promise<EphemeralCard>{const card=this.cards.find(c=>c.canonicalCardId===expected.cardId);if(!card)throw new Error("card_not_found");validateEphemeralCard(card,expected);return structuredClone(card);}}
