import assert from "node:assert/strict";
// @ts-expect-error Direct Node test imports TypeScript source files.
import * as s from "./deck-semantic-mapping.ts";
const id=(d:string)=>`${d.repeat(8)}-${d.repeat(4)}-4${d.repeat(3)}-8${d.repeat(3)}-${d.repeat(12)}`;
const fields=[{name:"Front",rawValue:"<style>.x{color:red}</style><b>Achilles tendon</b> is tested {{FrontSide}}",plainText:"Achilles tendon is tested"},{name:"Back",rawValue:"[sound:x.mp3] No talus fracture",plainText:"No talus fracture"}];const seed={fields,tags:["foot"],cardOrdinal:0};const card={canonicalCardId:id("1"),canonicalCardVersionId:id("2"),contentHash:s.canonicalContentHash(seed),...seed};
const entities=[{id:id("3"),preferredLabel:"Achilles tendon",normalizedLabel:"achilles tendon",entityType:"anatomy_structure",aliases:["calcaneal tendon"],sourceAliases:[],active:true,lifecycleStatus:"canonical"},{id:id("4"),preferredLabel:"Talus fracture",normalizedLabel:"talus fracture",entityType:"condition",aliases:[],sourceAliases:[],active:true,lifecycleStatus:"canonical"}];
const loader=new s.FixtureContentLoader([card]);const loaded=await loader.load({cardId:id("1"),versionId:id("2"),contentHash:card.contentHash});assert.equal(loaded.fields.length,2);assert.match(s.stripNonClinicalMarkup(fields[0].rawValue),/Achilles tendon/);assert.doesNotMatch(s.stripNonClinicalMarkup(fields[0].rawValue),/color|FrontSide/);
await assert.rejects(()=>loader.load({cardId:id("1"),versionId:id("9"),contentHash:card.contentHash}),/version_mismatch/);await assert.rejects(()=>loader.load({cardId:id("1"),versionId:id("2"),contentHash:"a".repeat(64)}),/hash_mismatch/);
const concepts=s.extractConcepts(card,entities);assert.equal(concepts.length,2);assert.equal(concepts.some(c=>c.conceptRole==="negated"&&c.normalizedConceptLabel==="talus fracture"),true);const result=s.runSemanticCard(card,entities);assert.equal(result.resolutions.some(r=>r.canonicalEntityId===id("3")&&r.disposition==="selected"),true);assert.equal(result.resolutions.some(r=>r.normalizedConceptLabel==="talus fracture"&&r.disposition==="rejected"),true);assert.equal(result.critics.some(r=>r.reviewerType==="negation_distractor_critic"&&r.decision==="oppose"),true);assert.equal(new Set(result.critics.map(r=>r.reviewerType)).size,5);
const achilles=concepts.find(c=>c.normalizedConceptLabel==="achilles tendon")!;const collision=[...entities,{...entities[0],id:id("5"),preferredLabel:"Achilles tendon concept"}];assert.equal(s.retrieveEntityCandidates(achilles,collision).length,2);assert.equal(s.resolveConcept(achilles,collision).disposition,"deferred");assert.equal(s.retrieveEntityCandidates(achilles,[{...entities[0],active:false,lifecycleStatus:"replaced"}]).length,1);assert.notEqual(s.resolveConcept(achilles,[{...entities[0],active:false,lifecycleStatus:"replaced"}]).disposition,"selected");
assert.throws(()=>s.assertDurableSemanticSafe({rawHtml:"<b>body</b>"}),/unsafe_durable/);assert.throws(()=>s.assertDurableSemanticSafe({concept:"x".repeat(501)}),/unbounded/);assert.doesNotThrow(()=>s.assertDurableSemanticSafe({normalizedConceptLabel:"achilles tendon",evidenceHash:"a".repeat(64)}));assert.throws(()=>s.authorizeModel("approved_external_model",false),/not_authorized/);assert.doesNotThrow(()=>s.authorizeModel("local_only",false));assert.throws(()=>s.validateModelSemanticResult({contractVersion:"bad",concepts:[],resolutions:[]}),/invalid_model_output/);
const replay={contractVersion:s.SEMANTIC_CONTRACT_VERSION,concepts:result.concepts,resolutions:result.resolutions};assert.doesNotThrow(()=>s.validateModelSemanticResult(replay));assert.equal(s.hash(replay),s.hash(structuredClone(replay)));
const cross=s.crossCardFindings([result,{...result,resolutions:result.resolutions.map(r=>r.canonicalEntityId?{...r,canonicalEntityId:id("6")}:r)}]);assert.ok(cross.length>0);
const rows=[{queue:"clinical_exception",riskTier:"C",canonicalCardId:id("1"),priorityScore:90,reasonCodes:["critic_opposition"]},{queue:"rapid_human_review",riskTier:"A",canonicalCardId:id("2"),priorityScore:50,reasonCodes:[]},{queue:"no_mapping_confirm",riskTier:"B",canonicalCardId:id("3"),priorityScore:30,reasonCodes:[]}];assert.deepEqual(s.calibrationSample(rows),s.calibrationSample([...rows].reverse()));
console.log("deck-semantic-mapping.test.ts: all assertions passed");
