import { createHash } from "node:crypto";
// @ts-expect-error Direct Node tooling imports TypeScript source files.
import { containsUnsafeMetadata, deterministicUuid, type PublishedDeckManifestV1, type VersionMappingCandidate } from "./deck-foundation.ts";

export const FACTORY_CONTRACT_VERSION = "snaportho-anki-kg-factory.v1" as const;
export const STAGE_RESULT_CONTRACT_VERSION = "snaportho-anki-kg-stage-result.v1" as const;
export const MACHINE_REVIEW_CONTRACT_VERSION = "snaportho-anki-kg-machine-review.v1" as const;
export const HUMAN_REVIEW_CONTRACT_VERSION = "snaportho-anki-kg-human-review.v1" as const;
export const FACTORY_IMPLEMENTATION_VERSION = "2026-07-20.1" as const;
export const RULES_VERSION = "anki-kg-factory-rules.2026-07-20.1" as const;
export const PROMPT_VERSION = "none-deterministic" as const;

export const FACTORY_STAGES = ["identity_validation","card_quality_analysis","deterministic_mapping","concept_extraction","entity_resolution","clinical_critic","coverage_critic","cross_card_consistency","machine_consensus","risk_classification","queue_routing","human_review_pending","publication_validation","completed","failed"] as const;
export type FactoryStage = typeof FACTORY_STAGES[number];
export const CONCEPT_ROLES = ["central_teaching","supporting_context","comparison","differential","prerequisite","incidental_mention","distractor","negated"] as const;
export const CONSENSUS_OUTCOMES = ["strong_support","qualified_support","disputed","insufficient_evidence","no_mapping_supported","kg_gap","alias_gap","card_improvement_required"] as const;
export type ConsensusOutcome = typeof CONSENSUS_OUTCOMES[number];
export const QUEUES = ["rapid_human_review","individual_human_review","clinical_exception","missing_alias","missing_entity","card_improvement","duplicate_card","stale_version","cross_card_conflict","publication_candidate","no_mapping_confirm"] as const;
export type FactoryQueue = typeof QUEUES[number];
export type RiskTier = "A"|"B"|"C"|"D";
export type TerminalRoute = Exclude<FactoryQueue,"publication_candidate">;

export type FactoryPins = { deckReleaseId:string; kgSnapshot:string; aliasSnapshot:string; inputManifestChecksum:string; configurationChecksum:string; rulesVersion:string; promptVersion:string; providerId:string|null; modelId:string|null };
export type StageResult<T=Record<string,unknown>> = { contractVersion:typeof STAGE_RESULT_CONTRACT_VERSION; factoryRunId:string; batchId:string; canonicalCardId:string; canonicalCardVersionId:string; stage:FactoryStage; stageImplementationVersion:string; inputChecksum:string; outputChecksum:string; status:"completed"|"failed"|"skipped"; result:T; warnings:string[]; failureCodes:string[]; startedAt:string; completedAt:string; retryCount:number };
export type MachineReview = { contractVersion:typeof MACHINE_REVIEW_CONTRACT_VERSION; factoryRunId:string; batchId:string; canonicalCardId:string; canonicalCardVersionId:string; canonicalEntityId:string|null; reviewerType:string; reviewerVersion:string; decision:"support"|"oppose"|"uncertain"; confidence:number; reasonCodes:string[]; competingEntityIds:string[]; evidenceHashes:string[] };
export type QueueItem = { queueItemId:string; factoryRunId:string; batchId:string; canonicalCardId:string; canonicalCardVersionId:string; canonicalEntityId:string|null; queue:FactoryQueue; terminal:boolean; riskTier:RiskTier; priorityScore:number; reasonCodes:string[]; evidenceHashes:string[]; machineConsensus:ConsensusOutcome; requiredHumanAction:string; lifecycleStatus:"pending_human_review" };
export type HumanReviewBlank = { contractVersion:typeof HUMAN_REVIEW_CONTRACT_VERSION; canonicalCardId:string; canonicalCardVersionId:string; canonicalEntityId:string; reviewerIdentity:""; reviewerQualification:""; decision:""; confidence:""; mappingRole:""; noMappingClassification:""; reviewedAt:""; provenanceMethod:""; ambiguityResolution:""; reasonCodes:""; safeNotes:"" };

export interface ModelAdapter { readonly mode:"fixture"|"replay"|"live"; readonly providerId:string; readonly modelId:string; readonly promptVersion:string; review(input:{cardVersionId:string;candidate:VersionMappingCandidate|null}):Promise<Omit<MachineReview,"contractVersion"|"factoryRunId"|"batchId"|"canonicalCardId"|"canonicalCardVersionId"|"canonicalEntityId">>; }
export class FixtureModelAdapter implements ModelAdapter { readonly mode="fixture" as const; readonly providerId="fixture"; readonly modelId="fixture-v1"; readonly promptVersion="fixture-prompt-v1"; async review(){ return {reviewerType:"fixture_clinical_critic",reviewerVersion:"v1",decision:"uncertain" as const,confidence:0.5,reasonCodes:["fixture_only_not_calibration_evidence"],competingEntityIds:[],evidenceHashes:[]}; } }

export type FactoryRunOutput = { runManifest:Record<string,unknown>; batchManifest:Record<string,unknown>; assignments:Array<Record<string,unknown>>; stageResults:StageResult[]; deterministicCandidates:VersionMappingCandidate[]; extractedConcepts:Array<Record<string,unknown>>; entityResolutionCandidates:Array<Record<string,unknown>>; criticFindings:Array<Record<string,unknown>>; coverageFindings:Array<Record<string,unknown>>; consistencyFindings:Array<Record<string,unknown>>; machineReviews:MachineReview[]; consensusDecisions:Array<Record<string,unknown>>; riskClassifications:Array<Record<string,unknown>>; queueItems:QueueItem[]; humanReviewPacket:HumanReviewBlank[]; kgAliasBacklog:Array<Record<string,unknown>>; deckImprovementBacklog:Array<Record<string,unknown>>; publicationReadinessPreview:Record<string,unknown>; metrics:Record<string,unknown> };

export function stableJson(value:unknown):string { const visit=(v:unknown):unknown=>Array.isArray(v)?v.map(visit):v&&typeof v==="object"?Object.fromEntries(Object.entries(v as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,visit(x)])):v; return JSON.stringify(visit(value)); }
export function checksum(value:unknown):string { return createHash("sha256").update(stableJson(value)).digest("hex"); }
export function validateStageResult(value:unknown):string[]{ const errors:string[]=[]; if(!value||typeof value!=="object")return["stage_result_not_object"]; const r=value as Record<string,unknown>; if(r.contractVersion!==STAGE_RESULT_CONTRACT_VERSION)errors.push("unknown_contract_version"); if(!FACTORY_STAGES.includes(r.stage as FactoryStage))errors.push("invalid_stage"); if(typeof r.inputChecksum!=="string"||!/^[a-f0-9]{64}$/.test(r.inputChecksum))errors.push("invalid_input_checksum"); if(typeof r.outputChecksum!=="string"||!/^[a-f0-9]{64}$/.test(r.outputChecksum))errors.push("invalid_output_checksum"); if(r.outputChecksum!==checksum(r.result))errors.push("output_checksum_mismatch"); if(containsUnsafeMetadata(r.result))errors.push("unsafe_result_metadata"); return errors; }
export function validateConceptRole(role:string):boolean{return (CONCEPT_ROLES as readonly string[]).includes(role);}
export function assertBlankHumanReview(rows:HumanReviewBlank[]):void { for(const row of rows) for(const key of ["reviewerIdentity","reviewerQualification","decision","confidence","mappingRole","noMappingClassification","reviewedAt","provenanceMethod","ambiguityResolution","reasonCodes","safeNotes"] as const) if(row[key]!=="")throw new Error(`machine_populated_human_field:${key}`); }

const EXECUTED_STAGES=FACTORY_STAGES.filter((s)=>s!=="failed");
export function runFactory(input:{manifest:PublishedDeckManifestV1;candidates:VersionMappingCandidate[];kgSnapshot:string;aliasSnapshot:string;cohortName:string;expectedCardCount?:number;stageSelection?:FactoryStage[];resumeResults?:StageResult[];retryFailed?:boolean;now?:string;adapter?:ModelAdapter}):FactoryRunOutput{
  if(input.manifest.releaseStatus!=="draft")throw new Error("calibration_requires_draft_manifest");
  if(input.expectedCardCount!==undefined&&input.manifest.cards.length!==input.expectedCardCount)throw new Error("unexpected_cohort_card_count");
  if(!input.kgSnapshot||!input.aliasSnapshot)throw new Error("kg_or_alias_snapshot_unavailable");
  if(containsUnsafeMetadata(input.manifest.metadata))throw new Error("unsafe_input_metadata");
  const selected=input.stageSelection??[...EXECUTED_STAGES]; const missing=EXECUTED_STAGES.filter((s)=>!selected.includes(s));
  if(missing.length)throw new Error(`required_stage_skipped:${missing.join(",")}`);
  const cards=[...input.manifest.cards].sort((a,b)=>a.orderingKey.localeCompare(b.orderingKey));
  const versions=new Map(cards.map(c=>[c.canonicalCardId,c.canonicalCardVersionId]));
  for(const candidate of input.candidates)if(versions.get(candidate.canonicalCardId)!==candidate.canonicalCardVersionId)throw new Error(`stale_candidate_version:${candidate.candidateId}`);
  const candidateByCard=new Map<string,VersionMappingCandidate[]>(); for(const c of input.candidates){const rows=candidateByCard.get(c.canonicalCardId)??[];rows.push(c);candidateByCard.set(c.canonicalCardId,rows);}
  const config={factoryContractVersion:FACTORY_CONTRACT_VERSION,implementationVersion:FACTORY_IMPLEMENTATION_VERSION,rulesVersion:RULES_VERSION,promptVersion:input.adapter?.promptVersion??PROMPT_VERSION,mode:input.adapter?.mode??"deterministic",cohortName:input.cohortName};
  const configurationChecksum=checksum(config), runId=deterministicUuid(`${input.manifest.manifestChecksum}|${input.kgSnapshot}|${input.aliasSnapshot}|${configurationChecksum}`), batchId=deterministicUuid(`${runId}|${cards.map(c=>c.canonicalCardVersionId).join("|")}`), now=input.now??"1970-01-01T00:00:00.000Z";
  const stageResults:StageResult[]=[]; const prior=new Map((input.resumeResults??[]).map(r=>[`${r.canonicalCardVersionId}:${r.stage}`,r]));
  const assignments:Array<Record<string,unknown>>=[]; const reviews:MachineReview[]=[]; const consensus:Array<Record<string,unknown>>=[]; const risks:Array<Record<string,unknown>>=[]; const queues:QueueItem[]=[];
  for(const card of cards){
    const candidates=[...(candidateByCard.get(card.canonicalCardId)??[])].sort((a,b)=>a.candidateId.localeCompare(b.candidateId)); const ambiguous=candidates.some(c=>c.ambiguityFlags.length>0||c.competingCandidateIds.length>0); const outcome:ConsensusOutcome=candidates.length===0?"no_mapping_supported":ambiguous?"disputed":candidates.every(c=>c.confidence>=0.9)?"strong_support":"qualified_support"; const tier:RiskTier=outcome==="strong_support"?"A":outcome==="qualified_support"?"B":outcome==="disputed"?"C":"B"; const queue:TerminalRoute=outcome==="no_mapping_supported"?"no_mapping_confirm":outcome==="disputed"?"clinical_exception":tier==="A"?"rapid_human_review":"individual_human_review";
    assignments.push({canonicalCardId:card.canonicalCardId,canonicalCardVersionId:card.canonicalCardVersionId,contentHash:card.contentHash,noteGuid:card.noteGuid,cardOrdinal:card.cardOrdinal,deckReleaseId:input.manifest.releaseId,batchId,currentStage:"completed",finalDisposition:queue});
    for(const candidate of candidates)reviews.push({contractVersion:MACHINE_REVIEW_CONTRACT_VERSION,factoryRunId:runId,batchId,canonicalCardId:card.canonicalCardId,canonicalCardVersionId:card.canonicalCardVersionId,canonicalEntityId:candidate.canonicalEntityId,reviewerType:"deterministic_resolution_reviewer",reviewerVersion:RULES_VERSION,decision:ambiguous?"uncertain":"support",confidence:candidate.confidence,reasonCodes:ambiguous?["competing_candidate"]:["candidate_evidence_supported"],competingEntityIds:candidate.competingCandidateIds,evidenceHashes:candidate.evidenceHashes});
    consensus.push({canonicalCardId:card.canonicalCardId,canonicalCardVersionId:card.canonicalCardVersionId,outcome,dissentPreserved:ambiguous,publicationEligible:false}); risks.push({canonicalCardId:card.canonicalCardId,canonicalCardVersionId:card.canonicalCardVersionId,riskTier:tier,reasonCodes:[outcome]});
    queues.push({queueItemId:deterministicUuid(`${runId}|${card.canonicalCardVersionId}|${queue}`),factoryRunId:runId,batchId,canonicalCardId:card.canonicalCardId,canonicalCardVersionId:card.canonicalCardVersionId,canonicalEntityId:candidates.length===1?candidates[0].canonicalEntityId:null,queue,terminal:true,riskTier:tier,priorityScore:tier==="C"?90:tier==="A"?50:60,reasonCodes:[outcome],evidenceHashes:[...new Set(candidates.flatMap(c=>c.evidenceHashes))].sort(),machineConsensus:outcome,requiredHumanAction:queue==="no_mapping_confirm"?"classify_no_mapping":"review_machine_proposal",lifecycleStatus:"pending_human_review"});
    for(const stage of selected){const key=`${card.canonicalCardVersionId}:${stage}`, existing=prior.get(key);if(existing&&existing.status==="completed"){stageResults.push(existing);continue;}if(existing?.status==="failed"&&!input.retryFailed){stageResults.push(existing);continue;} const result={terminalRoute:queue,machineConsensus:outcome,riskTier:tier,candidateCount:candidates.length,publicationEligible:false}; const inputChecksum=checksum({previous:stageResults.at(-1)?.outputChecksum??input.manifest.manifestChecksum,cardVersionId:card.canonicalCardVersionId,stage}); stageResults.push({contractVersion:STAGE_RESULT_CONTRACT_VERSION,factoryRunId:runId,batchId,canonicalCardId:card.canonicalCardId,canonicalCardVersionId:card.canonicalCardVersionId,stage,stageImplementationVersion:FACTORY_IMPLEMENTATION_VERSION,inputChecksum,outputChecksum:checksum(result),status:"completed",result,warnings:[],failureCodes:[],startedAt:now,completedAt:now,retryCount:existing?.status==="failed"?existing.retryCount+1:0});}
  }
  const human:HumanReviewBlank[]=input.candidates.map(c=>({contractVersion:HUMAN_REVIEW_CONTRACT_VERSION,canonicalCardId:c.canonicalCardId,canonicalCardVersionId:c.canonicalCardVersionId,canonicalEntityId:c.canonicalEntityId,reviewerIdentity:"",reviewerQualification:"",decision:"",confidence:"",mappingRole:"",noMappingClassification:"",reviewedAt:"",provenanceMethod:"",ambiguityResolution:"",reasonCodes:"",safeNotes:""}));assertBlankHumanReview(human);
  if(new Set(queues.map(q=>q.canonicalCardId)).size!==cards.length||queues.length!==cards.length)throw new Error("incomplete_terminal_card_accounting");
  const routeCounts=Object.fromEntries(QUEUES.map(q=>[q,queues.filter(x=>x.queue===q).length])); const tierCounts=Object.fromEntries(["A","B","C","D"].map(t=>[t,risks.filter(r=>r.riskTier===t).length]));
  const ambiguousCardCount=cards.filter(c=>(candidateByCard.get(c.canonicalCardId)??[]).some(x=>x.ambiguityFlags.length||x.competingCandidateIds.length)).length;
  const metrics={cardsProcessed:cards.length,proposedMappedCards:candidateByCard.size,proposedNoMappingCards:cards.length-candidateByCard.size,proposedLinks:input.candidates.length,linksByEntityType:{unknown_without_persisted_entity_snapshot:input.candidates.length},linksByMappingRole:Object.fromEntries([...new Set(input.candidates.map(c=>c.proposedMappingRole))].sort().map(role=>[role,input.candidates.filter(c=>c.proposedMappingRole===role).length])),deterministicOnlyCandidates:input.candidates.length,modelAssistedCandidates:0,deterministicModelAgreement:null,criticOppositionRate:0,machineReviewAgreement:ambiguousCardCount===0?1:(cards.length-ambiguousCardCount)/cards.length,ambiguityRate:ambiguousCardCount/cards.length,multiConceptRate:cards.filter(c=>(candidateByCard.get(c.canonicalCardId)??[]).length>1).length/cards.length,riskTierDistribution:tierCounts,missingAliasCount:0,potentialMissingEntityCount:0,cardImprovementCount:0,duplicateCardCount:0,staleVersionCount:0,crossCardConflicts:0,estimatedHumanReviewVolume:cards.length,rapidReviewVolume:routeCounts.rapid_human_review,individualReviewVolume:routeCounts.individual_human_review,unresolvedCards:routeCounts.clinical_exception,reproducibilityChecksumStatus:"verified",terminalRouteDistribution:routeCounts,publicationEligibleMappings:0,stageCompletionRate:1,stageFailureRate:0,labels:["unreviewed_machine_proposals"]};
  const runManifest={contractVersion:FACTORY_CONTRACT_VERSION,factoryRunId:runId,status:"completed",dryRun:true,pins:{deckReleaseId:input.manifest.releaseId,kgSnapshot:input.kgSnapshot,aliasSnapshot:input.aliasSnapshot,inputManifestChecksum:input.manifest.manifestChecksum,configurationChecksum,rulesVersion:RULES_VERSION,promptVersion:config.promptVersion,providerId:input.adapter?.providerId??null,modelId:input.adapter?.modelId??null},startedAt:now,completedAt:now,parentRunId:null,retryOfRunId:null}; const batchManifest={factoryRunId:runId,batchId,cohortName:input.cohortName,orderedCardVersions:cards.map(c=>c.canonicalCardVersionId),batchChecksum:checksum(cards.map(c=>[c.canonicalCardId,c.canonicalCardVersionId,c.contentHash])),stageStatus:"completed",retryCount:0,reviewerPrioritySummary:routeCounts};
  return {runManifest,batchManifest,assignments,stageResults,deterministicCandidates:[...input.candidates],extractedConcepts:[],entityResolutionCandidates:input.candidates.map(c=>({...c,reviewState:"unreviewed_machine_proposal"})),criticFindings:reviews.filter(r=>r.decision!=="support"),coverageFindings:queues.filter(q=>q.queue==="no_mapping_confirm").map(q=>({canonicalCardId:q.canonicalCardId,finding:"legitimate_no_mapping_requires_human_confirmation"})),consistencyFindings:[],machineReviews:reviews,consensusDecisions:consensus,riskClassifications:risks,queueItems:queues,humanReviewPacket:human,kgAliasBacklog:[],deckImprovementBacklog:[],publicationReadinessPreview:{ready:false,recommendation:"DO_NOT_PUBLISH",reasonCodes:["direct_human_review_missing","draft_release","machine_consensus_is_insufficient"],eligibleMappingCount:0},metrics};
}
