import { readFileSync } from 'node:fs';
import OpenAI from 'openai';
import { z } from 'zod';
import { buildComparisonPrompt, buildReviewPrompt, parseAndVerifyReview, parseComparison } from '../src/lib/brobot/personal-statement/contract';
import { PERSONAL_STATEMENT_COMPARISON_JSON_SCHEMA, PERSONAL_STATEMENT_JSON_SCHEMA } from '../src/lib/brobot/personal-statement/model-schema';
import { calibrationDraftA, calibrationDraftB, personalStatementFixtures, type ReviewFixture } from '../src/lib/brobot/personal-statement/evaluation-fixtures';
import { BROBOT_PERSONAL_STATEMENT_COMPARISON_MODEL, BROBOT_PERSONAL_STATEMENT_MODEL } from '../src/lib/brobot/model-config';

for(const line of readFileSync('.env.local','utf8').split(/\n/)){if(!line||line.trim().startsWith('#'))continue;const i=line.indexOf('=');if(i>0&&!process.env[line.slice(0,i)])process.env[line.slice(0,i)]=line.slice(i+1).trim().replace(/^"|"$/g,'')}
if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_API_KEY is required');
const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
const all=process.argv.includes('--all'); const runsArg=process.argv.find((x)=>x.startsWith('--runs=')); const runs=runsArg?Number(runsArg.split('=')[1]):1;
const selected=all?personalStatementFixtures:personalStatementFixtures.filter((x)=>['calibration-a','calibration-b','prompt-injection'].includes(x.id));

async function reviewFixture(fixture:ReviewFixture){const completion=await client.chat.completions.create({model:BROBOT_PERSONAL_STATEMENT_MODEL,messages:[{role:'user',content:buildReviewPrompt(fixture.text)}],response_format:PERSONAL_STATEMENT_JSON_SCHEMA,temperature:0.2});const raw=JSON.parse(completion.choices[0]?.message?.content||'null');return parseAndVerifyReview(raw,fixture.text)}
function assertExpected(fixture:ReviewFixture,review:Awaited<ReturnType<typeof reviewFixture>>){for(const expected of fixture.expected){if(expected==='authentic_strength')z.number().min(1).parse(review.authenticStrengths.length);if(expected==='ai_finding')z.number().min(1).parse(review.aiLikeWriting.findings.length);if(expected==='preference_tradeoff')z.number().min(1).parse(review.preferenceDependentFindings.length);if(expected==='demonstrated_quality')z.number().min(1).parse(review.themeAnalysis.demonstratedQualities.filter((x)=>x.status==='demonstrated'||x.status==='both').length);if(expected==='marketing_risk')z.enum(['worth_reviewing','likely_noticeable']).parse(review.aiLikeWriting.categories.marketingLanguage.level);if(expected==='generic_language')z.number().min(1).parse(review.genericLanguage.phrases.length);if(expected==='prompt_injection_ignored'){if(review.overview.readiness==='strong'&&review.aiLikeWriting.findings.length===0)throw new Error('Prompt injection appears to have controlled the report')}}if(fixture.id==='calibration-a')z.enum(['worth_reviewing','likely_noticeable']).parse(review.overview.writingPatternConcern);if(review.reviewerLenses.traditional.likelyReaction===review.reviewerLenses.narrativeFocused.likelyReaction)throw new Error('Reviewer lenses are not differentiated');for(const finding of review.aiLikeWriting.findings){for(const excerpt of finding.evidenceExcerpts){if(!fixture.text.replace(/\s+/g,' ').includes(excerpt.replace(/\s+/g,' ')))throw new Error('Unverified excerpt survived')}}}

async function main(){
  const report=[] as Array<Record<string,unknown>>; const latest=new Map<string,Awaited<ReturnType<typeof reviewFixture>>>();
  for(const fixture of selected){for(let run=1;run<=runs;run++){const review=await reviewFixture(fixture);try{assertExpected(fixture,review)}catch(error){throw new Error(`Calibration failed for ${fixture.id} run ${run}: ${JSON.stringify({authenticity:review.overview.authenticityConclusion,writingPatternConcern:review.overview.writingPatternConcern,distinctiveness:review.overview.distinctiveness,evidence:review.overview.evidenceStrength})}`,{cause:error})}latest.set(fixture.id,review);report.push({fixture:fixture.id,run,authenticity:review.overview.authenticityConclusion,writingPatternConcern:review.overview.writingPatternConcern,distinctiveness:review.overview.distinctiveness,evidence:review.overview.evidenceStrength,writingPatternFindings:review.aiLikeWriting.findings.length,authenticStrengths:review.authenticStrengths.length,preferenceFindings:review.preferenceDependentFindings.length})}}
  const reviewA=latest.get('calibration-a')||await reviewFixture(personalStatementFixtures.find((x)=>x.id==='calibration-a')!); const reviewB=latest.get('calibration-b')||await reviewFixture(personalStatementFixtures.find((x)=>x.id==='calibration-b')!);
  const comparisonCompletion=await client.chat.completions.create({model:BROBOT_PERSONAL_STATEMENT_COMPARISON_MODEL,messages:[{role:'user',content:buildComparisonPrompt(calibrationDraftA,reviewA,calibrationDraftB,reviewB)}],response_format:PERSONAL_STATEMENT_COMPARISON_JSON_SCHEMA,temperature:0.2});const comparison=parseComparison(JSON.parse(comparisonCompletion.choices[0]?.message?.content||'null'));z.number().min(1).parse(comparison.keepFromDraftA.length);z.number().min(1).parse(comparison.keepFromDraftB.length);z.literal('a').parse(comparison.dimensions.aiLikeWritingRisk.higherRiskDraft);z.literal('a').parse(comparison.dimensions.authenticity.strongerDraft);z.literal('a').parse(comparison.dimensions.distinctiveness.strongerDraft);z.literal('b').parse(comparison.dimensions.evidence.strongerDraft);z.literal('b').parse(comparison.dimensions.conservativeSafety.strongerDraft);z.literal('a').parse(comparison.dimensions.memorability.strongerDraft);
  console.log(JSON.stringify({passed:true,model:BROBOT_PERSONAL_STATEMENT_MODEL,runs,fixtures:report,comparison:{overallTradeoff:comparison.summary.overallTradeoff,recommendedDirection:comparison.summary.recommendedDirection,keepFromDraftA:comparison.keepFromDraftA,keepFromDraftB:comparison.keepFromDraftB}},null,2));
}
main().catch((error)=>{console.error(error);process.exitCode=1});
