import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
const root=path.resolve(import.meta.dirname,"../../..");
const migration=readFileSync(path.join(root,"supabase/migrations/20260726_160000_extension_anki_search_relay.sql"),"utf8");
const submit=readFileSync(path.join(root,"src/app/api/brobot/extension/anki-search/route.ts"),"utf8");
const pending=readFileSync(path.join(root,"src/app/api/anki/search-requests/pending/route.ts"),"utf8");
const claim=readFileSync(path.join(root,"src/app/api/anki/search-requests/[id]/claim/route.ts"),"utf8");
const complete=readFileSync(path.join(root,"src/app/api/anki/search-requests/[id]/complete/route.ts"),"utf8");
const tutorPanel=readFileSync(path.join(root,"extensions/orthobullets-brobot/src/sidepanel/question-tutor-panel.ts"),"utf8");
const sidepanelApp=readFileSync(path.join(root,"extensions/orthobullets-brobot/src/sidepanel/App.ts"),"utf8");
const queryKinds=readFileSync(path.join(root,"supabase/migrations/20260726_200000_anki_search_query_kinds.sql"),"utf8");
for(const pattern of [/force row level security/,/question_fingerprint_hash/,/normalized_native_id/,/claim_expires_at/,/educational_metadata_is_safe/,/open_browse_and_return_results/])assert.match(migration,pattern);
assert.doesNotMatch(migration,/\b(stem|answer_choices|raw_html|explanation_text)\b/i);
assert.match(submit,/normalize/);assert.match(submit,/idempotency_key/);
assert.match(submit,/anki_search_relay_unavailable/);
assert.match(submit,/PGRST205/);
assert.match(pending,/\.eq\("user_id",auth\.userId\)/);
assert.match(claim,/claimed_by_device_token_id/);
assert.match(complete,/claimed_by_device_token_id/);
assert.match(complete,/latest_deck_concept/);
for(const pattern of[/query_kind/,/topic_page/,/page_sections/,/page_sections_match_kind/])assert.match(queryKinds,pattern);
assert.match(submit,/query_kind: input\.source\.queryKind/);
assert.match(submit,/page_sections: input\.concept\.pageSections/);
for(const source of[submit,pending,claim,complete])assert.doesNotMatch(source,/console\.(log|error)/);
assert.match(tutorPanel,/id="qt-send-to-anki"/);
assert.match(tutorPanel,/id="qt-send-to-anki-before-explain"/);
assert.match(tutorPanel,/view\.session\?\.explanation/);
assert.match(tutorPanel,/onSendToAnki\(button, questionExplanation\)/);
assert.match(sidepanelApp,/onSendToAnki: \(button, explanation\) => void sendQuestionToAnki\(button, explanation\)/);
console.log("extension-anki-search-relay.test.ts: all assertions passed");
