/**
 * Hand & Wrist Prepare Curriculum Cluster — neighborhood manufacturing seeds.
 * Organized by clinical conditions residents prepare for, not individual operations.
 */

export type HandWristCategory =
  | "distal-radius-wrist-trauma"
  | "carpal-trauma"
  | "metacarpal-trauma"
  | "phalangeal-trauma"
  | "tendons-nerves"
  | "ligament-soft-tissue"
  | "infection-emergency";

export type HandWristNeighborhoodDef = {
  topicKey: string;
  displayName: string;
  category: HandWristCategory;
  categoryLabel: string;
  curriculumNodeSlug: string;
  prepareTopicId: string;
  casePrepSlug?: string;
  clinicalKind: string;
  primaryAnatomySlugs: string[];
  relatedTopicKeys: string[];
  crossClusterRefs?: string[];
  ankiCardMappings: number;
  orthobulletsQuestionMappings: number;
  isSharedAnatomyOwner?: boolean;
  extraEntityKinds?: Array<"classification" | "imaging" | "procedure" | "complication" | "treatment_principle">;
};

export const HAND_WRIST_CLUSTER_KEY = "hand-wrist" as const;

export const HAND_WRIST_NEIGHBORHOODS: HandWristNeighborhoodDef[] = [
  // Distal Radius & Wrist Trauma
  {
    topicKey: "distal-radius-fracture",
    displayName: "Distal Radius Fracture",
    category: "distal-radius-wrist-trauma",
    categoryLabel: "Distal Radius & Wrist Trauma",
    curriculumNodeSlug: "trauma-distal-radius-fractures",
    prepareTopicId: "distal-radius-fracture",
    casePrepSlug: "distal-radius-orif",
    clinicalKind: "fracture",
    primaryAnatomySlugs: ["distal-radius", "druj", "median-nerve", "tfcc"],
    relatedTopicKeys: ["druj-instability", "galeazzi-fracture", "essex-lopresti-injury", "carpal-instability"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 41,
    isSharedAnatomyOwner: true,
    extraEntityKinds: ["classification", "imaging", "procedure", "complication"],
  },
  {
    topicKey: "distal-ulna-fracture",
    displayName: "Distal Ulna Fracture",
    category: "distal-radius-wrist-trauma",
    categoryLabel: "Distal Radius & Wrist Trauma",
    curriculumNodeSlug: "hand-distal-ulna-fracture",
    prepareTopicId: "distal-ulna-fracture",
    clinicalKind: "fracture",
    primaryAnatomySlugs: ["distal-ulna", "druj", "tfcc"],
    relatedTopicKeys: ["distal-radius-fracture", "druj-instability", "ulnar-styloid-fracture"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 12,
    extraEntityKinds: ["imaging", "procedure"],
  },
  {
    topicKey: "ulnar-styloid-fracture",
    displayName: "Ulnar Styloid Fracture",
    category: "distal-radius-wrist-trauma",
    categoryLabel: "Distal Radius & Wrist Trauma",
    curriculumNodeSlug: "hand-ulnar-styloid-fracture",
    prepareTopicId: "ulnar-styloid-fracture",
    clinicalKind: "fracture",
    primaryAnatomySlugs: ["distal-ulna", "tfcc", "druj"],
    relatedTopicKeys: ["distal-radius-fracture", "druj-instability", "tfcc-injury"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 8,
    extraEntityKinds: ["imaging"],
  },
  {
    topicKey: "druj-instability",
    displayName: "DRUJ Instability",
    category: "distal-radius-wrist-trauma",
    categoryLabel: "Distal Radius & Wrist Trauma",
    curriculumNodeSlug: "hand-druj-instability",
    prepareTopicId: "druj-instability",
    clinicalKind: "instability",
    primaryAnatomySlugs: ["druj", "tfcc", "distal-ulna", "distal-radius"],
    relatedTopicKeys: ["distal-radius-fracture", "galeazzi-fracture", "essex-lopresti-injury", "tfcc-injury"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 18,
    extraEntityKinds: ["classification", "procedure"],
  },
  {
    topicKey: "galeazzi-fracture",
    displayName: "Galeazzi Fracture",
    category: "distal-radius-wrist-trauma",
    categoryLabel: "Distal Radius & Wrist Trauma",
    curriculumNodeSlug: "hand-galeazzi-fracture",
    prepareTopicId: "galeazzi-fracture",
    clinicalKind: "fracture_dislocation",
    primaryAnatomySlugs: ["distal-radius", "druj", "ulna"],
    relatedTopicKeys: ["distal-radius-fracture", "druj-instability", "essex-lopresti-injury"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 14,
    extraEntityKinds: ["imaging", "procedure"],
  },
  {
    topicKey: "essex-lopresti-injury",
    displayName: "Essex-Lopresti Injury",
    category: "distal-radius-wrist-trauma",
    categoryLabel: "Distal Radius & Wrist Trauma",
    curriculumNodeSlug: "hand-essex-lopresti-injury",
    prepareTopicId: "essex-lopresti-injury",
    clinicalKind: "fracture_dislocation",
    primaryAnatomySlugs: ["radius", "druj", "interosseous-membrane", "pruj"],
    relatedTopicKeys: ["galeazzi-fracture", "druj-instability", "distal-radius-fracture"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 10,
    extraEntityKinds: ["imaging", "complication"],
  },
  {
    topicKey: "wrist-dislocation",
    displayName: "Wrist Dislocation",
    category: "distal-radius-wrist-trauma",
    categoryLabel: "Distal Radius & Wrist Trauma",
    curriculumNodeSlug: "hand-wrist-dislocation",
    prepareTopicId: "wrist-dislocation",
    clinicalKind: "dislocation",
    primaryAnatomySlugs: ["lunate", "scaphoid", "capitate", "druj"],
    relatedTopicKeys: ["perilunate-dislocation", "lunate-dislocation", "carpal-instability"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 16,
    extraEntityKinds: ["classification", "procedure"],
  },
  // Carpal Trauma
  {
    topicKey: "scaphoid-fracture",
    displayName: "Scaphoid Fracture",
    category: "carpal-trauma",
    categoryLabel: "Carpal Trauma",
    curriculumNodeSlug: "hand-scaphoid-fracture",
    prepareTopicId: "scaphoid-fracture",
    casePrepSlug: "scaphoid-orif",
    clinicalKind: "fracture",
    primaryAnatomySlugs: ["scaphoid", "scapholunate-ligament", "radius"],
    relatedTopicKeys: ["scaphoid-nonunion", "perilunate-dislocation", "sl-ligament-injury", "carpal-instability"],
    ankiCardMappings: 8,
    orthobulletsQuestionMappings: 52,
    extraEntityKinds: ["classification", "imaging", "procedure", "complication"],
  },
  {
    topicKey: "scaphoid-nonunion",
    displayName: "Scaphoid Nonunion",
    category: "carpal-trauma",
    categoryLabel: "Carpal Trauma",
    curriculumNodeSlug: "hand-scaphoid-nonunion",
    prepareTopicId: "scaphoid-nonunion",
    clinicalKind: "nonunion",
    primaryAnatomySlugs: ["scaphoid", "scapholunate-ligament"],
    relatedTopicKeys: ["scaphoid-fracture", "carpal-instability", "sl-ligament-injury"],
    ankiCardMappings: 4,
    orthobulletsQuestionMappings: 22,
    extraEntityKinds: ["imaging", "procedure", "complication"],
  },
  {
    topicKey: "lunate-fracture",
    displayName: "Lunate Fracture",
    category: "carpal-trauma",
    categoryLabel: "Carpal Trauma",
    curriculumNodeSlug: "hand-lunate-fracture",
    prepareTopicId: "lunate-fracture",
    clinicalKind: "fracture",
    primaryAnatomySlugs: ["lunate", "capitate", "scapholunate-ligament"],
    relatedTopicKeys: ["perilunate-dislocation", "lunate-dislocation", "carpal-instability"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 8,
    extraEntityKinds: ["imaging"],
  },
  {
    topicKey: "perilunate-dislocation",
    displayName: "Perilunate Dislocation",
    category: "carpal-trauma",
    categoryLabel: "Carpal Trauma",
    curriculumNodeSlug: "hand-perilunate-dislocation",
    prepareTopicId: "perilunate-dislocation",
    clinicalKind: "dislocation",
    primaryAnatomySlugs: ["lunate", "capitate", "scapholunate-ligament", "lunotriquetral-ligament"],
    relatedTopicKeys: ["lunate-dislocation", "scaphoid-fracture", "sl-ligament-injury", "carpal-instability"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 28,
    extraEntityKinds: ["classification", "procedure"],
  },
  {
    topicKey: "lunate-dislocation",
    displayName: "Lunate Dislocation",
    category: "carpal-trauma",
    categoryLabel: "Carpal Trauma",
    curriculumNodeSlug: "hand-lunate-dislocation",
    prepareTopicId: "lunate-dislocation",
    clinicalKind: "dislocation",
    primaryAnatomySlugs: ["lunate", "capitate", "median-nerve"],
    relatedTopicKeys: ["perilunate-dislocation", "carpal-instability", "carpal-tunnel-syndrome"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 20,
    extraEntityKinds: ["classification", "procedure"],
  },
  {
    topicKey: "carpal-instability",
    displayName: "Carpal Instability",
    category: "carpal-trauma",
    categoryLabel: "Carpal Trauma",
    curriculumNodeSlug: "hand-carpal-instability",
    prepareTopicId: "carpal-instability",
    clinicalKind: "instability",
    primaryAnatomySlugs: ["scapholunate-ligament", "lunotriquetral-ligament", "scaphoid", "lunate"],
    relatedTopicKeys: ["sl-ligament-injury", "lt-ligament-injury", "scaphoid-nonunion", "distal-radius-fracture"],
    ankiCardMappings: 3,
    orthobulletsQuestionMappings: 24,
    extraEntityKinds: ["classification", "imaging"],
  },
  {
    topicKey: "sl-ligament-injury",
    displayName: "SL Ligament Injury",
    category: "carpal-trauma",
    categoryLabel: "Carpal Trauma",
    curriculumNodeSlug: "hand-sl-ligament-injury",
    prepareTopicId: "sl-ligament-injury",
    clinicalKind: "ligamentous_injury",
    primaryAnatomySlugs: ["scapholunate-ligament", "scaphoid", "lunate"],
    relatedTopicKeys: ["carpal-instability", "scaphoid-fracture", "perilunate-dislocation"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 16,
    extraEntityKinds: ["imaging", "procedure"],
  },
  {
    topicKey: "lt-ligament-injury",
    displayName: "LT Ligament Injury",
    category: "carpal-trauma",
    categoryLabel: "Carpal Trauma",
    curriculumNodeSlug: "hand-lt-ligament-injury",
    prepareTopicId: "lt-ligament-injury",
    clinicalKind: "ligamentous_injury",
    primaryAnatomySlugs: ["lunotriquetral-ligament", "lunate", "triquetrum", "tfcc"],
    relatedTopicKeys: ["carpal-instability", "tfcc-injury", "perilunate-dislocation"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 12,
    extraEntityKinds: ["imaging"],
  },
  // Metacarpal Trauma
  {
    topicKey: "metacarpal-fracture",
    displayName: "Metacarpal Fracture",
    category: "metacarpal-trauma",
    categoryLabel: "Metacarpal Trauma",
    curriculumNodeSlug: "hand-metacarpal-fracture",
    prepareTopicId: "metacarpal-fracture",
    clinicalKind: "fracture",
    primaryAnatomySlugs: ["second-metacarpal", "third-metacarpal", "fourth-metacarpal", "fifth-metacarpal", "mcp-joint"],
    relatedTopicKeys: ["boxer-fracture", "bennett-fracture", "rolando-fracture", "cmc-dislocations"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 32,
    extraEntityKinds: ["imaging", "treatment_principle"],
  },
  {
    topicKey: "bennett-fracture",
    displayName: "Bennett Fracture",
    category: "metacarpal-trauma",
    categoryLabel: "Metacarpal Trauma",
    curriculumNodeSlug: "hand-bennett-fracture",
    prepareTopicId: "bennett-fracture",
    clinicalKind: "fracture_dislocation",
    primaryAnatomySlugs: ["first-metacarpal", "trapezium", "cmc-joint", "apl"],
    relatedTopicKeys: ["rolando-fracture", "thumb-ucl-injury", "cmc-dislocations"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 18,
    extraEntityKinds: ["imaging", "procedure"],
  },
  {
    topicKey: "rolando-fracture",
    displayName: "Rolando Fracture",
    category: "metacarpal-trauma",
    categoryLabel: "Metacarpal Trauma",
    curriculumNodeSlug: "hand-rolando-fracture",
    prepareTopicId: "rolando-fracture",
    clinicalKind: "fracture",
    primaryAnatomySlugs: ["first-metacarpal", "trapezium", "cmc-joint"],
    relatedTopicKeys: ["bennett-fracture", "thumb-ucl-injury"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 10,
    extraEntityKinds: ["imaging", "procedure"],
  },
  {
    topicKey: "boxer-fracture",
    displayName: "Boxer Fracture",
    category: "metacarpal-trauma",
    categoryLabel: "Metacarpal Trauma",
    curriculumNodeSlug: "hand-boxer-fracture",
    prepareTopicId: "boxer-fracture",
    clinicalKind: "fracture",
    primaryAnatomySlugs: ["fifth-metacarpal", "mcp-joint"],
    relatedTopicKeys: ["metacarpal-fracture"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 14,
    extraEntityKinds: ["treatment_principle"],
  },
  {
    topicKey: "cmc-dislocations",
    displayName: "CMC Dislocations",
    category: "metacarpal-trauma",
    categoryLabel: "Metacarpal Trauma",
    curriculumNodeSlug: "hand-cmc-dislocations",
    prepareTopicId: "cmc-dislocations",
    clinicalKind: "dislocation",
    primaryAnatomySlugs: ["cmc-joint", "first-metacarpal", "trapezium"],
    relatedTopicKeys: ["bennett-fracture", "thumb-ucl-injury"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 12,
    extraEntityKinds: ["procedure"],
  },
  // Phalangeal Trauma
  {
    topicKey: "proximal-phalanx-fracture",
    displayName: "Proximal Phalanx Fracture",
    category: "phalangeal-trauma",
    categoryLabel: "Phalangeal Trauma",
    curriculumNodeSlug: "hand-proximal-phalanx-fracture",
    prepareTopicId: "proximal-phalanx-fracture",
    clinicalKind: "fracture",
    primaryAnatomySlugs: ["proximal-phalanx", "pip-joint", "mcp-joint"],
    relatedTopicKeys: ["volar-plate-injury", "central-slip-injury"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 14,
    extraEntityKinds: ["imaging", "treatment_principle"],
  },
  {
    topicKey: "middle-phalanx-fracture",
    displayName: "Middle Phalanx Fracture",
    category: "phalangeal-trauma",
    categoryLabel: "Phalangeal Trauma",
    curriculumNodeSlug: "hand-middle-phalanx-fracture",
    prepareTopicId: "middle-phalanx-fracture",
    clinicalKind: "fracture",
    primaryAnatomySlugs: ["middle-phalanx", "pip-joint", "dip-joint"],
    relatedTopicKeys: ["volar-plate-injury"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 8,
    extraEntityKinds: ["imaging"],
  },
  {
    topicKey: "distal-phalanx-fracture",
    displayName: "Distal Phalanx Fracture",
    category: "phalangeal-trauma",
    categoryLabel: "Phalangeal Trauma",
    curriculumNodeSlug: "hand-distal-phalanx-fracture",
    prepareTopicId: "distal-phalanx-fracture",
    clinicalKind: "fracture",
    primaryAnatomySlugs: ["distal-phalanx", "dip-joint"],
    relatedTopicKeys: ["mallet-finger", "fingertip-injury", "nail-bed-injury"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 10,
    extraEntityKinds: ["imaging"],
  },
  {
    topicKey: "mallet-finger",
    displayName: "Mallet Finger",
    category: "phalangeal-trauma",
    categoryLabel: "Phalangeal Trauma",
    curriculumNodeSlug: "hand-mallet-finger",
    prepareTopicId: "mallet-finger",
    clinicalKind: "tendon_injury",
    primaryAnatomySlugs: ["distal-phalanx", "dip-joint", "edc"],
    relatedTopicKeys: ["extensor-tendon-injury", "distal-phalanx-fracture"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 22,
    extraEntityKinds: ["classification", "treatment_principle"],
  },
  {
    topicKey: "jersey-finger",
    displayName: "Jersey Finger",
    category: "phalangeal-trauma",
    categoryLabel: "Phalangeal Trauma",
    curriculumNodeSlug: "hand-jersey-finger",
    prepareTopicId: "jersey-finger",
    clinicalKind: "tendon_injury",
    primaryAnatomySlugs: ["fdp", "distal-phalanx", "flexor-tendon-zones"],
    relatedTopicKeys: ["flexor-tendon-injury", "flexor-tendon-zones"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 24,
    extraEntityKinds: ["classification", "procedure"],
  },
  {
    topicKey: "central-slip-injury",
    displayName: "Central Slip Injury",
    category: "phalangeal-trauma",
    categoryLabel: "Phalangeal Trauma",
    curriculumNodeSlug: "hand-central-slip-injury",
    prepareTopicId: "central-slip-injury",
    clinicalKind: "tendon_injury",
    primaryAnatomySlugs: ["pip-joint", "edc", "middle-phalanx"],
    relatedTopicKeys: ["extensor-tendon-injury", "mallet-finger"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 14,
    extraEntityKinds: ["complication"],
  },
  {
    topicKey: "volar-plate-injury",
    displayName: "Volar Plate Injury",
    category: "phalangeal-trauma",
    categoryLabel: "Phalangeal Trauma",
    curriculumNodeSlug: "hand-volar-plate-injury",
    prepareTopicId: "volar-plate-injury",
    clinicalKind: "ligamentous_injury",
    primaryAnatomySlugs: ["volar-plate", "pip-joint", "proximal-phalanx"],
    relatedTopicKeys: ["proximal-phalanx-fracture", "middle-phalanx-fracture"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 10,
    extraEntityKinds: ["imaging"],
  },
  // Tendons & Nerves
  {
    topicKey: "flexor-tendon-injury",
    displayName: "Flexor Tendon Injury",
    category: "tendons-nerves",
    categoryLabel: "Tendons & Nerves",
    curriculumNodeSlug: "hand-flexor-tendon-injury",
    prepareTopicId: "flexor-tendon-injury",
    clinicalKind: "tendon_injury",
    primaryAnatomySlugs: ["fdp", "fds", "flexor-tendon-zones", "flexor-pulley-system"],
    relatedTopicKeys: ["flexor-tendon-zones", "jersey-finger", "flexor-tenosynovitis"],
    ankiCardMappings: 6,
    orthobulletsQuestionMappings: 38,
    extraEntityKinds: ["procedure", "complication"],
  },
  {
    topicKey: "extensor-tendon-injury",
    displayName: "Extensor Tendon Injury",
    category: "tendons-nerves",
    categoryLabel: "Tendons & Nerves",
    curriculumNodeSlug: "hand-extensor-tendon-injury",
    prepareTopicId: "extensor-tendon-injury",
    clinicalKind: "tendon_injury",
    primaryAnatomySlugs: ["edc", "epl", "extensor-tendon-zones"],
    relatedTopicKeys: ["extensor-tendon-zones", "mallet-finger", "central-slip-injury"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 26,
    extraEntityKinds: ["procedure"],
  },
  {
    topicKey: "flexor-tendon-zones",
    displayName: "Flexor Tendon Zones",
    category: "tendons-nerves",
    categoryLabel: "Tendons & Nerves",
    curriculumNodeSlug: "hand-flexor-tendon-zones",
    prepareTopicId: "flexor-tendon-zones",
    clinicalKind: "anatomic_concept",
    primaryAnatomySlugs: ["flexor-tendon-zones", "fdp", "fds", "flexor-pulley-system"],
    relatedTopicKeys: ["flexor-tendon-injury", "jersey-finger"],
    ankiCardMappings: 4,
    orthobulletsQuestionMappings: 18,
    extraEntityKinds: ["classification"],
  },
  {
    topicKey: "extensor-tendon-zones",
    displayName: "Extensor Tendon Zones",
    category: "tendons-nerves",
    categoryLabel: "Tendons & Nerves",
    curriculumNodeSlug: "hand-extensor-tendon-zones",
    prepareTopicId: "extensor-tendon-zones",
    clinicalKind: "anatomic_concept",
    primaryAnatomySlugs: ["extensor-tendon-zones", "edc", "epl"],
    relatedTopicKeys: ["extensor-tendon-injury", "mallet-finger"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 14,
    extraEntityKinds: ["classification"],
  },
  {
    topicKey: "median-nerve-compression",
    displayName: "Median Nerve Compression",
    category: "tendons-nerves",
    categoryLabel: "Tendons & Nerves",
    curriculumNodeSlug: "hand-median-nerve-compression",
    prepareTopicId: "median-nerve-compression",
    clinicalKind: "nerve_compression",
    primaryAnatomySlugs: ["median-nerve", "carpal-tunnel", "fds", "fdp"],
    relatedTopicKeys: ["carpal-tunnel-syndrome", "flexor-tendon-injury"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 20,
    extraEntityKinds: ["procedure"],
  },
  {
    topicKey: "carpal-tunnel-syndrome",
    displayName: "Carpal Tunnel Syndrome",
    category: "tendons-nerves",
    categoryLabel: "Tendons & Nerves",
    curriculumNodeSlug: "hand-carpal-tunnel-syndrome",
    prepareTopicId: "carpal-tunnel-syndrome",
    casePrepSlug: "carpal-tunnel-release",
    clinicalKind: "nerve_compression",
    primaryAnatomySlugs: ["median-nerve", "carpal-tunnel", "fpl"],
    relatedTopicKeys: ["median-nerve-compression", "trigger-finger", "distal-radius-fracture"],
    ankiCardMappings: 4,
    orthobulletsQuestionMappings: 44,
    // Named release techniques and complications are supplied by the CTS
    // manufacturing input package; generic placeholders are unsafe here.
    extraEntityKinds: [],
  },
  {
    topicKey: "cubital-tunnel-syndrome",
    displayName: "Cubital Tunnel Syndrome",
    category: "tendons-nerves",
    categoryLabel: "Tendons & Nerves",
    curriculumNodeSlug: "hand-cubital-tunnel-syndrome",
    prepareTopicId: "cubital-tunnel-syndrome",
    clinicalKind: "nerve_compression",
    primaryAnatomySlugs: ["ulnar-nerve", "fcu"],
    relatedTopicKeys: ["ulnar-nerve-compression"],
    crossClusterRefs: ["humeral-shaft-fracture"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 28,
    extraEntityKinds: ["procedure"],
  },
  {
    topicKey: "ulnar-nerve-compression",
    displayName: "Ulnar Nerve Compression",
    category: "tendons-nerves",
    categoryLabel: "Tendons & Nerves",
    curriculumNodeSlug: "hand-ulnar-nerve-compression",
    prepareTopicId: "ulnar-nerve-compression",
    clinicalKind: "nerve_compression",
    primaryAnatomySlugs: ["ulnar-nerve", "guyon-canal"],
    relatedTopicKeys: ["cubital-tunnel-syndrome", "carpal-tunnel-syndrome"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 16,
    extraEntityKinds: ["procedure"],
  },
  {
    topicKey: "radial-nerve-compression",
    displayName: "Radial Nerve Compression",
    category: "tendons-nerves",
    categoryLabel: "Tendons & Nerves",
    curriculumNodeSlug: "hand-radial-nerve-compression",
    prepareTopicId: "radial-nerve-compression",
    clinicalKind: "nerve_compression",
    primaryAnatomySlugs: ["radial-nerve", "pin"],
    relatedTopicKeys: ["de-quervain-tenosynovitis"],
    crossClusterRefs: ["humeral-shaft-fracture"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 12,
    extraEntityKinds: ["procedure"],
  },
  // Ligament & Soft Tissue
  {
    topicKey: "thumb-ucl-injury",
    displayName: "Thumb UCL Injury",
    category: "ligament-soft-tissue",
    categoryLabel: "Ligament & Soft Tissue",
    curriculumNodeSlug: "hand-thumb-ucl-injury",
    prepareTopicId: "thumb-ucl-injury",
    clinicalKind: "ligamentous_injury",
    primaryAnatomySlugs: ["thumb-ucl", "mcp-joint", "first-metacarpal"],
    relatedTopicKeys: ["gamekeeper-skier-thumb", "bennett-fracture", "cmc-dislocations"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 26,
    extraEntityKinds: ["imaging", "procedure"],
  },
  {
    topicKey: "gamekeeper-skier-thumb",
    displayName: "Gamekeeper/Skier Thumb",
    category: "ligament-soft-tissue",
    categoryLabel: "Ligament & Soft Tissue",
    curriculumNodeSlug: "hand-gamekeeper-skier-thumb",
    prepareTopicId: "gamekeeper-skier-thumb",
    clinicalKind: "ligamentous_injury",
    primaryAnatomySlugs: ["thumb-ucl", "mcp-joint"],
    relatedTopicKeys: ["thumb-ucl-injury", "bennett-fracture"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 18,
    extraEntityKinds: ["procedure"],
  },
  {
    topicKey: "tfcc-injury",
    displayName: "TFCC Injury",
    category: "ligament-soft-tissue",
    categoryLabel: "Ligament & Soft Tissue",
    curriculumNodeSlug: "hand-tfcc-injury",
    prepareTopicId: "tfcc-injury",
    clinicalKind: "ligamentous_injury",
    primaryAnatomySlugs: ["tfcc", "druj", "triquetrum", "distal-ulna"],
    relatedTopicKeys: ["druj-instability", "distal-radius-fracture", "lt-ligament-injury"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 30,
    extraEntityKinds: ["classification", "procedure"],
  },
  {
    topicKey: "dupuytren-disease",
    displayName: "Dupuytren Disease",
    category: "ligament-soft-tissue",
    categoryLabel: "Ligament & Soft Tissue",
    curriculumNodeSlug: "hand-dupuytren-disease",
    prepareTopicId: "dupuytren-disease",
    clinicalKind: "soft_tissue_disease",
    primaryAnatomySlugs: ["fds", "flexor-pulley-system"],
    relatedTopicKeys: ["trigger-finger"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 20,
    extraEntityKinds: ["classification", "procedure"],
  },
  {
    topicKey: "trigger-finger",
    displayName: "Trigger Finger",
    category: "ligament-soft-tissue",
    categoryLabel: "Ligament & Soft Tissue",
    curriculumNodeSlug: "hand-trigger-finger",
    prepareTopicId: "trigger-finger",
    clinicalKind: "tenosynovitis",
    primaryAnatomySlugs: ["fds", "a1-pulley", "flexor-pulley-system"],
    relatedTopicKeys: ["carpal-tunnel-syndrome", "flexor-tendon-injury"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 24,
    extraEntityKinds: ["procedure"],
  },
  {
    topicKey: "de-quervain-tenosynovitis",
    displayName: "De Quervain Tenosynovitis",
    category: "ligament-soft-tissue",
    categoryLabel: "Ligament & Soft Tissue",
    curriculumNodeSlug: "hand-de-quervain-tenosynovitis",
    prepareTopicId: "de-quervain-tenosynovitis",
    clinicalKind: "tenosynovitis",
    primaryAnatomySlugs: ["apl", "epb", "radial-nerve"],
    relatedTopicKeys: ["scaphoid-fracture"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 18,
    extraEntityKinds: ["procedure"],
  },
  // Infection & Emergency
  {
    topicKey: "flexor-tenosynovitis",
    displayName: "Flexor Tenosynovitis",
    category: "infection-emergency",
    categoryLabel: "Infection & Emergency",
    curriculumNodeSlug: "hand-flexor-tenosynovitis",
    prepareTopicId: "flexor-tenosynovitis",
    clinicalKind: "infection",
    primaryAnatomySlugs: ["fdp", "fds", "flexor-tendon-zones"],
    relatedTopicKeys: ["hand-infection", "bite-injuries", "flexor-tendon-injury"],
    ankiCardMappings: 2,
    orthobulletsQuestionMappings: 26,
    extraEntityKinds: ["classification", "procedure"],
  },
  {
    topicKey: "hand-infection",
    displayName: "Hand Infection",
    category: "infection-emergency",
    categoryLabel: "Infection & Emergency",
    curriculumNodeSlug: "hand-hand-infection",
    prepareTopicId: "hand-infection",
    clinicalKind: "infection",
    primaryAnatomySlugs: ["fds", "fdp", "digital-nerves"],
    relatedTopicKeys: ["flexor-tenosynovitis", "bite-injuries", "fingertip-injury"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 22,
    extraEntityKinds: ["procedure"],
  },
  {
    topicKey: "bite-injuries",
    displayName: "Bite Injuries",
    category: "infection-emergency",
    categoryLabel: "Infection & Emergency",
    curriculumNodeSlug: "hand-bite-injuries",
    prepareTopicId: "bite-injuries",
    clinicalKind: "infection",
    primaryAnatomySlugs: ["mcp-joint", "collateral-ligaments", "flexor-tendon-zones"],
    relatedTopicKeys: ["hand-infection", "flexor-tenosynovitis"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 16,
    extraEntityKinds: ["procedure"],
  },
  {
    topicKey: "fingertip-injury",
    displayName: "Fingertip Injury",
    category: "infection-emergency",
    categoryLabel: "Infection & Emergency",
    curriculumNodeSlug: "hand-fingertip-injury",
    prepareTopicId: "fingertip-injury",
    clinicalKind: "soft_tissue_injury",
    primaryAnatomySlugs: ["distal-phalanx", "digital-nerves"],
    relatedTopicKeys: ["nail-bed-injury", "distal-phalanx-fracture"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 14,
    extraEntityKinds: ["procedure"],
  },
  {
    topicKey: "nail-bed-injury",
    displayName: "Nail Bed Injury",
    category: "infection-emergency",
    categoryLabel: "Infection & Emergency",
    curriculumNodeSlug: "hand-nail-bed-injury",
    prepareTopicId: "nail-bed-injury",
    clinicalKind: "soft_tissue_injury",
    primaryAnatomySlugs: ["distal-phalanx"],
    relatedTopicKeys: ["fingertip-injury", "distal-phalanx-fracture"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 10,
    extraEntityKinds: ["procedure"],
  },
  {
    topicKey: "compartment-syndrome-hand",
    displayName: "Compartment Syndrome of the Hand",
    category: "infection-emergency",
    categoryLabel: "Infection & Emergency",
    curriculumNodeSlug: "hand-compartment-syndrome",
    prepareTopicId: "compartment-syndrome-hand",
    clinicalKind: "emergency",
    primaryAnatomySlugs: ["hand-compartment-complex", "interosseous-membrane"],
    relatedTopicKeys: ["hand-infection", "flexor-tenosynovitis"],
    crossClusterRefs: ["compartment-syndrome"],
    ankiCardMappings: 0,
    orthobulletsQuestionMappings: 12,
    extraEntityKinds: ["procedure"],
  },
];

export function getHandWristNeighborhood(topicKey: string): HandWristNeighborhoodDef | undefined {
  return HAND_WRIST_NEIGHBORHOODS.find((n) => n.topicKey === topicKey);
}

export function listHandWristTopicKeys(): string[] {
  return HAND_WRIST_NEIGHBORHOODS.map((n) => n.topicKey);
}

export const HAND_WRIST_SHARED_ANATOMY_SLUGS = [
  "hand-wrist-anatomy-hub",
  "radius",
  "ulna",
  "interosseous-membrane",
  "druj",
  "pruj",
  "distal-radius",
  "distal-ulna",
  "scaphoid",
  "lunate",
  "triquetrum",
  "pisiform",
  "trapezium",
  "trapezoid",
  "capitate",
  "hamate",
  "first-metacarpal",
  "second-metacarpal",
  "third-metacarpal",
  "fourth-metacarpal",
  "fifth-metacarpal",
  "proximal-phalanx",
  "middle-phalanx",
  "distal-phalanx",
  "dip-joint",
  "pip-joint",
  "mcp-joint",
  "cmc-joint",
  "scapholunate-ligament",
  "lunotriquetral-ligament",
  "tfcc",
  "thumb-ucl",
  "volar-plate",
  "collateral-ligaments",
  "fpl",
  "fdp",
  "fds",
  "epl",
  "epb",
  "apl",
  "edc",
  "ecu",
  "fcr",
  "fcu",
  "a1-pulley",
  "a2-pulley",
  "a3-pulley",
  "a4-pulley",
  "a5-pulley",
  "c1-pulley",
  "c2-pulley",
  "c3-pulley",
  "flexor-pulley-system",
  "flexor-tendon-zones",
  "extensor-tendon-zones",
  "median-nerve",
  "ulnar-nerve",
  "radial-nerve",
  "ain",
  "pin",
  "digital-nerves",
  "radial-artery",
  "ulnar-artery",
  "superficial-palmar-arch",
  "deep-palmar-arch",
  "carpal-tunnel",
  "guyon-canal",
] as const;
