"use client";
import { useEffect, useRef, useState } from "react";
import { X } from "lucide-react";
import type { MyCasesCase } from "@/lib/mycases/types";
import { LEARNING_KINDS, LEARNING_LABELS } from "../format";

export function CaseForm({close,done}:{close:()=>void;done:()=>void}){const [error,setError]=useState("");const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const rating=(name:string)=>form.get(name)===""?null:Number(form.get(name));const response=await fetch("/api/mycases/cases",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:form.get("title"),procedure_name:form.get("procedure"),diagnosis:form.get("diagnosis"),rotation_context:form.get("rotation"),attending_context:form.get("attending"),status:form.get("status"),difficulty:rating("difficulty"),autonomy:rating("autonomy"),preparation:form.get("preparation"),debrief:form.get("debrief"),tags:String(form.get("tags")||"").split(",").map(value=>value.trim()).filter(Boolean)})});if(response.ok)done();else setError((await response.json()).error||"Unable to add case.")};return <Dialog close={close} title="Add educational case"><p className="mt-1 text-sm text-slate-500">Use generic educational context only—never patient or encounter information.</p><form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><Input name="title" label="Case title" required/><Input name="procedure" label="Procedure" required/><Input name="diagnosis" label="Generic diagnosis"/><Input name="rotation" label="Rotation"/><Input name="attending" label="Attending context"/><label className="text-sm font-semibold">Status<select name="status" className="mt-1 min-h-11 w-full border border-slate-300 bg-white p-3"><option>draft</option><option>upcoming</option><option>completed</option></select></label><Rating name="difficulty" label="Difficulty (0–5)"/><Rating name="autonomy" label="Autonomy (0–5)"/><div className="sm:col-span-2"><TextArea name="preparation" label="Preparation"/><TextArea name="debrief" label="Debrief"/><Input name="tags" label="Tags (comma separated)"/></div>{error&&<p role="alert" className="text-sm text-red-600 sm:col-span-2">{error}</p>}<Actions close={close}/></form></Dialog>}
export function ItemForm({cases,initialCaseId,close,done}:{cases:MyCasesCase[];initialCaseId?:string;close:()=>void;done:()=>void}){const [error,setError]=useState("");const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch("/api/mycases/learning-items",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:form.get("kind"),title:form.get("title"),content:form.get("content"),case_id:form.get("case")||null,procedure_name:form.get("procedure"),topic:form.get("topic"),attending_context:form.get("attending"),tags:String(form.get("tags")||"").split(",").map(value=>value.trim()).filter(Boolean)})});if(response.ok)done();else setError((await response.json()).error||"Unable to add knowledge.")};return <Dialog close={close} title={initialCaseId?"Add learning from this case":"Add knowledge"}><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-semibold">Learning type<select name="kind" className="mt-1 min-h-11 w-full border border-slate-300 bg-white p-3">{LEARNING_KINDS.map(kind=><option key={kind} value={kind}>{LEARNING_LABELS[kind]}</option>)}</select></label><Input name="title" label="Title"/><label className="block text-sm font-semibold">Content<textarea name="content" required rows={6} className="mt-1 w-full border border-slate-300 p-3 outline-none focus:border-blue-600"/></label><label className="block text-sm font-semibold">Source case<select name="case" defaultValue={initialCaseId||""} className="mt-1 min-h-11 w-full border border-slate-300 bg-white p-3"><option value="">General knowledge (not case-linked)</option>{cases.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><Input name="procedure" label="Procedure"/><Input name="topic" label="Topic"/><Input name="attending" label="Attending context"/><Input name="tags" label="Tags (comma separated)"/></div>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<Actions close={close}/></form></Dialog>}
function Dialog({close,title,children}:{close:()=>void;title:string;children:React.ReactNode}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==="Escape")close()};document.addEventListener("keydown",key);ref.current?.focus();return()=>document.removeEventListener("keydown",key)},[close]);return <div className="fixed inset-0 z-[90] flex items-start justify-center overflow-y-auto bg-slate-950/65 p-4 pt-10 backdrop-blur-sm" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><div role="dialog" aria-modal="true" aria-labelledby="mycases-dialog-title" tabIndex={-1} ref={ref} className="w-full max-w-2xl bg-white p-6 shadow-2xl outline-none sm:p-8"><div className="flex items-center justify-between"><h2 id="mycases-dialog-title" className="text-2xl font-black">{title}</h2><button aria-label="Close dialog" onClick={close} className="flex h-10 w-10 items-center justify-center focus-visible:ring-2 focus-visible:ring-blue-500"><X className="h-5 w-5"/></button></div>{children}</div></div>}
function Input({name,label,required=false}:{name:string;label:string;required?:boolean}){return <label className="block text-sm font-semibold">{label}<input name={name} required={required} className="mt-1 min-h-11 w-full border border-slate-300 p-3 outline-none focus:border-blue-600 focus:ring-1 focus:ring-blue-600"/></label>}
function TextArea({name,label}:{name:string;label:string}){return <label className="mb-4 block text-sm font-semibold">{label}<textarea name={name} rows={3} className="mt-1 w-full border border-slate-300 p-3 outline-none focus:border-blue-600"/></label>}
function Rating({name,label}:{name:string;label:string}){return <label className="block text-sm font-semibold">{label}<select name={name} className="mt-1 min-h-11 w-full border border-slate-300 bg-white p-3"><option value="">Not recorded</option>{[0,1,2,3,4,5].map(value=><option key={value}>{value}</option>)}</select></label>}
function Actions({close}:{close:()=>void}){return <div className="flex justify-end gap-2 pt-3 sm:col-span-2"><button type="button" onClick={close} className="min-h-11 border border-slate-300 px-4 text-sm font-bold">Cancel</button><button className="min-h-11 bg-slate-950 px-5 text-sm font-bold text-white">Save</button></div>}
