"use client";
import { Archive, Grid2X2, List, Search, SlidersHorizontal, X } from "lucide-react";
import { useMemo, useState } from "react";
import type { MyCasesCase, MyCasesLearningItem } from "@/lib/mycases/types";
import type { CaseMediaSummaryMap, CasesViewMode } from "../ui-types";
import { relativeDate, statusLabel } from "../format";
import { SecureThumbnail } from "../media/SecureThumbnail";

type Props={cases:MyCasesCase[];items:MyCasesLearningItem[];media:CaseMediaSummaryMap;onCase:(item:MyCasesCase)=>void;onRetryMedia:(caseId:string)=>void};
export function CasesLibrary({cases,items,media,onCase,onRetryMedia}:Props){
  const [view,setView]=useState<CasesViewMode>("grid"),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[rotation,setRotation]=useState("all"),[attending,setAttending]=useState("all"),[tag,setTag]=useState("all"),[archived,setArchived]=useState(false),[sort,setSort]=useState("updated"),[filtersOpen,setFiltersOpen]=useState(false);
  const options=(key:"rotation_context"|"attending_context")=>[...new Set(cases.map(item=>item[key]).filter((value):value is string=>Boolean(value)))].sort();
  const tags=[...new Set(cases.flatMap(item=>item.tags?.map(entry=>entry.name)??[]))].sort();
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return cases.filter(item=>(archived||!item.is_archived)&&(status==="all"||item.status===status)&&(rotation==="all"||item.rotation_context===rotation)&&(attending==="all"||item.attending_context===attending)&&(tag==="all"||item.tags?.some(entry=>entry.name===tag))&&(!q||[item.title,item.procedure_name,item.diagnosis,item.rotation_context,item.attending_context,...(item.tags?.map(entry=>entry.name)??[])].some(value=>value?.toLowerCase().includes(q)))).sort((a,b)=>sort==="created"?b.created_at.localeCompare(a.created_at):sort==="procedure"?a.procedure_name.localeCompare(b.procedure_name):sort==="status"?a.status.localeCompare(b.status):b.updated_at.localeCompare(a.updated_at));},[cases,query,status,rotation,attending,tag,archived,sort]);
  const activeFilters=[status,rotation,attending,tag].filter(value=>value!=="all").length+(archived?1:0);
  const reset=()=>{setStatus("all");setRotation("all");setAttending("all");setTag("all");setArchived(false)};
  return <section aria-labelledby="cases-library-title">
    <div className="flex flex-col gap-4 border-b border-slate-200 pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">Visual case library</p><h2 id="cases-library-title" className="mt-1 text-3xl font-black tracking-tight">Cases</h2><p className="mt-1 text-sm text-slate-500">Recognize prior cases at a glance, then reopen the learning around them.</p></div><div className="flex items-center gap-2"><button aria-label="Grid view" aria-pressed={view==="grid"} onClick={()=>setView("grid")} className={`flex h-10 w-10 items-center justify-center border ${view==="grid"?"border-slate-950 bg-slate-950 text-white":"border-slate-300 bg-white text-slate-600"}`}><Grid2X2 className="h-4 w-4"/></button><button aria-label="List view" aria-pressed={view==="list"} onClick={()=>setView("list")} className={`flex h-10 w-10 items-center justify-center border ${view==="list"?"border-slate-950 bg-slate-950 text-white":"border-slate-300 bg-white text-slate-600"}`}><List className="h-4 w-4"/></button></div></div>
    <div className="mt-5 border border-slate-200 bg-white p-3"><div className="flex flex-col gap-3 md:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><span className="sr-only">Search cases</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search procedure, diagnosis, rotation, attending, or tag" className="min-h-10 w-full border border-slate-300 py-2 pl-10 pr-3 text-sm outline-none focus:border-blue-600 focus:ring-1 focus:ring-blue-600"/></label><button onClick={()=>setFiltersOpen(value=>!value)} aria-expanded={filtersOpen} className="flex min-h-10 items-center justify-center gap-2 border border-slate-300 px-4 text-sm font-bold"><SlidersHorizontal className="h-4 w-4"/>Filters{activeFilters?` (${activeFilters})`:""}</button><label className="flex items-center gap-2 text-sm"><span className="text-slate-500">Sort</span><select value={sort} onChange={event=>setSort(event.target.value)} className="min-h-10 border border-slate-300 bg-white px-3 font-semibold"><option value="updated">Recently updated</option><option value="created">Recently created</option><option value="procedure">Procedure</option><option value="status">Status</option></select></label></div>{filtersOpen&&<div className="mt-3 grid gap-3 border-t border-slate-200 pt-3 sm:grid-cols-2 xl:grid-cols-5"><Filter label="Status" value={status} set={setStatus} values={["draft","upcoming","completed","archived"]}/><Filter label="Rotation" value={rotation} set={setRotation} values={options("rotation_context")}/><Filter label="Attending context" value={attending} set={setAttending} values={options("attending_context")}/><Filter label="Tag" value={tag} set={setTag} values={tags}/><label className="flex min-h-10 items-center gap-2 border border-slate-200 px-3 text-sm font-semibold"><input type="checkbox" checked={archived} onChange={event=>setArchived(event.target.checked)}/><Archive className="h-4 w-4 text-slate-400"/>Include archived</label></div>}{activeFilters>0&&<div className="mt-3 flex items-center gap-3 text-xs text-slate-500"><span>{filtered.length} results with {activeFilters} active filter{activeFilters===1?"":"s"}</span><button onClick={reset} className="inline-flex items-center gap-1 font-bold text-blue-700"><X className="h-3 w-3"/>Clear filters</button></div>}</div>
    {view==="grid"?<div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(item=><CaseCard key={item.id} item={item} learningCount={items.filter(entry=>entry.case_id===item.id&&!entry.is_archived).length} media={media[item.id]} onClick={()=>onCase(item)} onRetry={()=>onRetryMedia(item.id)}/>)}</div>:<div className="mt-6 divide-y divide-slate-200 border-y border-slate-200 bg-white">{filtered.map(item=><button key={item.id} onClick={()=>onCase(item)} className="grid w-full gap-4 py-4 text-left outline-none hover:bg-slate-50 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-blue-500 sm:grid-cols-[144px_1fr_auto] sm:items-center sm:px-3"><SecureThumbnail media={media[item.id]} procedure={item.procedure_name} alt={`Educational thumbnail for ${item.procedure_name}`} className="aspect-[16/10]" onRetry={()=>onRetryMedia(item.id)}/><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold uppercase tracking-wide text-blue-700">{statusLabel(item.status)}</span>{item.is_archived&&<span className="text-xs font-bold text-slate-400">Archived</span>}</div><h3 className="mt-1 text-lg font-bold">{item.procedure_name}</h3><p className="mt-1 text-sm text-slate-500">{item.diagnosis||item.title} · {item.rotation_context||"No rotation"}</p></div><div className="text-left text-xs text-slate-500 sm:text-right"><strong className="block text-sm text-slate-800">{media[item.id]?.count??0} media</strong>{relativeDate(item.updated_at)}</div></button>)}</div>}
    {!filtered.length?<div className="mt-6 border border-dashed border-slate-300 bg-white py-16 text-center"><Search className="mx-auto h-7 w-7 text-slate-300"/><h3 className="mt-3 font-bold">No cases match this view</h3><p className="mt-1 text-sm text-slate-500">Clear a filter or try a broader educational search.</p></div>:null}
  </section>;
}
function Filter({label,value,set,values}:{label:string;value:string;set:(value:string)=>void;values:string[]}){return <label className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}<select value={value} onChange={event=>set(event.target.value)} className="mt-1 block min-h-10 w-full border border-slate-300 bg-white px-3 text-sm font-semibold normal-case tracking-normal text-slate-800"><option value="all">All</option>{values.map(option=><option key={option}>{option}</option>)}</select></label>}
function CaseCard({item,learningCount,media,onClick,onRetry}:{item:MyCasesCase;learningCount:number;media:CaseMediaSummaryMap[string];onClick:()=>void;onRetry:()=>void}){return <button onClick={onClick} className="group overflow-hidden border border-slate-200 bg-white text-left shadow-sm outline-none transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-lg focus-visible:ring-2 focus-visible:ring-blue-500 motion-reduce:transform-none"><SecureThumbnail media={media} procedure={item.procedure_name} alt={`Educational thumbnail for ${item.procedure_name}`} className="aspect-[16/10]" onRetry={onRetry}/><div className="p-5"><div className="flex items-center justify-between gap-3"><span className="text-xs font-bold uppercase tracking-[.12em] text-blue-700">{statusLabel(item.status)}</span><span className="text-xs text-slate-500">{media?.count??0} media</span></div><h3 className="mt-3 line-clamp-2 text-lg font-black leading-6">{item.procedure_name}</h3><p className="mt-1 line-clamp-2 min-h-10 text-sm leading-5 text-slate-500">{item.diagnosis||item.title}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-xs text-slate-500"><span>{item.rotation_context||"No rotation"}</span><span>{learningCount} learning</span></div><p className="mt-2 text-xs text-slate-400">{relativeDate(item.updated_at)}</p></div></button>}
