import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const root=new URL("../../../../",import.meta.url);
const migration=readFileSync(new URL("supabase/migrations/20260720_150000_mycases_secure_educational_media.sql",root),"utf8").toLowerCase();
const hardening=readFileSync(new URL("supabase/migrations/20260720_160000_mycases_media_storage_bypass_hardening.sql",root),"utf8").toLowerCase();
const verification=readFileSync(new URL("supabase/verification/mycases_secure_educational_media.sql",root),"utf8").toLowerCase();
const uploadRoute=readFileSync(new URL("src/app/api/mycases/cases/[caseId]/assets/route.ts",root),"utf8");
const viewRoute=readFileSync(new URL("src/app/api/mycases/assets/[assetId]/view/route.ts",root),"utf8");
const assetRoute=readFileSync(new URL("src/app/api/mycases/assets/[assetId]/route.ts",root),"utf8");
const repository=readFileSync(new URL("src/lib/mycases/media/repository.ts",root),"utf8");
const client=readFileSync(new URL("src/components/mycases/media/SecureMediaGallery.tsx",root),"utf8");
const reconciliation=readFileSync(new URL("scripts/reconcile-mycases-educational-media.ts",root),"utf8");
assert(migration.includes("mycases_cases_id_user_id_key"));
assert(migration.indexOf("mycases_cases_id_user_id_key")<migration.indexOf("create table if not exists public.mycases_educational_assets"));
assert(migration.includes("foreign key (case_id, user_id)")); assert(migration.includes("unique (id, user_id)"));
assert(migration.includes("public = false")); assert.equal(migration.includes("public_url"),false); assert.equal(migration.includes("original_filename"),false);
assert.equal((migration.match(/mycases_educational_assets_(select|insert|update|delete)_own/g)||[]).length>=8,true);
assert(migration.includes("auth.uid() = user_id"));
for(const operation of ["select","insert","update","delete"]){
  assert(migration.includes(`drop policy if exists mycases_educational_media_${operation}_own on storage.objects`));
  assert.equal(migration.includes(`create policy mycases_educational_media_${operation}_own`),false);
  assert(hardening.includes(`drop policy if exists mycases_educational_media_${operation}_own on storage.objects`));
}
assert(hardening.startsWith("-- close the authenticated-client storage bypass"));
assert(hardening.includes("begin;")); assert(hardening.includes("commit;"));
assert.equal(hardening.includes("create policy"),false);
assert(verification.includes("forbidden educational asset metadata")); assert(verification.includes("storage.buckets"));
assert(verification.includes("roles && array['public', 'anon', 'authenticated']::name[]"));
assert(verification.includes("direct anon/authenticated storage access"));
assert(uploadRoute.includes("requireMyCasesApiUser")); assert(uploadRoute.includes('new Set(["file","caption","attestation"])')); assert(uploadRoute.includes('form.get("attestation")!=="true"'));
assert(viewRoute.includes("requireMyCasesApiUser")); assert(repository.includes('.eq("id", assetId).eq("user_id", userId)'));
assert(repository.includes("createSignedUrl")); assert.equal(repository.includes("getPublicUrl"),false);
assert(repository.includes("if (uploaded.length) await admin.storage")); assert(repository.includes("if (!row) return { deleted:true }"));
assert(repository.includes("randomUUID()")); assert.equal(repository.includes("file.name"),false); assert.equal(repository.includes("console."),false);
assert(repository.includes('import "server-only"'));
assert(repository.indexOf("assertSanitizedImage(image)")<repository.indexOf(".upload(imageKey"));
assert(repository.includes("assertOwnedObjectKeys(row)"));
assert(repository.includes("delete_state_failed"));
assert(assetRoute.includes('key=>key!=="caption"'));
assert.equal(client.includes(".storage"),false); assert.equal(client.includes("supabase"),false);
assert(client.includes("/api/mycases/"));
assert(client.includes("thumbnailOnly=true"));
assert(reconciliation.includes('mode: apply ? "apply" : "dry-run"'));
assert(reconciliation.includes("if (!apply || !plan.orphanObjectKeys.length) return"));
assert.equal(reconciliation.includes("signedUrl"),false); assert.equal(reconciliation.includes("caption"),false);
console.log("MyCases educational media security contract tests passed");
