-- Phase 3 staging and delivery foundation. No canonical data or releases are created here.
begin;
create table public.anki_editor_incorporation_batches(id uuid primary key default gen_random_uuid(),batch_key text not null unique,status text not null default 'draft',input_checksum text not null,preview_checksum text not null,rules_version text not null,created_by_user_id uuid not null references auth.users(id) on delete restrict,target_draft_release_id uuid null references public.anki_deck_releases(id) on delete restrict,created_at timestamptz not null default now(),validated_at timestamptz null,incorporated_at timestamptz null,safe_metadata jsonb not null default '{}',constraint anki_incorp_batch_status check(status in('draft','validated','ready','incorporating','incorporated','failed','cancelled','superseded')),constraint anki_incorp_batch_hash check(input_checksum~'^[a-f0-9]{64}$'and preview_checksum~'^[a-f0-9]{64}$'),constraint anki_incorp_batch_safe check(public.educational_metadata_is_safe(safe_metadata)));
create table public.anki_editor_incorporation_items(id uuid primary key default gen_random_uuid(),batch_id uuid not null references public.anki_editor_incorporation_batches(id) on delete restrict,proposal_id uuid not null references public.anki_editor_workspace_proposals(id) on delete restrict,proposal_evidence_hash text not null,operation text not null,outcome text not null,base_canonical_card_version_id uuid null references public.canonical_card_versions(id) on delete restrict,proposed_content_hash text not null,error_codes text[] not null default '{}',result_canonical_card_id uuid null references public.canonical_cards(id) on delete restrict,result_canonical_card_version_id uuid null references public.canonical_card_versions(id) on delete restrict,created_at timestamptz not null default now(),constraint anki_incorp_item_unique unique(batch_id,proposal_id),constraint anki_incorp_item_operation check(operation in('new_version','new_card')),constraint anki_incorp_item_outcome check(outcome in('ready','blocked','excluded','incorporated','failed')),constraint anki_incorp_item_hashes check(proposal_evidence_hash~'^[a-f0-9]{64}$'and proposed_content_hash~'^[a-f0-9]{64}$'));
create table public.anki_kg_expansion_review_packets(id uuid primary key default gen_random_uuid(),proposal_id uuid not null unique references public.anki_editor_workspace_proposals(id) on delete restrict,proposal_evidence_hash text not null,status text not null default 'pending',suggestion_type text not null,preferred_label text not null,entity_type text not null,description text not null,existing_entity_id uuid null references public.canonical_entities(id) on delete restrict,created_at timestamptz not null default now(),resolved_at timestamptz null,constraint anki_kg_packet_status check(status in('pending','in_review','approved','rejected','materialized','superseded')),constraint anki_kg_packet_type check(suggestion_type in('new_entity','new_alias')),constraint anki_kg_packet_hash check(proposal_evidence_hash~'^[a-f0-9]{64}$'));
create table public.anki_kg_expansion_review_actions(id uuid primary key default gen_random_uuid(),packet_id uuid not null references public.anki_kg_expansion_review_packets(id) on delete restrict,reviewer_user_id uuid not null references auth.users(id) on delete restrict,decision text not null,reason_codes text[] not null default '{}',notes text not null default '',idempotency_key uuid not null,created_at timestamptz not null default now(),constraint anki_kg_action_decision check(decision in('approve','reject','request_changes','defer')),constraint anki_kg_action_notes check(char_length(notes)<=2000),constraint anki_kg_action_idempotent unique(reviewer_user_id,idempotency_key));
create table public.anki_deck_release_artifacts(id uuid primary key default gen_random_uuid(),deck_release_id uuid not null references public.anki_deck_releases(id) on delete restrict,artifact_type text not null,artifact_schema_version text not null,artifact_checksum text not null,object_key text null,byte_size bigint null,media_type text null,status text not null default 'draft',created_at timestamptz not null default now(),published_at timestamptz null,constraint anki_release_artifact_unique unique(deck_release_id,artifact_type,artifact_checksum),constraint anki_release_artifact_type check(artifact_type in('manifest','bootstrap_apkg','delta_bundle','media_index')),constraint anki_release_artifact_hash check(artifact_checksum~'^[a-f0-9]{64}$'),constraint anki_release_artifact_size check(byte_size is null or byte_size>0),constraint anki_release_artifact_status check(status in('draft','validated','published','superseded','withdrawn')));
create table public.anki_deck_media_assets(id uuid primary key default gen_random_uuid(),deck_release_id uuid not null references public.anki_deck_releases(id) on delete restrict,canonical_card_version_id uuid null references public.canonical_card_versions(id) on delete restrict,logical_filename text not null,content_sha256 text not null,mime_type text not null,byte_size bigint not null,object_key text not null,license_status text not null,provenance jsonb not null default '{}',created_at timestamptz not null default now(),constraint anki_media_asset_unique unique(deck_release_id,logical_filename),constraint anki_media_asset_hash check(content_sha256~'^[a-f0-9]{64}$'),constraint anki_media_asset_size check(byte_size>0),constraint anki_media_asset_mime check(mime_type in('image/png','image/jpeg','image/gif','image/webp','audio/mpeg','audio/ogg')),constraint anki_media_asset_license check(license_status in('owned','licensed','public_domain','excluded')),constraint anki_media_asset_safe check(public.educational_metadata_is_safe(provenance)));
create table public.anki_deck_sync_acknowledgements(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete restrict,device_token_id uuid not null references public.brobot_anki_device_tokens(id) on delete restrict,deck_release_id uuid not null references public.anki_deck_releases(id) on delete restrict,sync_plan_checksum text not null,installed_manifest_checksum text not null,status text not null,conflict_count integer not null default 0,created_at timestamptz not null default now(),constraint anki_sync_ack_hash check(sync_plan_checksum~'^[a-f0-9]{64}$'and installed_manifest_checksum~'^[a-f0-9]{64}$'),constraint anki_sync_ack_status check(status in('planned','applied','partial','failed','rolled_back')),constraint anki_sync_ack_conflicts check(conflict_count>=0));
create function public.guard_anki_phase3_evidence()returns trigger language plpgsql as $$begin raise exception 'phase 3 evidence is immutable';end$$;
create trigger guard_anki_incorporation_item before update or delete on public.anki_editor_incorporation_items for each row execute function public.guard_anki_phase3_evidence();
create trigger guard_anki_kg_action before update or delete on public.anki_kg_expansion_review_actions for each row execute function public.guard_anki_phase3_evidence();
create trigger guard_anki_sync_ack before update or delete on public.anki_deck_sync_acknowledgements for each row execute function public.guard_anki_phase3_evidence();
do $$declare t text;begin foreach t in array array['anki_editor_incorporation_batches','anki_editor_incorporation_items','anki_kg_expansion_review_packets','anki_kg_expansion_review_actions','anki_deck_release_artifacts','anki_deck_media_assets','anki_deck_sync_acknowledgements']loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);execute format('revoke all on public.%I from anon,authenticated,service_role',t);execute format('grant select,insert,update on public.%I to service_role',t);end loop;end$$;
comment on table public.anki_editor_incorporation_batches is 'Review-gated staging only. A batch does not itself authorize canonical writes or release publication.';
commit;
